UK-Export-Finance/dtfs2

portal-api/api-tests/fixtures/deal-fully-completed-issued-and-unissued-facilities.js
portal-api/api-tests/fixtures/deal-fully-completed.js
portal-api/src/v1/controllers/integration/helpers/calculate-facility-conversion-date.js

There was an issue creating the requestedCoverEndDate so today it was calculating one of the facilities as having an endDate of 29/02/2022.
This was due to referencing the same now variable in several places as adding/subtracting days/months/years to calculate a date. Each respective add/subtract would use the value left from the previous one rather than based on todays date.

Fixed wrong calculation of date in mock data

---

reference-data-proxy/src/v1/controllers/companies-house.controller.js

https://ukef-dtfs.atlassian.net/browse/DTFS2-4328
Companies house api expects 8 char numbers. Anything less is led with 0. Added 0 pad if less than 8 chars.

DTFS2-4328: pad company no to always be 8 chars

---

portal-api/api-tests/api.js
portal-api/api-tests/fixtures/gef/application.js
portal-api/api-tests/fixtures/gef/facilities.js
portal-api/api-tests/v1/gef/application.api-test.js
portal-api/api-tests/v1/gef/facilities.api-test.js
portal-api/src/v1/gef/controllers/application-submit.js
portal-api/src/v1/gef/controllers/application.controller.js
portal-api/src/v1/gef/controllers/facilities.controller.js
portal-api/src/v1/gef/models/application.js
portal-api/src/v1/gef/models/facilities.js
portal-api/src/v1/gef/routes.js

- increase `submissionCount` when deal status changes to 'submitted'
- add `submissionDate` when deal status changes to 'submitted'
- add `submittedAsIssuedDate` to issued facilities when deal status changes to 'submitted'
- calculate `ukefExposure` when a facility is updated
- seperate `update` and `getAllFacilitiesByApplicationId` functionality in facilities controller. Allows us to get & update facilities without req & res.
- improved facilities unit tests so that "get all" is actually tested when `req.query.applicationId` is passed.
- create `addSubmissionData` function for when a deal status changes to submit. Can be expanded to other things moving forwards.
~Need this PR merged first https://github.com/foundry4/dtfs2/pull/165~

DTFS2-4524 - add submission data to GEF deals & facilities

---

trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
trade-finance-manager-api/src/v1/helpers/notify-template-formatters.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js

- some facility fields used in the email template were missing after deal submission field mappings were introduced
- only populate "unissued facilities" email section if there are unissued facilities

DTFS2-4239 - fix tfm submission email formatting issues with facilities

---

trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/__mocks__/mock-cash-contingent-facilities.js
trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal-MIA.js
trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
trade-finance-manager-api/src/v1/controllers/deal.pricing-and-risk.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.js

On TFM deal submit, some default values are added to the deal. This PR ensures that they work for GEF and not just BSS.
- default `exporterCreditRating` for all AIN deals regardless of deal type
- add tests for default `lossGivenDefault` and `riskProfile` for GEF facilities
- add mock Contingent facility to TFM api mocks
- add maker to GEF deal submission mapping

DTFS2-4511 - TFM default pricing and risk values for GEF

---

dtfs-central-api/api-tests/v1/gef-deals/gef-deal-get.api-test.js
dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facilities-get.api-test.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/create-gef-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/get-facilities.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-submit-deal.controller.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js
dtfs-central-api/src/v1/routes/tfm-routes.js
e2e-tests/gef/cypress/integration/facility-value.spec.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-AIN-deal-creates-tfm-deal-stage-and-product/submit-AIN-deal-creates-tfm-deal-stage-and-product.spec.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIA-deal-creates-tfm-deal-stage-and-product/submit-MIA-deal-creates-tfm-deal-stage-and-product.spec.js
e2e-tests/trade-finance-manager/cypress/integration/partials/caseSummary.js
gef-ui/templates/partials/facility-currency.njk
portal-api/src/v1/gef/enums.js
portal-api/src/v1/gef/models/facilities.js
trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/mappings/map-deal.js
trade-finance-manager-ui/server/graphql/queries/deal-query.js
trade-finance-manager-ui/server/graphql/queries/facility-query.js
trade-finance-manager-ui/templates/case/_macros/case-summary.component-test.js
trade-finance-manager-ui/templates/case/_macros/case-summary.njk

- central API: add `applicationId` as ObjectId when creating GEF facility
- central API: get GEF facilities with `applicationId` as ObjectId instead of string
- central API: endpoint to get all TFM facilities by `applicationId`.
- TFM API: get TFM facilities when mapping deal for UI with a single API call
- GEF UI: rename YEN currency value to JPY
- TFM UI: query and display TFM product

Fix/DTFS2-4380 - TFM getting GEF facilities with one API call, currency & product fixes

---

dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facilities-get.api-test.js
dtfs-central-api/api-tests/v1/user/user-get.api-test.js
dtfs-central-api/api-tests/v1/user/user-post.api-test.js
dtfs-central-api/src/constants/routes.js
dtfs-central-api/src/createApp.js
dtfs-central-api/src/v1/controllers/portal/deal/get-deal.controller.js
dtfs-central-api/src/v1/controllers/user/create-user.controller.js
dtfs-central-api/src/v1/controllers/user/get-user.controller.js
dtfs-central-api/src/v1/routes/index.js
dtfs-central-api/src/v1/routes/user-routes.js
trade-finance-manager-api/api-tests/send-deal-submit-emails.api-test.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIN.js
trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
trade-finance-manager-api/src/v1/helpers/issued-facilities.api-test.js
trade-finance-manager-api/src/v1/helpers/issued-facilities.js
trade-finance-manager-api/src/v1/helpers/notify-template-formatters.api-test.js
trade-finance-manager-api/src/v1/helpers/notify-template-formatters.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-gef-deal.js

When TFM receives a deal, an email needs to be sent to the Maker that includes a list of issued and unissued facilities. This was already in place for BSS deals, but not GEF. This PR ensures that all functions have the necessary data for GEF deal.
- central API: add get & create user endpoints
- central API: when getting a GEF deal, return maker (so it can be used for sending email)
- TFM API: add Cash & Contingent facilities to `issued-facilities` helper
- TFM API: split up and clean `send-deal-submit-emails`, improve test coverage
- TFM API: split up and clean `notify-template-formatters`, add test coverage
- TFM API: submitted facilities mapping: use `bankReference` instead of `bankReferenceNumber`

DTFS2-4362 - TFM email acknowledgement working for GEF deal/facilities

---

portal/server/nunjucks-configuration/formatAsCurrency.js

https://ukef-dtfs.atlassian.net/browse/DTFS2-4339
- Fixes issue where decimals were being ignored. `formatAsCurrency` filter was casting as an Int, so changed to float

DTFS2-4339: nunjucks currency format filter float fix

---

e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
utils/mock-data-loader/gef/exporter.js
utils/mock-data-loader/insert-mocks-gef.js

- remove incomplete exporters from GEF data. Can cause issues with estore
- in GEF submit-to-ukef e2e test, use a deal with only 1 facility
- disable estore API call until it doesn't error (pending Mulesoft IT team)

DTFS2-4727 - only call estore if BSS

---

e2e-tests/trade-finance-manager/cypress/fixtures/create-mock-deal.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-search.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort-by-buyer.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort-by-exporter.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort-by-ukefDealId.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort.spec.js
trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js

- reduce the amount of deals & facilities used in TFM sorting tests
- check expected ascending/descending properties based on the deal data _after_ submission, instead of based on the mock data we provide before submission

Fix TFM sorting tests

---

README.md
docker-compose.yml

Changes nodemon watch to legacy mode to make it work for windows users. Works as normal for others. Common problem with containers and mounted drives (https://github.com/remy/nodemon#application-isnt-restarting)

fix: nodemon watch to legacy mode for windows

---

reference-data-proxy/src/createApp.js
reference-data-proxy/src/drivers/db-client.js
reference-data-proxy/src/index.js
reference-data-proxy/src/v1/controllers/countries.controller.js
reference-data-proxy/src/v1/controllers/estore.controller.js
reference-data-proxy/src/v1/controllers/number-generator.controller.js

Currently in e2e tests the number generator isn't called, we get the same random number that we generate ourselves.
Therefore external API calls can fail - i.e, Estore; because they rely on ukefID from number generator.
This PR removes the promise rejection in estore controller which allows TFM deal submission to continue without being blocked by Estore.

Temporarily fix estore

---

trade-finance-manager-api/src/graphql/schemas/index.js
trade-finance-manager-api/src/v1/controllers/deal.controller.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/graphql/queries/deals-query-light.js
trade-finance-manager-ui/server/graphql/queries/deals-query.js

Previously if for some reason, TFM API deals/facilities query doesn't get returned, the UI just hangs and says eg. "cannot read deals of undefined". Very unhelpful.
- Make deal and facility UKEF IDs optional in TFM GraphQL schema. This way, some things display in the UI rather than erroring when Number Generator doesn't work and the ID doesn't exist.
- Add logs to deal, deals and facility queries so that if the API returns GraphQL errors, they are logged out.
- Fix issue where "all deals" was not using the light query version. My fault for missing this. The non-light version does additional API calls that TFM UI does not need. The light version only returns what TFM UI needs (e.g no facilities data or eligibility)
- Fix some typos

Improve TFM GraphQL queries

---

portal-api/README.md
portal-api/api-tests/fixtures/gef/application.js
portal-api/api-tests/v1/bonds/bonds.api-test.js
portal-api/api-tests/v1/gef/facilities.api-test.js
portal-api/api-tests/v1/loan/loan.api-test.js
portal-api/src/v1/controllers/bond-change-cover-start-date.controller.js
portal-api/src/v1/controllers/bond-issue-facility.controller.js
portal-api/src/v1/controllers/bonds.controller.js
portal-api/src/v1/controllers/deal-status/create-ukef-ids.js
portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.js
portal-api/src/v1/controllers/deal-status/update-issued-facilities.js
portal-api/src/v1/controllers/deal-status/update-submitted-issued-facilities.js
portal-api/src/v1/controllers/facilities.controller.js
portal-api/src/v1/controllers/integration/type-b-helpers/update-facilities.js
portal-api/src/v1/controllers/loan-change-cover-start-date.controller.js
portal-api/src/v1/controllers/loan-issue-facility.controller.js
portal-api/src/v1/controllers/loans.controller.js
portal-api/src/v1/gef/controllers/facilities.controller.js
portal-api/src/v1/gef/models/application.js
portal-api/src/v1/gef/models/facilities.js

When a GEF/BSS facility is updated, update the `facilitiesUpdated` timestamp in the associated deal.
This is required for Cedar reporting (external system that will query our data)

DTFS2-4525 - GEF/BSS - Add facilitiesUpdated timestamp to deal

---

dtfs-central-api/api-tests/v1/tfm/deal/tfm-deals-get-query-field.api-test.js
dtfs-central-api/api-tests/v1/tfm/deal/tfm-deals-get.api-test.js
dtfs-central-api/src/v1/controllers/portal/facility/create-facility.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals-date-helpers.api-test.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals-date-helpers.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
dtfs-central-api/src/v1/routes/bank-routes.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.js
trade-finance-manager-api/src/graphql/resolvers/query-deals-light.js
trade-finance-manager-api/src/graphql/schemas/index.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal.controller.js
trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
trade-finance-manager-api/src/v1/controllers/tasks.controller.js
trade-finance-manager-ui/server/graphql/queries/deals-query.js
trade-finance-manager-ui/templates/case/underwriting/managers-decision/_macros/managers-decision-submitted.component-test.js
trade-finance-manager-ui/templates/case/underwriting/managers-decision/_macros/managers-decision-submitted.njk

- Without this change, only deals with specific timestamps would get returned if they are passed into the `byField` request body. 
- Now, a date format can be passed in, e.g '01-12-2021' and any timestamp that's within this day will be returned in the response.
- How? We generate start-of-day and end-of-day timestamps with `date-fns` and then use these in the MongoDB query, with `$gte`/`$lte` operators.
- Create `get-deals-date-helpers` function for API call:
- keeps date input format and supported timestamp fields in one place.
- main function: `dayStartAndEndTimestamps`: given a date in '01-12-2021' format, this will return 2 timestamps of the start and end of this day.
- all of these functions are then used in the "get deals" endpoint/MongoDB query, if an appropriate field is passed …

DTFS2-4525 - Fix/improve TFM API deals query for external teams. Query timestamp fields by date string

---

gef-ui/server/nunjucks-configuration/filter-getStatusLabel.js
portal/server/nunjucks-configuration/filter-getStatusLabel.test.js

There are two `getStatusLabel` functions used for GEF in Portal. One for Deal page, the other for GEF Deals table.
This one, for the Deals table, was missed in previous PR.

fix/update GEF statusLabel nunjuck filter used in Deals page

---

trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
trade-finance-manager-api/src/constants/tasks.js
trade-finance-manager-api/src/v1/controllers/deal.tasks.api-test.js
trade-finance-manager-api/src/v1/controllers/deal.tasks.js
trade-finance-manager-api/src/v1/helpers/create-tasks.api-test.js
trade-finance-manager-api/src/v1/helpers/create-tasks.js

- Add a task creation rule for a BSS MIA deal that has eligibility criteria answer 11 as false (additional task gets added)
- Add `isConditional` flag to tasks that can be included or not included (on deal submission), depending on deal data
- Remove ability to pass a list of 'excluded tasks' to task creation function
- Instead of having a list of 'exluded tasks', we now only specifically define a list of 'additional tasks' that will be added, depending on the deal data
- Make `deal.tasks.js` more functional - each task rule in it's own function
- Add logic to 'create group tasks' function so that a task will only be added to a group if:
- the task is *not*  a conditional task (therefore always applies)
- or the task is a conditional task and is included in the list of additional tasks to …

DTFS2-3549 - TFM tasks creation based on list of additional tasks (depending on deal data)

---

trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityFeeType.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityFeeType.js
trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal-MIA.js
trade-finance-manager-api/src/v1/controllers/update-facilities.js
trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js

- do not calculate GEF facility fee record if the deal type is MIA
- do not use `submittedAsIssuedDate` in facility `coverStartDate` mapping, just use the `coverStartDate`.
- add missing facility feeType mapping for "At Maturity" value
- lint fixes

DTFS2-4973 - TFM - GEF facility/fee record fixes

---

trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js
trade-finance-manager-api/src/graphql/reducers/deals.api-test.js
trade-finance-manager-api/src/graphql/reducers/deals.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.js
trade-finance-manager-ui/server/graphql/queries/deal-query.js

- add `dealType`, `facilitiesUpdated` and `eligibility` mappings to deals query reducer, for GEF deals
- add `dateOfLastAction` to GEF deal details reducer mapping

TFM graphQL deals query patches for Cedar/external integration

---

trade-finance-manager-api/src/constants/tasks.js
trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks-populated.js
trade-finance-manager-api/src/v1/__mocks__/mock-MIA-tasks.js

Don't rely on e.g. "group_1.group_title", just name the group title constant as to what the group/title actually is.

Rename TFM task group title constants

---

gef-ui/server/utils/helpers.js
gef-ui/server/utils/helpers.test.js

This patch allows maker from the same bank to re-submit the application to the checker provided the user role is `Maker`.

DTFS2-5078 - Maker from same bank can re-submit

---

reference-data-proxy/src/v1/controllers/estore.controller.js

- currently the facilityIdentifer is a number and this throws an error with eStore as it only accepts strings

Convert the facilityIdentifier to string

---

dtfs-central-api/src/v1/controllers/portal/deal/update-deal-status.controller.js

There is a more useful console log further down in the function.

remove console.log we don't need

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-AIN-deal-creates-tfm-deal-stage-and-product/submit-AIN-deal-creates-tfm-deal-stage-and-product.spec.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIA-deal-creates-tfm-deal-stage-and-product/submit-MIA-deal-creates-tfm-deal-stage-and-product.spec.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/AIN-deal/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIA-deal/dealThatJustNeedsDates.json
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/deal.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-search.spec.js
e2e-tests/trade-finance-manager/cypress/integration/pages/dealsPage.js
trade-finance-manager-api/src/graphql/reducers/deals-light.api-test.js
trade-finance-manager-api/src/graphql/reducers/deals-light.js
trade-finance-manager-ui/templates/deals/_macros/deals-table.component-test.js
trade-finance-manager-ui/templates/deals/_macros/deals-table.njk

This fixes an issue where exporter company name and submissionType was now displaying in the TFM deals table. This was caused after data changes.
- add `submissionType` and `exporter` to deals-light query
- `deals-table` using `exporter.companyName` instead of `supplierName`
- add extra e2e tests/assertions for TFM displaying submissionType, exporter name and all other fields, in deals table

Fix TFM mappings for deals table, improve tests

---

azure-functions/acbs-function/api.js
azure-functions/acbs-function/helpers/activity.js
azure-functions/acbs-function/mappings/deal/helpers/get-deal-currency.js

This is a bug patch for an existing ticket (4054).
Following rectifications have been applied in this patch:
* `await` and `async` keyword has been added to respective calls,
* `comments` property check, as no comments throws error when `filter` is called on an undefined property.
* `currency.id` check when the response contains JSON object rather than a string repose

DTFS2-4054 : TFM ACBS interaction activites

---

trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js

This is a bug patch of the above ticket, which was caused due to the reference to an old application variable.
`portalMINUpdate` variable has the updated deal status after MIA -> MIN deal status update.

DTFS2-4583 : ACBS GEF MIN Records

---

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-all-tasks.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-helpers.js
trade-finance-manager-api/src/v1/controllers/send-tfm-email.js
trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
trade-finance-manager-api/src/v1/controllers/tasks.controller.js
trade-finance-manager-api/src/v1/helpers/tasks.api-test.js
trade-finance-manager-api/src/v1/helpers/tasks.js
trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.api-test.js
trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js

- ensure that when the Underwriting Group Tasks are unlocked, emails are sent out.
- only unlock a task in a group, if *all* tasks in the previous group are completed (it used to only check the previous task).
- improve test coverage

DTFS2-4174 - TFM tasks patches (update unlocking task rule, send emails for underwriting tasks unlocking)

---

portal-api/api-tests/v1/gef/application.api-test.js
portal-api/src/v1/gef/controllers/application.controller.js

Sending an email when the deal status changes previously relied on references to uppercase constants and matching uppercase value in the deal. We changed the uppercase deal status to be non-uppercase and this stopped the emails from being sent (no status found, therefore Notify would reject the email because of missing email variables).
There was also no test coverage for this.
This is now fixed, added test coverage.

fix - GEF status update emails

---

trade-finance-manager-api/api-tests/v1/mappings/map-deals.api-test.js
trade-finance-manager-api/src/createApp.js
trade-finance-manager-api/src/v1/mappings/map-deals.js

- update `map-deals` BSS/EWCS facility API call to consume _id from object (used to rely on this being an array of ids)
- add test coverage
- add graphQL error response handling so that:
- if user is authenticated and for some reason the resolver does not return any data, it will throw a custom error.
- if user is not authenticated, it will throw default unauth error from middleware
Without the custom error handling - if a user was authenticated and there was an error with the resolvers, this would be returned which is misleading and has tripped us up many times.
```js
[
{ message: 'Not Authorised!' }
]
```
Now it will return:
```js
[
{ message: 'Server error returning query.' }
]
```

fix TFM deals query issue, improve graphQL error handling

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal-unissued-facilities/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal/dealThatJustNeedsDates.json

Without this, a "missing email variable" error is thrown in E2E tests.
In the real world this would exist as it's a required field.

Add exporter.companyName to mock BSS deals used in E2E tests

---

trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal-MIN.js
trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js
trade-finance-manager-api/src/v1/helpers/get-submission-date.api-test.js
trade-finance-manager-api/src/v1/helpers/get-submission-date.js

This bug patch mitigates GEF email variable for submission date. If the application is MIN `manualInclusionNoticeSubmissionDate` is returned else `submissionDate` thus rendering MIN submission date in the confirmation email.
* Introduction of `getSubmissionDate` helper function to ascertain submission date.
* `manualInclusionNoticeSubmissionDate` has been updated to `1234` on mock MIN deal.
* Updated jest test

DTFS2-5355 : GEF Email

---

portal-api/src/v1/controllers/reports/unissued-facilities.controller.js

- Portal - Unissued facilities report - Days to issue on BSS/EWCS using MIA submission date rather than MIN
- It was using the `manualInclusionApplicationSubmissionDate`. it should have used `manualInclusionNoticeSubmissionDate`

DTFS2-5408: Unissued facilities report - Days to issue on BSS/EWCS using MIA submission date rather than MIN

---

azure-functions/acbs-function/acbs-issue-facility/index.js
azure-functions/acbs-function/helpers/date.js
azure-functions/acbs-function/mappings/facility/facility-fee.js
azure-functions/acbs-function/mappings/facility/facility-update.js
azure-functions/acbs-function/mappings/facility/helpers/get-income-class-code.js
reference-data-proxy/src/utils/swagger-definitions/acbs.ts
reference-data-proxy/src/v1/controllers/acbs.controller.ts
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/acbs.controller.js

Upon issuance of a facility, its `loan` and `fee` records must be created. This ticket aims to deliver respective ACBS records creations, while keeping the mapping functions consistent for both creation and update. 
* Reduction of arguments when issuing facility in `acbs.controller`.
* Optimised `deal` object for required properties only.
* `formatDate` now evaluates EPOCH date in string or integer, mitigates returning Invalid date.
* Removal of unwanted argument from `getIncomeClassCode` helper function.
* Improved documentation.

DTFS2-4585 : Facility issue - Loan & Fee records creations

---

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-keyword.spec.js
portal/server/constants/field-names.js
portal/server/controllers/dashboard/deals/deals-filters-keyword-query.js
portal/server/controllers/dashboard/deals/deals-filters-keyword-query.test.js
portal/server/controllers/dashboard/deals/deals-filters-query.js
portal/server/controllers/dashboard/deals/deals-filters-query.test.js
portal/server/controllers/dashboard/deals/selected-filters.js
portal/server/controllers/dashboard/deals/selected-filters.test.js
portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.js
portal/server/controllers/dashboard/facilities/facilities-filters-keyword-query.test.js
portal/server/controllers/dashboard/facilities/facilities-filters-query.js
portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
portal/server/controllers/dashboard/facilities/index.js
portal/server/controllers/dashboard/facilities/index.test.js
portal/server/controllers/dashboard/facilities/selected-filters.js
portal/server/controllers/dashboard/facilities/selected-filters.test.js
portal/server/controllers/dashboard/filters/generate-keyword-query.js
portal/server/controllers/dashboard/filters/generate-keyword-query.test.js
portal/templates/dashboard/facilities.njk

This adds the ability to filter by keyword in Dashboard facilities, just like deals, but with different fields.
Also as part of this - created a resuable `generateKeywordQuery` function(s) that is consumed by both deals and facilities. Just need to pass in an array of fields and the keyword value, and it'll generate an array of objects with correct format/regex that'll be sent to the API for MongoDB query. 🚀

DTFS2-4615 - Filter dashboard facilities by keyword. Reusable keyword query functions

---

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-remove-all-filters.spec.js
e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-main-container-filter-remove.spec.js
e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-panel-filter-remove.spec.js
portal/Dockerfile
portal/server/constants/dashboard-filters.js
portal/server/constants/dashboard.js
portal/server/constants/index.js
portal/server/controllers/dashboard/deals/index.js
portal/server/controllers/dashboard/deals/index.test.js
portal/server/controllers/dashboard/facilities/index.js
portal/server/controllers/dashboard/facilities/index.test.js
portal/server/controllers/dashboard/facilities/selected-filters.js
portal/server/controllers/dashboard/facilities/selected-filters.test.js
portal/server/controllers/dashboard/filters/generate-selected-filters.js
portal/server/controllers/dashboard/filters/generate-selected-filters.test.js
portal/server/controllers/dashboard/filters/remove-filter-from-session.js
portal/server/controllers/dashboard/filters/remove-filter-from-session.test.js
portal/server/controllers/dashboard/index.js
portal/server/routes/dashboard.js
portal/server/routes/login.js
portal/templates/dashboard/_macros/dashboard-filters-action-bar.njk

- Remove a single facility filter via filters panel, panel form, or main container 'selected filters' list.
- Remove all facility filters.
- Add remove filter endpoints to facility UI routes.
- Create `removeSessionFilter` function to use in both deals and facilities when "remove a filter" endpoint is called. Sanitise any `req.params` that have string booleans (received from Nunjucks)
- Move `selectedHasBeenIssuedFilters` and text/value mapping into facilities directory.
- Create `generateSelectedFiltersObjectWithMappedValues` so that a selected filter object will display the intended text value, but a different value to be sent to API. E.g, `hasBeenIssued` with `true` boolean, will have `Issued` text/value displayed, but the href/checkbox value will be `true`
- Without this, any filters …

DTFS2-4615 - ability to remove dashboard facility filters

---

e2e-tests/portal/cypress/integration/journeys/maker/clone-deal/clone-deal.spec.js
portal-api/api-tests/v1/deals/deal-clone.api-test.js
portal-api/src/v1/controllers/deal-clone.controller.js

Previously, the `previousStatus` would be retained when cloning a deal. Without this change, you could end up with a Draft deal status, with a previousStatus of e.g Ready for Checker, which should not be the case.

fix/DTFS2-5395 - wipe previousStatus when cloning a BSS/EWCS deal

---

trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.api-test.js
trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js

Without this change, if there are multiple facilities, each facility heading does not go to a new line.

DTFS2-5357 - add line break to each facility in GEF confirmation email

---

trade-finance-manager-ui/server/constants/deals.js
trade-finance-manager-ui/server/controllers/deals/index.test.js

Order by `tfm.dateReceived`, not `submissionDate`.

fix/DTFS2-5417 - TFM all deals default sort order

---

e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-search.spec.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js
trade-finance-manager-api/src/graphql/schemas/index.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dateReceived.api-test.js
trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dateReceived.js
trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.api-test.js
trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.js
trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.js
trade-finance-manager-ui/server/constants/deals.js
trade-finance-manager-ui/server/controllers/deals/index.test.js

- DTFS2-5417: Add `dateReceivedTimestamp` to `deal.tfm`. Required to correctly sort TFM deals in the UI by date received
- DTFS2-5417: Update TFM UI to use `dateReceivedTimestamp` in default sort params sent to API/DB query
- Fix/update TFM GEF facility fee record calculation api tests
- Remove BSS from a `console.error` that would get thrown for a GEF deal

DTFS2-5417 - TFM - add dateReceivedTimestamp, fix Fee Record tests

---

dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-put-tfm.api-test.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js

* multiple duplicate objects added to tfm activities when resubmitting deal from portal -> tfm
* was due to full tfm object being sent to controller -> thinking it was an extra activity to add and adding it
* Added check for duplicate entries by checking label and timestamp
* Added to test

DTFS2-5416 - TFM Bug - comment added multiple times

---

azure-functions/acbs-function/mappings/deal/helpers/get-deal-effective-date.js

* `EWCS/BSS` and `GEF` have different property name, `getCoverStartDate` helper function mitigates this issue.

DTFS2-ACBS-Bug : Cover start date

---

portal/server/api.js

BSS UI api call to Mandatory Criteria was not returning `response.data`. This caused BSS deal creation to break.

fix BSS deal creation error with mandatory criteria API response

---

e2e-tests/portal/cypress/integration/journeys/maker/before-you-start.spec.js
e2e-tests/portal/cypress/integration/pages/beforeYouStart.js
portal/server/routes/start.js
portal/templates/before-you-start/before-you-start.njk

This fixes the criteria not displaying and adds e2e test coverage.
The template relied on `mandatoryCriteria.data` from the API, but it doesn't need the `.data`.

fix BSS Mandatory Criteria not displaying on before-you-start page

---

azure-functions/acbs-function/constants/deal.js
azure-functions/acbs-function/mappings/party/helpers/get-sme-type.js
dtfs-central-api/src/v1/swagger-definitions/portal/gef-exporter.js
e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
e2e-tests/portal/cypress/fixtures/mockExporter.js
e2e-tests/trade-finance-manager/cypress/fixtures/mock-gef-deals.js
gef-ui/server/constants/index.js
gef-ui/server/utils/display-items.js
gef-ui/templates/partials/about-exporter.njk
portal-api/api-tests/v1/gef/validation/exporter.api-test.js
portal-api/src/v1/gef/controllers/validation/exporter.js
portal-api/src/v1/gef/enums.js
trade-finance-manager-api/src/v1/__mocks__/mock-TFM-deal-AIN-submitted.js
trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
utils/mock-data-loader/gef/exporter.js

Instead of mapping e.g "MICRO" to "Micro" in the GEF UI and (near future) data migration, just save the values in the DB as what they are.
Also for ACBS smeType mapping function - added another type because GEF and BSS have different values ("non sme", "not sme"). @abhi-markan

GEF smeType values as real values instead of uppercase values

---

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/deal-page-GEF.spec.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityDates.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityDates.js

* Fixed coverStartDate showing as invalid date by only mapping if is not null, else undefined
* Updated tests and e2e test

DTFS2-5419-TFM Bug - Cover Start Date showing as Invalid date

---

azure-functions/acbs-function/mappings/facility/facility-fee.js

Facility fixed fee record `effectiveDate` was being picked from facility `tfm` object, this approach will not always work especially when the facility cover start date is not same as the submission date.
`getIssueDate` helper function return the correct effective date.

DTFS2-5520 : Facility fee record

---

azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js

Error while creating a **non-GBP** facility loan record, this was due to `exchangeRate` long decimal value.
`toFixed(4)` will round off the trailing digits to 4 decimal point exchange rate.

Facility loan exchange rate

---

azure-functions/acbs-function/acbs-issue-facility/index.js
trade-finance-manager-api/src/v1/controllers/acbs.controller.js

When a facility is issued on the following day since its creation, `getIssueDate` returns the submission date due to the absence of `facilitySnapshot` object.
`facilitySnapshot` object is passed as an argument instead of `facility` object which does not contains all the vital properties.
Documentation update

DTFS2-5528 : ACBS Facility issue

---

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-filters.spec.js
e2e-tests/portal/cypress/integration/journeys/reports/review-ukef-decision.spec.js
e2e-tests/portal/cypress/integration/pages/dashboardFacilities.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-EC-11-false.spec.js
portal/server/controllers/dashboard/facilities/index.js
portal/server/controllers/dashboard/facilities/index.test.js
portal/server/controllers/dashboard/reports.controller.js
portal/server/controllers/dashboard/reports.test.js
portal/server/helpers/equalArrays.helper.js
portal/server/helpers/equalArrays.test.js
portal/server/helpers/isChecker.helper.js
portal/server/helpers/isChecker.test.js
portal/templates/dashboard/_macros/dashboard-facilities-table.njk
portal/templates/dashboard/facilities.njk
portal/templates/reports/_macros/ukefDecision.macro.njk
portal/templates/reports/conditional-decision.njk
portal/templates/reports/unconditional-decision.njk
portal/templates/reports/unissued-facilities.njk

- Reports page: the rows in the table for GEF/BSS deals/facilities should be `readOnly` for Checkers. Makers should be able to click on them
- Facilities tab: the rows in the table for GEF/BSS facilities should be `readOnly` for checkers. Makers should be able to click on them as usual.

ReadOnly links for deals and facilities when a checker is logged in

---

azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js
azure-functions/acbs-function/mappings/facility/helpers/get-fee-type.js
azure-functions/acbs-function/mappings/facility/helpers/get-year-basis.js

`BSS/EWCS` fee frequency and type were not being returned due to absence of appropriate properties.
Evaluation of `premiumFrequency` and `premiumType` property in respective helper functions.
Year basis defaults to 365, though this branch will never be reached provided only `360` and `365` can be selected by the user during facility creation process.

DTFS2-5546 : BSS/EWCS Compatibility

---

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-facilities/dashboard-facilities-name-link.spec.js
portal/templates/dashboard/_macros/dashboard-facilities-table.njk

* on portal facility table, name link is not there if facility name is not set
* added condition to check if name exists, else defaults to 'Not entered'
* Added e2e test

DTFS2-5465- Portal Bug - Name link not present if no name

---

trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.api-test.js
trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js

Previously was only rendering `coverStartDate`.

DTFS2-5453 - add facility coverEndDate to TFM - GEF confirmation email

---

dtfs-central-api/src/v1/controllers/portal/deal/add-deal-comment.controller.js
dtfs-central-api/src/v1/controllers/portal/deal/delete-deal.controller.js
dtfs-central-api/src/v1/controllers/portal/deal/get-deal.controller.js
dtfs-central-api/src/v1/controllers/portal/deal/update-deal-status.controller.js
dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/get-facilities.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/get-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-deal/add-underwriter-comment-gef.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-deal/get-gef-deal.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-deal/put-gef-deal.status.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-deal/update-deal.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/create-gef-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/get-facilities.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/update-facility.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-delete-deal.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deal.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-submit-deal.controller.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facility.controller.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-update-facility.controller.js
dtfs-central-api/src/v1/controllers/tfm/users/tfm-users.controller.js
dtfs-central-api/src/v1/controllers/user/get-user.controller.js

- added a validation for `req.params.id` properties in central-api to check whether an `_id` is a valid Object Id. If it's not, then the server crashes because it tries to query the DB with an invalid _id

Validate the `req.params._id` and `_id` property to ensure it's a valid ObjectId

---

trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.api-test.js
trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-email-variables.js

This fixes an email confirmation not sending.
One of the email variables - `dealName`, uses `additionalRefName` which is an optional field. If this field is not provided, the email does not get sent because it's missing. Fixed by adding a default value of '-'.

DTFS2-5452 - DTFS2-5387 - fix TFM GEF confirmation email not sending

---

trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js
trade-finance-manager-api/graphql-query-tests/graphql-authentication.api-test.js
trade-finance-manager-api/src/v1/__mocks__/mock-deal.js
trade-finance-manager-api/src/v1/__mocks__/mock-facilities.js
trade-finance-manager-api/src/v1/controllers/tasks.api-test.js

- make sure that the failing TFM tests do not have hard coded deal ids. API endpoints are mocked in the tests, any deal/facility queries must match a mock ID.
- move "TFM tasks should unlock" API tests into one test This was causing an issue where the first test would update the mock tasks so the proceeding email test would fail.

fix TFM API tests

---

e2e-tests/gef/cypress/integration/exporter-correspondence-address.spec.js
e2e-tests/gef/cypress/integration/pages/exporters-address.js
gef-ui/server/controllers/application-details/index.js
gef-ui/server/controllers/companies-house/index.js
gef-ui/server/controllers/companies-house/index.test.js
gef-ui/server/controllers/enter-exporters-correspondence-address/index.js
gef-ui/server/utils/display-items.js

* If select no for correspondence address, then can never be changed even on cloning deal
* if save and return on correspondence address, then it added United Kingdom
* set correspondenceAddress to null once entering company house number
* changed add html link to registered address if correspondenceAddress is not set
* only set country to United kingdom if 1st line and postcode set

DTFS2-5532 - GEF Bug - Keep correspondence address visible

---

gef-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
gef-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
portal/server/nunjucks-configuration/filter-dashIfEmpty.js
portal/server/nunjucks-configuration/filter-dashIfEmpty.test.js
trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk

Upon an application of a plugin or a function which will return `NaN` as an output `dashIfEmpty` plugin considers it as a valid text thus prevents it from displaying `-`.
* Filter function has been updated to consider `NaN` as an empty value.
* Jest tests cases updates.

DTFS2 : Dash if empty

---

azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js

Loan maximum liability amount for facility type `Loan` should take into account UKEF cover percentage, ignoring this would lead to loan amount being higher than the facility amount.
`EWCS` formula has been updated to reflect this requirement.

DTFS2-5630 : Loan disbursement amount

---

.github/workflows/staging_deploy.yml

Due to lack of privileges to Azure enterprise applications, Service principal cannot be listed or created to update `AZURE_DIGITAL_STAGING`. This has been changed to `AZURE_DIGITAL_TEST`.

DTFS2-5637 : Credentials

---

e2e-tests/gef/cypress/integration/unissued-facility-to-issued-cover-start-date.spec.js
gef-ui/server/controllers/unissued-facilities/index.test.js
gef-ui/server/controllers/unissued-facilities/validation.js
gef-ui/server/controllers/unissued-facilities/validation.test.js

Upon facility issuance, if the facility cover start date was previously saved but not submitted an error message is thrown stating **cover start date cannot precede issue date** despite the fact that the cover start date is set to the issuance date.
This was due to cover start date selection was being ignored.
* `shouldCoverStartOnSubmission` is added to compound conditions.
* `coverStartDate` property in the return object returns issue date if `shouldCoverStartOnSubmission` is true otherwise user defined cover start date.
* Added Jest unit test.
* E2E test introducted.

DTFS2-5710 : Cover start date validation

---

reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
reference-data-proxy/src/v1/controllers/estore/eStoreApi.ts

- added a check in place to prevent `dealIdentifiers` that are used in tests from triggering eStore calls
- added a flag to identify eStore users

fix: prevent test deals from reaching eStore. + updated the notifications email

---

azure-functions/acbs-function/constants/facility.js
azure-functions/acbs-function/mappings/facility/facility-master.js
azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js

Facility master and loan records have `productTypeId` field which specifies facility product type.
Upon a contingent facility record creation, it was being set to cash due to code `280` set for contingent facility type.
* Contingent ACBS code updated to `281`.
* `getProductTypeId` helper function will return `280` for contingent facility upon master record creation for a GEF deal and `281` on facility loan creation.
* Default return set to `280`

DTFS2-5498 : Facility product code

---

utils/mock-data-loader/bss/deals/1.js
utils/mock-data-loader/bss/deals/10.js
utils/mock-data-loader/bss/deals/11.js
utils/mock-data-loader/bss/deals/2.js
utils/mock-data-loader/bss/deals/3.js
utils/mock-data-loader/bss/deals/4.js
utils/mock-data-loader/bss/deals/5.js
utils/mock-data-loader/bss/deals/6.js
utils/mock-data-loader/bss/deals/7.js
utils/mock-data-loader/bss/deals/8.js
utils/mock-data-loader/bss/deals/9.js

* Mock data loader crashed reference data proxy when submitting BSS deals
* added eligibility version to criteria for BSS deals in mock data loader

Bug - BSS - mock data loader eligibility 

---

portal-api/src/v1/controllers/reports/unissued-facilities.controller.js

- prevent `Abandoned` deals from showing on Unissued facilities report

fix: prevent `Abandoned` deals from showing on unissued facilities report

---

e2e-tests/trade-finance-manager/cypress.json
e2e-tests/trade-finance-manager/cypress/fixtures/deal-MIA.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/change-facility-risk-profile.spec.js
e2e-tests/trade-finance-manager/cypress/integration/pages/underwriting/pricingAndRiskPage.js
trade-finance-manager-ui/server/graphql/queries/deal-query.js
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk

* pricing and risk page had '-' by interest margin and guarantee value
* added guaranteeFeePayableToUkef to graphql query
* changed from '-' to value for relevant fields
* updated e2e test

fix(DTFS2-5817): TFM - Missing price risk info

---

.gitignore

`**/actionsheets/*` directory has been added to `.gitignore` to avoid to tracking Action Sheets and accidentally adding them to the repo due to data sensitivity.

.gitignore - Added `actionsheets` directory

---

azure-functions/acbs-function/helpers/date.js
trade-finance-manager-api/src/utils/date.js
trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.js

Date specified by the bank is converted into `UTC` by moment if date is set to `00:0:00 +01:00` then UTC conversion can take the converted date back a day. This PR aims to mitigate this issue.
* Removal of `utc()` calls.
* Date in string or EPOCH provided will be treated as it is.

DTFS2-5870 : Moment `utc()` calls removed.

---

azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js

`disbursementAmount` is not present as expected and due to datatype being `undefined` replace function is being executed which only exists for string datatype.
* Property null check
* Type of `string` comparison

DTFS2-5582 : disbursementAmount undefined - FLR

---

azure-functions/acbs-function/mappings/facility/facility-fee.js
azure-functions/acbs-function/mappings/facility/helpers/get-income-class-code.js

Facility fixed fee record / premium schedule has `incomeClassCode` field which was being set as per the deal type due to lack of clarity in the user story. Due to deal type for BSS and EWCS and set in unison i.e. `BSS/EWCS` rather individually this has caused the helper function to reset to the default case which was set to BSS, thus supplying `BPM` for EWCS facility.
This bug has caused issue with three production EWCS deals which have been set as `BPM` instead of `EPM` hence causing issues with reconciliation with CODA.
* Facility type evaluation for setting the correct income class code.
* Improved function documentation.

fix(DTFS2-5930): Facility fixed fee income class code

---

.github/workflows/staging_deploy.yml

`Staging` environment was consuming GH secret as per an old naming convention.
This has been updated to reflect an updated naming convention.
`AZURE_DIGITAL_TEST ` -> `AZURE_DIGITAL_STAGING `

fix(Deployment) : Staging GitHub secret name update

---

azure-functions/acbs-function/activity-create-code-value-transaction/index.js
azure-functions/acbs-function/activity-create-deal-guarantee/index.js
azure-functions/acbs-function/activity-create-deal-investor/index.js
azure-functions/acbs-function/activity-create-deal/index.js
azure-functions/acbs-function/activity-create-facility-covenant/index.js
azure-functions/acbs-function/activity-create-facility-fee/index.js
azure-functions/acbs-function/activity-create-facility-guarantee/index.js
azure-functions/acbs-function/activity-create-facility-investor/index.js
azure-functions/acbs-function/activity-create-facility-loan/index.js
azure-functions/acbs-function/activity-create-facility-master/index.js
azure-functions/acbs-function/activity-create-party/index.js

Mulesoft compatible payload has never been stored anywhere in the system. Payload storage is providing pivotal for quick debugging and manual intervention thus saving hours when necessary.
Return responses are saving in Azure storage, keeping this in mind following have been added to return statements across various Azure Durable Activity Functions (DAF).
* Inclusion of `status` in the return statement.
* Inclusion of `dataSent` in the return statement.

fix(ACBS) : Inclusion of payload and status in logs

---

.gitignore

##Introduction
`json` directory used for storing raw JSON files for data migration.
This has now been added to `.gitignore` to avoid accidental inclusion of high PII files.

fix(DTFS2-gitignore) : Added json directory

---

azure-functions/acbs-function/constants/deal.js
azure-functions/acbs-function/mappings/deal/deal-investor.js

Due to latest patch applied to ACBS `dev` and `QA` environments deal creation has been unsuccessful.
A remedial action requires deal investor expiry date to be updated from `9999-99-99` to `2050-12-31`.
* Updated constant - Deal investor record's expiryDate payload property.

fix(DTFS2-5964) : Deal expiry date set to 2050-12-31

---

dtfs-central-api/api-tests/v1/tfm/deal/tfm-deals-get-query-field.api-test.js
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals-date-helpers.js

When querying `v1/tfm/deals` with below sample body, TFM API returns empty data set.
This was due to `lastUpdated` field was missed out from array of acceptable fields.
```{
"queryParams": {
"byField": [
{
"name": "tfm.lastUpdated",
"value": "02-08-2022"
}
]
}
}
```
* `tfm.lastUpdated` has been added to `TIMESTAMP_FIELDS`.
* API Unit test case.
* Lint fix.

feat(DTFS2-5965) : TFM API  field support

---

e2e-tests/portal/cypress/fixtures/deal-dashboard-data.js
e2e-tests/portal/cypress/fixtures/deal.js
e2e-tests/portal/cypress/integration/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-min-submission-date/deal.js
e2e-tests/portal/cypress/integration/journeys/checker/currency-conversion-date/deal-first-submission.js
e2e-tests/portal/cypress/integration/journeys/checker/issued-specs-new/MIA-deal-with-unissued-facilities.js
e2e-tests/portal/cypress/integration/journeys/checker/issued-specs-new/submit-MIN-deal-with-issued-facility/MIN-deal-accepted-status-with-unissued-facilities.js
e2e-tests/portal/cypress/integration/journeys/checker/return-a-deal-to-maker/dealWithSomeIssuedFacilitiesReadyForReview.js
e2e-tests/portal/cypress/integration/journeys/checker/submit-a-deal/test-data/template.json
e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/dealWithFirstPageComplete.json
e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/dealWithSecondPageComplete.json
e2e-tests/portal/cypress/integration/journeys/maker/fixtures/dealFullyCompleted.js
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealThatJustNeedsConversionDate.json
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealWithIncompleteAbout.json
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealWithIncompleteBonds.json
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealWithIncompleteEligibility.json
e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review/dealWithIncompleteLoans.json
e2e-tests/portal/cypress/integration/journeys/maker/submit-issued-facilities-for-review/dealWithNotStartedFacilityStatuses.js
e2e-tests/portal/cypress/integration/journeys/maker/submit-issued-facilities-for-review/submit-MIN-deal-with-issued-facilities-for-review-without-cover-start-dates/MINDealWithNotStartedFacilityStatuses.js
e2e-tests/portal/cypress/integration/journeys/number-generator/test-data/MIA-deal-ready-to-submit-with-already-submitted-issued-facilities.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/test-data/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-non-gbp-facilities/test-data/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/AIN-deal/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIA-deal/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal-unissued-facilities/dealThatJustNeedsDates.json
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/test-data/MIN-deal/dealThatJustNeedsDates.json
utils/mock-data-loader/bss/eligibilityCriteria.js

* portal e2e tests were missing eligibility criteria versions which crashed tfm-api
* Added versions to all required e2e deal files

fix(DTFS2-5968): Added eligibility criteria versions to e2e tests for portal

---

e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/portal/cypress/integration/journeys/maker/facilities/maker-cannot-edit-issued-facilities-after-submit-to-ukef/deal-multiple-facility-types-ready-to-submit-to-ukef.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-proceed.spec.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapUkefExposure.js

* TFM facility page showed maximum facility  exposure timestamp as January 1970 as value was mapped using date-fns in epoch seconds rather than milliseconds
* converted from date-fns timestamp to native epoch timestamp with ms
* Linked to amendment submission date
* added to existing e2e tests

fix(DTFS2-5966): Amendment facility time value fix

---

azure-functions/acbs-function/api.js

Azure Functions App do not support optional chaining `?` and nullish coalescing`??`.
* These have been removed and replaced with `ternary operator` to mitigate compatibility issue.

fix(DTFS2-ACBS-Bugs): Backward compatible script

---

e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js
trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentEffectiveDate.validate.js

* Automatic amendments could only have effective date today or in the future
* Removed validation for effective date not being in the past
* Added to automatic amendment e2e test with past effective date

fix(DTFS2-6009): Remove effective date validation for automatic amendments

---

azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js

Amid recent ACBS facility master records creation failure, a two decimal point formatting is required.
Despite this has never been an issue before (Deals submitted prior to 24/08/2022) but nevertheless a back-end level decimal point formatting is a necessity. 
* Introduction of `decimalPoint` function responsible for trailing two decimal point formatting.
* Default value set to `0`.

fix(DTFS2-6013): Two decimal point format - Facility Records

---

utils/data-migration/.gitignore

Data migration source directories contain sensitive information which should not be added to any VCS.
* Added `tfm/amendments` and `tfm/actionsheets` to `.gitignore`.

chore(git-ignore): Added data migration directories

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
e2e-tests/trade-finance-manager/cypress/integration/pages/caseDealPage.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.api-test.js
trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js

* Exposure values for BSS facilities were rounded to the nearest number so decimal places were always 00
* Removed split which cut off decimal places in mapping function for BSS
* Added to tests

fix(DTFS2-5970): BSS exposure rounded off

---

azure-functions/acbs-function/acbs-amend-facility/index.js

DAF `activity-get-facility-master` responsible for fetching the latest facility master record (FMR) alongside with an `eTag` should only be invoked *twice* when facility cover end date is also being amended.
Frivolously execution is expensive on resources.
* Execution only when `coverEndDate` is also set in the amendments payload.

fix(ACBS-Bugs): DAF Execution when obligatory

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/test-data/dealReadyToSubmit.js
e2e-tests/trade-finance-manager/cypress/integration/pages/caseDealPage.js
trade-finance-manager-api/src/constants/tasks.js
trade-finance-manager-api/src/v1/controllers/deal.tasks.api-test.js
trade-finance-manager-api/src/v1/controllers/deal.tasks.js

* Match or create the parties in this deal task was only conditionally showing for BSS
* submit-to-tfm e2e facilities test failing
* Added check for BSS and to add parties task if either buyer or exporter URN is blank
* Added more api-tests to check all conditions
* Changed submit-to-tfm e2e facilities test to calculate exposure from column value

fix(DTFS2-5829): Match parties task non-conditional

---

utils/data-migration/.gitignore

`utils` directory have various I/O scripts which could produce sensitive information.
This data should never make it to any VCS, in order to prevent such scenarios following paths have been added to utils `.gitignore`.
* exports/
* actionsheets/
* json/
* tfm/amendments

fix(DTFS2-gitignore): Added sensitive directories

---

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js

Migrated deals especially `BSS/EWCS` have various criterions which do not exists in pre-defined ECs.
Upon accessing a void criterion GQL resolver does not gets the expected data thus returning `null` data back to `TFM UI`.
* Criterion `id` existence check in `versionContentStrings` (pre-defined ECs)

fix: EC - Criterion existence check

---

trade-finance-manager-api/src/v1/content-strings/index.js

Eligibility criteria for migrated deals especially `BSS/EWCS` predominantly work around EC version `1`.
* Introduction of version `1` for `BSS/EWCS` deals.
* All `25` criterions have been added.

fix(EC): Added EC Criterions version 1

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
trade-finance-manager-api/src/graphql/helpers/facilityValueFormatted.helper.api-test.js
trade-finance-manager-api/src/graphql/helpers/facilityValueFormatted.helper.js
trade-finance-manager-api/src/graphql/resolvers/query-facilities.js

* GEF facilities are displayed without decimal places on TFM all facilities page
* Amendment values were showing without 2 decimal places if .00
* Added helper to return number as 2 decimal places if is a number and is not already 2 decimal place
* (BSS has string formatted to 2 decimal places so is untouched)

fix(DTFS2-5967): TFM facilities decimal places

---

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js
trade-finance-manager-api/src/constants/tasks-amendment.constant.js
trade-finance-manager-api/src/v1/content-strings/index.js

One of the manual amendments task titled as `Complete an adverse history check` has been decided to now be allocated to `Underwriter` team instead of `Underwrite manager`.
* Teams has been changed to `UNDERWRITER`.
* E2E have been updated.

fix(DTFS2-6025): Group 2 task moved from `UW manager` to `UW`

---

e2e-tests/portal/cypress/integration/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js
e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js
portal-api/api-tests/v1/bonds/bond-change-cover-start-date-validation.api-test.js
portal-api/api-tests/v1/bonds/bond-issue-facility-validation.api-test.js
portal-api/api-tests/v1/loan/loan-change-cover-start-date-validation.api-test.js
portal-api/api-tests/v1/loan/loan-issue-facility-validation.api-test.js
portal-api/api-tests/v1/validation/cover-end-date.api-test.js
portal-api/package-lock.json
portal-api/package.json
portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js
portal-api/src/v1/validation/fields/cover-end-date.js
portal-api/src/v1/validation/fields/issue-facility/requested-cover-start-date.js
portal-api/src/v1/validation/loan-rules/facility-stage-unconditional/requested-cover-start-date.js

* BSS allowed for the year to be 2 numbers (eg 22 instead of 2022) which caused some functions to assume the year 0022
* Added validation using joi to check length is 4 and only digits entered for the number

fix(DTFS2-6024): BSS date validation

---

trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentRequestDate.validate.js
trade-finance-manager-ui/server/controllers/case/amendments/validation/amendmentRequestDateValidation.test.js

* Only run isBefore or isAfter check on amendment request date if year is in correct format

fix(DTFS2-6037): Year format remove error message

---

trade-finance-manager-api/src/graphql/resolvers/query-deal.js
trade-finance-manager-ui/server/api.js

Upon an unsuccessful resolution of a GQL in `TFM-API` no `deal` object is returned.
TFM-UI crashes when accessing void property.
* Exceptional handling TFM-API GQL resolver.
* Optional chaining of `response?.data?.deal`

fix: GQL resolver exceptional handling and optional chaining

---

trade-finance-manager-ui/templates/case/parties/_macros/parties-indemnifier-area.njk

When an `indemnifier` is present with its correspondence address and country and when logged in as a non-editable user address overlaps with the heading on the left this was due to a child DOM element with class `govuk-grid-column-one-half` exists inside a parent DOM element with same class, thus reducing the width to `50%`.
* Removal of condition and `<div>` object as they do not serve any meaningful purpose.

fix(DTFS2-6035): TFM UI - Indemnifier address overlap

---

azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js

When cover start date and end date is null due to facility not being issued, exposure period helper function returns `NaN` for `BSS/EWCS` deals.
* Returns `exposure` when both month duration and month off set are void.

fix: ACBS Exposure period - Null cover start and end date

---

e2e-tests/gef/cypress.json
e2e-tests/gef/cypress/fixtures/dateConstants.js
e2e-tests/gef/cypress/integration/about-facility.spec.js
gef-ui/server/controllers/about-facility/index.js
gef-ui/server/controllers/about-facility/index.test.js

* If select shouldCoverStartOnSubmission and go back to change coverEndDate, could choose coverEndDate on the same day and could proceed if before
* Added validation if shouldCoverStartOnSubmission  then to temporarily create a coverStartDate and compare to coverEndDate
* Added tests

fix(DTFS2-6036): shouldCoverStartOnSubmission validation

---

dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm/submit-MIN-with-unissued-facilities-and-resubmit-issued-facilities-updates-facilities-in-tfm.spec.js
e2e-tests/trade-finance-manager/cypress/integration/pages/facilitiesPage.js
e2e-tests/trade-finance-manager/cypress/integration/pages/facilityPage.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.api-test.js
trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.js

* MIN facilities do not show up on all facilities tab
* MIN tfm-deal dealSnapshot._id converted to string instead of ObjectId
* returned dealUpdate from `updatePortalDealFromMIAtoMIN` as compared to returning full deal 
* removed full update body from update in `updateDealSnapshot` 
* Added extra tests

fix(DTFS2-6056): All facilities - fix dealId conversion to string

---

trade-finance-manager-api/graphql-query-tests/query-facilities.api-test.js
trade-finance-manager-api/src/graphql/resolvers/query-facilities.js

* If ukefFacilityId is null, tfm-ui crashes as graphql replaces facility with null on all facilities page mapping
* Replaced null with '-' on query-facilities resolver
* Added test

fix(DTFS2-6065): Null ukefFacilityId fix

---

dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js

* Some dealSnapshots on migrated deals still have dealSnapshot._id as a string
* Changed $lookup to use _id instead of dealSnapshot._id

fix(DTFS2-6056): show all MIN facilities - change to _id

---

.github/workflows/README.md
.github/workflows/deploy.sh
.github/workflows/pr_api_tests.yml
.github/workflows/pr_e2e_tests.yml
.github/workflows/pr_integration_tests.yml
.github/workflows/pr_no_tests.yml
.github/workflows/scan_codeql_analysis.yml

Since `main-amendment` has been merged into `main`, any reference to same in CICD is now frivolous.
* GHA branches now only refers to `main`.
* Deployment shell script deployment only on `main`
* Updated README.md

fix: Removed `main-amendments` from GHA

---

utils/reporting/tfm/.eslintignore
utils/reporting/tfm/.eslintrc.js
utils/reporting/tfm/rad-reporting.js

Due to the advent of RAD reporting, a small script has been written to generate a bespoke `RAD` report for `MIA/MIN` deals only.
Below script relies on `tfm-deals` collection's filtered data.
* Export data from `tfm-deals` with `$or: { [ {'dealSnapshot.dealType: 'Manual Inclusion Application'},  {'dealSnapshot.dealType: 'Manual Inclusion Notice'} ] }`
* Once exported set `deals` with exported data.
* Run below script, which will output data in tabular format.
* Linting - Addition of `.eslint*` files

feat(Reporting): RAD Reporting

---

azure-functions/acbs-function/acbs-amend-facility/index.js

#Introduction
Previously only `Bond` facility type were allowed to be amended (FLR).
After a recent `CODA` testing, it has been identified that the `GEF` facility's  ML should be amended alongside  with it's FMR.
`EW` facility specification remains the same.
#Resolution
* `Loan` type facilities are excluded from FLR amendment.
* Documentation update.

fix(acbs): GEF facility loan record ML amendment

---

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-non-gbp-facilities/submit-deal-with-non-gbp-facilities.spec.js
e2e-tests/trade-finance-manager/cypress/integration/pages/facilityPage.js
trade-finance-manager-ui/templates/case/facility/_macros/facility_details.component-test.js
trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk

`Exchange Rate` under `Value and Exposure` in TFM have been hard coded to `-`.
Since `exchangeRate` property is being set with the `midRate` from the Mulesoft API and also being set as part of data-migration, it should be made available in TFM.
After conformation, template have been updated.
* `tfm.exchnageRate` property being read in the NJK template.
* Introduced `facilityExchangeRate` for all the E2E tests.
* Updated E2E tests for `non-GBP` facilities submission.
* Updated component test.

feat(DTFS2-6098): Show exchange rate in TFM

---

azure-functions/acbs-function/mappings/facility/facility-loan-amend.js
azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js

Facility amendment could consists of both value *increment* or value *decrement*.
Value increment works as expected, however decrement require facility records amendment to be swapped.
In a standard value increment records are amended in following sequence:
1. FMR
2. FLR
However, in case of decrement records are amended in reverse:
1. FLR
2. FMR
1. Execution sequence are swapped upon operation type.
2. GEF facility amendment bug resolution with regards to `10%` of the amendment value and condition update for payload construction.
1. Documentation update

fix(DTFS2-6023): Facility amendment decrement

---

trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacilities.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapFacility.js

Deals with empty facilities crash GQL reducers when `map` method is being applied.
* Void facility check

fix(DTFS2-6116): Void facility validations

---

e2e-tests/e2e-fixtures/tfm-users.fixture.js
trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk

* PIM were not able to access task as were in multiple groups
* fixed the order in nunjucks for checking if in group
* User group is array and task.team.id is a string
* Added team to mock user PIM group

fix(DTFS-6128): Users with multiple teams not being able to access tasks

---

trade-finance-manager-api/src/v1/controllers/acbs.controller.js

Upon making an ACBS request output is stored in `durable-functions-log` collection which then is handled by `acbs.controller` to be saved in `tfm-*` collection.
When an amendment request is submitted to ACBS, final output from DOF is returned and saved in `durable-functions-log` which is further then fetched and amended to `tfm-facilities` (tfm.acbs.[amendment_id]). 
Above property was being created, however with an empty object due to `undefined` property de-construction.
* Property names correction.

fix(DTFS2-6139): Property name correction whilst de-constructing

---

portal/server/helpers/constructPayload.js
portal/server/helpers/constructPayload.test.js
portal/server/helpers/index.js
portal/server/routes/user/profile.js

A vulnerability has been raised, where a non-privileged or a lower privileged user can amend the `<form>` DOM element on the change password by inserting the `role` attributes DOM elements.
Upon submission whole `req.body` is submitted to the controller thus amending non-targeted the user profile attributes.
* Introduction of `constructPayload` method, which is responsible for creating payload with indented properties only with an optional `CSRF` property inclusion.
* Accompanied with an unit test.

fix(DTFS2-6143): Payload construction

---

portal/server/routes/admin/users.js
portal/server/routes/user/profile.js

* As pointed out `red.body` was still being passed instead of `payload`, thus not patching the vulnerability.
* Other admin endpoints were still passing the whole `req.body` to the update endpoint.
* `payload` being passed to the API endpoint.
* Admin user edit POST endpoint now calls `constructPayload` before user update endpoint invocation.
* Admin user password change POST endpoint calls `constructPayload` before user update endpoint invocation.
* Add vulnerability E2E tests.
* Add a test confirming `constructPayload` method has been called.
* Typo fix

fix(DTFS2-6143): payload being passed instead of req.body

---

reference-data-proxy/src/v1/controllers/email.controller.ts

All outgoing emails send via `Gov Notify` did not have any `reference` as it was set to default `null`.
An unique reference number always aides in an effective debugging.
* Created unique reference number based on `templateId` and now `EPOCH`.

fix(DTFS2-6161): Added unique reference to all outgoing email addresses

---

gef-ui/package-lock.json
portal/package-lock.json
trade-finance-manager-ui/package-lock.json

`npm audit` flags `loader-utils` to be a critical vulnerability for version `2.0.2`.
`npm audit fix --legacy-peer-deps` has been executed on following microservies:
* Portal
* GEF UI
* TFM UI

fix(DTFS2-6157): Loader utils upgraded to 2.0.4

---

utils/data-migration/helpers/format.js
utils/reporting/tfm/rad-reporting.js
utils/reporting/tfm/tfm-reporting.js

A bespoke TFM report is generated upon a request, in order for a swift report generation a simple node script has been written based on @IgnatG initial work.
This script reads the data from `tfm-deals` collection and construct the rows as an `array` which then is passed over to `generateReport` function responsible for appending processed data array at the bottom of the bespoke columns. Once amalgamated and converted into CSV data is then passed to file write method.

feat(tfm-reporting): TFM reporting

---

trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenor.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenor.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenorDate.api-test.js
trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapTenorDate.js

TFM UI seems to have been missing `tenor` for GEF deals, since this is being resolved by a GQL resolver methods transitively calling helper functions. Both `mapTenor` and `mapTenorDate` methods were not cross-product compliant thus returning `-` for GEF.
* Updated mapping function to accommodate both `un-issued` and `issued` facilities across all the products.
* Updated unit test cases.
* Improved documentation.

feat(DTFS2-6236): Return tenor across products for all facilities

---

azure-functions/acbs-function/mappings/facility/facility-master.js

Due to a know tech-debt issue, on certain occasion `facility.currency.id` does not exists, due to which perils are high when creating records in ACBS especially during facility level records.
* If the `currency.id` is absent then currency will be defaulted to `GBP`.

fix(DTFS2-6239): Facility level default currency

---

trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapDealSnapshot.js
trade-finance-manager-api/src/v1/mappings/map-deal.js
trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js

Since Non-delegated banks do not have EC, this needs to be reflected across GQL mapping.
* Conditional branching.

feat(DTFS2-6213): NDB EC mapping

---

e2e-tests/trade-finance-manager/cypress/fixtures/deal-AIN.js

Month ago Abhi changed Tenor check from 25 months to 26 - https://github.com/UK-Export-Finance/dtfs2/pull/1245 
After a month issue appeared again, this change should/might be permanent fix.

2e2 Tenor check fix. One date was static, while other dynamic

---

reverse-proxy/Dockerfile

`nginx` Dockerimage has a new upgrade with lesser known vulnerabilities.
* Upgraded `reverse-proxy` nginx image to `nginx:1.23`.

chore(nginx): Dockerfile image upgrade to 1.23

---

azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-expiry-date.js
azure-functions/acbs-function/mappings/facility/code-value-transaction.js
azure-functions/acbs-function/mappings/facility/facility-covenant.js
azure-functions/acbs-function/mappings/facility/facility-guarantee.js
azure-functions/acbs-function/mappings/facility/facility-investor.js
azure-functions/acbs-function/mappings/facility/facility-loan.js
azure-functions/acbs-function/mappings/facility/facility-master.js
azure-functions/acbs-function/mappings/facility/facility-update.js
azure-functions/acbs-function/mappings/facility/helpers/get-fee-dates.js
azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js
trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.api-test.js
trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.js

An anomaly has been identified between TFM and ACBS, whereby the GCD and GED differs.
This has been identified due to the guarantee dates mis-calculation further consumed by ACBS mapping functions and also due to a partial facility issuance payload.
* Commitment GCD - Removal of additional `3 month` from the calculation.
* Facility issuance - Enhanced payload with additional date fields.

feat(DTFS2-6284): GCD and GED for TCM and ACBS

---

gef-ui/package-lock.json
portal-api/package-lock.json
reference-data-proxy/package-lock.json
trade-finance-manager-api/package-lock.json
trade-finance-manager-ui/package-lock.json

Various micro-services consume `sideway/formula` as a transitive dependency.
A vulnerability has been flagged for the same, `@sideway/formula` contains Regular Expression Denial of Service (ReDoS) Vulnerability - https://github.com/advisories/GHSA-c2jc-4fpr-4vhg.
* Dependency update from `3.0.0` to `3.0.1`.

chore(npm-package-bump): Updated @sideway/formula to 3.0.1

---

trade-finance-manager-ui/server/controllers/case/activity/index.js

TFM UI crashes when `tfm.activities` object does not exist.
Albeit this is an edge case and represent a corrupt deal submission in TFM, TFM UI should not crash.
* Object void check.

fix(no-activities): Prevents TFM crash when no acitivity exist

---

azure-functions/acbs-function/mappings/facility/facility-covenant.js
azure-functions/acbs-function/mappings/facility/facility-fee.js
azure-functions/acbs-function/mappings/facility/facility-investor.js
azure-functions/acbs-function/mappings/facility/facility-loan.js

A known bug produces empty `currency` object, due to which no currency is present and thus causes ACBS payload to fail.
* If object `currency.id` does not exist, then default to `GBP`.

fix(no-currency): Default to `GBP` on void currency

---

azure-functions/acbs-function/Dockerfile
azure-functions/number-generator-function/Dockerfile

Durable functions which runs node version 10 is not compatible with npm `9.5.0`.
* NPM latest version is not installed on durable functions `acbs` and `number-generator`.

fix(dockerfile): Node v10 incompatible with npm 9.5.1

---

portal-api/src/createApp.js

Health check missing for portal-api, since GQL no longer handles wildcard paths.
* Added route for Azure health check before container swap.

fix(portal-api): azure webapp healthcheck

---

reference-data-proxy/src/cronJobs/eStoreCronJobManager.ts

On the dev VMs which run slow there was a race condition that when the mongoDb instance said it was ready another service would start up and query it instantly. Unfortunately this would error as it was not read to accept connections. I've added in a 30 second delay to mongoDb query on startup of the reference data proxy to fix this when running locally.
Long term best fix would be to implement a better healthcheck on the mongoDb container so that the other services do not come up until the mongoDb passes said healthcheck.

Avoid race condition in start up with MongoDb for local dev

---

dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.js
trade-finance-manager-api/src/v1/controllers/feedback-controller.js

The feedback controller on the TFM amendments API was the only endpoint that was vulnerable of saving unwanted form fields from the forms in the frontend so I've moved the object destructuring that already existed to before the DB save call so that unwanted fields are filtering out from the request body.

feat: destructure feedback form on TFM API

---

external-api/src/interfaces/index.ts
external-api/src/interfaces/premiumSchedule.interface.ts
external-api/src/v1/controllers/premium-schedule.controller.ts

The get premium schedule endpoint posted the request body without any sanitization meaning it was vulnerable to having extra fields than what it should accept in request body and sending all of those on.
Introduce new interface to cast the request body to so that extra fields aren't passed through.

Fix(DTFS2): Add interface to premium Schedule

---

infrastructure/arm_templates/storage-private-endpoint/parameters.json
infrastructure/arm_templates/storage-private-endpoint/template.json
infrastructure/arm_templates/storage/parameters.json
infrastructure/arm_templates/storage/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/storage.bicep
infrastructure/resource_group_level/modules/vnet.bicep

* produce a complete new deployment environment (`feature`) mirroring the current ones.
* be in a position to take over the extant environments.
Note that there have been some manual changes to the environments. This work also functions as an audit of the current infrastructure.
This card covers wiring up the storage only. Note that there will be some tidying / refactoring when all the components are in place, (e.g. commonise tags, consider parameter sets), but the code should be of reasonable quality and clear.
This code wires up the storage account and its components.

feat(fn-417): storage

---

infrastructure/arm_templates/cosmosdb/errors.json
infrastructure/arm_templates/cosmosdb/parameters.json
infrastructure/arm_templates/cosmosdb/private-endpoint/parameters.json
infrastructure/arm_templates/cosmosdb/private-endpoint/template.json
infrastructure/arm_templates/cosmosdb/serverless_example/parameters.json
infrastructure/arm_templates/cosmosdb/serverless_example/template.json
infrastructure/arm_templates/cosmosdb/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/cosmosdb.bicep
infrastructure/resource_group_level/modules/privatelink-mongo-cosmos-azure-com.bicep

Note that there have been some manual changes to the environments. This work also functions as an audit of the current infrastructure.
This card covers wiring up cosmosdb (MongoDB) only. Note that there will be some tidying / refactoring when all the components are in place, (e.g. commonise tags, consider parameter sets), but the code should be of reasonable quality and clear.
This code wires up cosmosdb and its private link.

feat(fn-416): cosmosdb

---

infrastructure/arm_templates/redis/parameters.json
infrastructure/arm_templates/redis/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/redis.bicep

*   produce a complete new deployment environment (feature) mirroring the current ones.
*   be in a position to take over the extant environments.
Note that there have been some manual changes to the environments. This work also functions as an audit of the current infrastructure.
This card covers wiring up Redis only. Note that there will be some tidying / refactoring when all the components are in place, (e.g. commonise tags, consider parameter sets), but the code should be of reasonable quality and clear.
Note also that this replicates the current setup. Enhancements, including …

feat(fn-418): redis

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/privatelink-file-core-windows-net.bicep
infrastructure/resource_group_level/modules/storage.bicep

This card covers wiring up the A Record generation in the private DNS for the storage private link.
If all is ok, we can apply this to all the private links.
This code adds a private dns zone config, which triggers the CNAME generation and management.
See the resources here: …

feat(FN-573): Configure automatic A Record generation

---

dtfs-central-api/api-tests/v1/tfm/amendments/tfm-amendments-get.api-test.js
dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.js

API tests on main were failing in central API.
Fix one case for invalid amendment APIs and then fix remaining test suites. Majority of the fixes are test file related only.

fix(DTFS2): Fix get amendments related central API tests

---

infrastructure/arm_templates/function-acbs/application-insights/errors.json
infrastructure/arm_templates/function-acbs/application-insights/parameters.json
infrastructure/arm_templates/function-acbs/application-insights/template.json
infrastructure/arm_templates/function-acbs/errors.json
infrastructure/arm_templates/function-acbs/parameters.json
infrastructure/arm_templates/function-acbs/private-endpoint/parameters.json
infrastructure/arm_templates/function-acbs/private-endpoint/template.json
infrastructure/arm_templates/function-acbs/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/function-acbs.bicep
infrastructure/resource_group_level/modules/storage.bicep

- Creating the Azure Function for the ACBS function, wired up to the correct docker image from CI
The code:
- creates the Azure Function
- wired up with dummy environment variables
- with Application Insights
Note:
- that there isn't currently an image to deploy!
- It does not wire up the A …

feat(FN-419): Add ACBS function to Bicep

---

infrastructure/arm_templates/app-service-plan/parameters.json
infrastructure/arm_templates/app-service-plan/template.json
infrastructure/arm_templates/dtfs-central-api/application-insights/parameters.json
infrastructure/arm_templates/dtfs-central-api/application-insights/template.json
infrastructure/arm_templates/dtfs-central-api/errors.json
infrastructure/arm_templates/dtfs-central-api/parameters.json
infrastructure/arm_templates/dtfs-central-api/private-endpoint/parameters.json
infrastructure/arm_templates/dtfs-central-api/private-endpoint/template.json
infrastructure/arm_templates/dtfs-central-api/template.json
infrastructure/arm_templates/log-analytics-workspace/parameters.json
infrastructure/arm_templates/log-analytics-workspace/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/cosmosdb.bicep
infrastructure/resource_group_level/modules/dtfs-central-api.bicep

This card covers 
- adding the backing infrastructure of the dtfs-central-api webapp
The code
- links with application insights
- wires up with dummy environment variables
- creates a private link
- DOES NOT wire up A Records. I'll do those in a batch.
- DOES NOT send in the environment variables from …

feat(FN-422): Add dtfs-central-api webapp

---

infrastructure/resource_group_level/modules/function-acbs.bicep

Note that the Infrastructure is not totally static while this work is underway. We need to cope with changes to it, such as this one which is the reirement of the Mulesoft API.
- removing Mulesoft API secrets / environment variables
- replacing them with APIM secrets
according to:
``` …
```

feat(FN-686): remove Mulesoft config

---

infrastructure/arm_templates/external-api/parameters.json
infrastructure/arm_templates/external-api/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/dtfs-central-api.bicep
infrastructure/resource_group_level/modules/external-api.bicep
infrastructure/resource_group_level/modules/function-acbs.bicep

- Adding the external-api webapp (previously called reference data proxy)
- Adds the external-api webapp in a way that should make it easy to commonise later
- DOESN'T add Application Insights, but I've left the code to do so, but commented out.

feat(FN-421): add external-api webapp to Bicep

---

infrastructure/arm_templates/portal-api/parameters.json
infrastructure/arm_templates/portal-api/template.json
infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/dtfs-central-api.bicep
infrastructure/resource_group_level/modules/portal-api.bicep

* Adding the portal-api webapp
* Portal-api webapp is added and wired up in Bicep
NOTE: Numerous settings are sent via connection string.
NOTE: I wire up the vnet & NAT gateway correctly, which is the case in `staging` and `prod` but not test.

feat(FN-423): portal api to Bicep

---

dtfs-central-api/src/v1/controllers/cron-jobs/cron-jobs.controller.js
dtfs-central-api/src/v1/controllers/durable-functions/durable-functions.controller.js
portal/server/api.js
trade-finance-manager-api/src/v1/api.js

This PR is to fix the [Information exposure through a stack trace](https://github.com/UK-Export-Finance/dtfs2/security/code-scanning?query=is%3Aopen+branch%3Amain+stack+trace++) alerts
Where errors are returned from the api methods, instead of returning them, log them and return an error message instead.

fix(SR-12): Stop exposing full error messages and stack traces

---

e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/amendment-tasks-manual.spec.js

There was some commented out test code from `amendment-tasks-manual.spec.js` in the TFM e2e tests, backed up on this ticket, which we need to re-instate.
The tests in this file make an amendment to a deal, and then go through completing each of the tasks on that amendment.
The commented out code had two sections. The first asserted that when the "Approve or decline the amendment" task had the status "Cannot start yet", that the "Add decision" button on the Underwriting tab should not appear.
And the second section asserted that when that task had the status "To do", that the "Add decision" button should appear.
Having looked in the code, the "Add decision" button does not depend on what tasks have and haven't been completed, only on whether an underwriter manager is logged in. So I've not …

test(DTFS-6210): Recover removed test code

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/dtfs-central-api.bicep
infrastructure/resource_group_level/modules/external-api.bicep
infrastructure/resource_group_level/modules/function-acbs.bicep
infrastructure/resource_group_level/modules/function-number-generator.bicep
infrastructure/resource_group_level/modules/gef-ui.bicep
infrastructure/resource_group_level/modules/portal-api.bicep
infrastructure/resource_group_level/modules/portal-ui.bicep
infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep
infrastructure/resource_group_level/modules/trade-finance-manager-api.bicep
infrastructure/resource_group_level/modules/trade-finance-manager-ui.bicep

* Wiring up A Records for all private links to enable traffic routing
* Adds privateDNSZoneGroups linked to the resources - this triggers the A Record generation.
NOTE: Dev has `reference-data-proxy` as well as `external-api` and a load of `demo` values. I have not attempted to recreate …

feat(FN-685) A record generation

---

azure-functions/acbs-function/package.json
azure-functions/number-generator-function/package.json
dtfs-central-api/package.json
external-api/package.json
gef-ui/package.json
portal-api/package.json
portal/package.json
trade-finance-manager-api/package.json
trade-finance-manager-ui/package.json
utils/data-migration/package.json
utils/mock-data-loader/package.json

@AlexBramhill noticed in #1955 that it was possible to commit a change to a file with a spelling mistake in `utils/data-migration/helpers/package.json`, so the `cspell` linting must not have been working properly.
I investigated this and found that `lint-staged` uses the nearest configuration file for each file that it lints (see [here](https://github.com/okonet/lint-staged#how-to-use-lint-staged-in-a-multi-package-monorepo)) so we needed to add our `cspell` linting step to the `lint-staged` section of every `package.json` file.
I have added our `cspell` linting step to the `lint-staged` section of every `package.json` file.

chore: apply cspell check in lint-staged to all packages

---

cspell.json
gef-ui/server/utils/helpers.js
portal-api/api-tests/v1/gef/application.api-test.js
portal-api/api-tests/v1/gef/clone-gef-deal.api-test.js
portal-api/api-tests/v1/gef/external-api.api-test.js
portal-api/api-tests/v1/gef/facilities.api-test.js
portal-api/src/v1/gef/controllers/externalApi.controller.js
portal-api/src/v1/gef/controllers/facilities.controller.js
portal-api/src/v1/gef/controllers/validation/application.js
portal-api/src/v1/gef/controllers/validation/external.js
portal-api/src/v1/gef/controllers/validation/facilities.js

@abhi-markan suggested renaming `errCode` to `status` in some error messages in https://github.com/UK-Export-Finance/dtfs2/pull/1955#discussion_r1293534151
As per the conversation below: We've kept `errCode` but added a `status` field following existing patterns

fix(sr-8): update error message name

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/cosmosdb.bicep

* Using parameter sets based on the environment to configure some settings
* a parameter set was created, while checking the values against the actual deployments

feat(FN-939):use parameter sets

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/function-acbs.bicep
infrastructure/resource_group_level/modules/function-number-generator.bicep
infrastructure/resource_group_level/modules/privatelink-file-core-windows-net.bicep
infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
infrastructure/resource_group_level/modules/webapps/external-api.bicep
infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
infrastructure/resource_group_level/modules/webapps/portal-api.bicep
infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep

* input of secure parameters, typically from GitHub secrets
* input of other parameter
* multiple params are added, deviating from the normal naming scheme for clarity
* combination of params into the correct inputs for the app services
* NOTE: I have kept the distinction between the …

feat(FN-742): Set values from GitHub

---

portal-api/package-lock.json
portal-api/package.json
portal-api/src/v1/users/routes.js
portal-api/src/v1/users/routes.test.js

See DTFS2-6681.
So we can deploy this fix more quickly, I've made minimal changes in this PR and I will raise a separate ticket for more extensive changes that I think we should make.
- installed `jest-when` as a dev dependency in portal-api
- extracted just `password` and `passwordConfirm` from the request body in portal-api's `resetPasswordWithToken` route when updating the user document
- added 2 simple unit tests for `resetPasswordWithToken` in portal-api's user routes to validate the change I've made

fix(DTFS2-6681): extract reset password payload

---

infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep
infrastructure/resource_group_level/modules/webapps/external-api.bicep
infrastructure/resource_group_level/modules/webapps/gef-ui.bicep
infrastructure/resource_group_level/modules/webapps/portal-api.bicep
infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep

* commonising webapp code and to highlight similarities
* fixing the naming of the webapp references to avoid conflicts
* renamed instances of the child webapp modules.

feat(FN-712):commonise webapps fix

---

trade-finance-manager-api/src/v1/controllers/facility.controller.js
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/case/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/facility-risk-profile/index.js

We need to standardise the TFM API by moving away from having both gql and REST endpoints. We will move the gql endpoints to REST.
Replace the updateFacilities and updateFacilityRiskProfile graphql endpoints with an updateFacility REST endpoint as part of the gql -> rest migration in TFM API.

Feat(DTFS2-6182): replace update facility graphql endpoint with REST endpoint

---

trade-finance-manager-api/src/v1/controllers/deal.controller.js
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/case/activity/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/loss-given-default/index.test.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js

We need to standardise the TFM API by moving away from having both gql and REST endpoints. We will move the gql endpoints to REST.
Replace the updateCreditRating, updateLossGivenDefault, updateProbabilityOfDefault, createActivity graphql endpoints with a single `updateDeal` REST endpoint as part of the gql -> rest migration in TFM API.

Feat(DTFS2-6182): replace update deal graphql endpoints with REST endpoint

---

portal/server/routes/admin/users.js

Currently the page that admins use to edit a user does not display errors if the update fails. Instead it assumes that the update succeeded and redirects the admin to the list of all users (as it does when the update succeeds).
The update can fail if the admin changes the user to have the `read-only` role AND one or more other roles. This is only possible to achieve via the UI in browsers with JavaScript disabled.
Steps to reproduce bug:
1. Disable JavaScript in the browser
2. Log in to Portal UI as the username ‘ADMIN’
3. Go to the ‘Users’ tab
4. Click on username 'BANK1_MAKER1’, taking you to the edit user page
5. Check the ‘Read-only’ box, so that ‘Maker’ and ‘Read-only’ are both checked
6. Click the save button
7. You are redirected to the ‘Users’ tab, but the update has silently …

fix(DTFS2-6679): display errors on the edit user page

---

infrastructure/resource_group_level/modules/webapps/portal-ui.bicep

* removing `DEAL_API_URL`
* `DEAL_API_URL` was removed after checking it isn't in use

feat(FN-805):remove deal api url

---

.github/workflows/test.yml
trade-finance-manager-api/src/v1/controllers/deal.controller.js
trade-finance-manager-api/src/v1/controllers/facility.controller.js
trade-finance-manager-api/src/v1/controllers/party.controller.js
trade-finance-manager-api/src/v1/controllers/tfm.controller.js
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/case/index.js
trade-finance-manager-ui/server/controllers/case/parties/index.js

We need to standardise the TFM API by moving away from having both gql and REST endpoints. We will move the gql endpoints to REST.
Replace the update party graphql endpoint with a REST endpoint as part of the gql -> rest migration in TFM API.

feat(DTFS2-6182): replace update party graphql endpoint with REST endpoint 

---

.github/workflows/test.yml
trade-finance-manager-api/src/constants/regex.js
trade-finance-manager-api/src/v1/controllers/facility.controller.js
trade-finance-manager-api/src/v1/graphql-mappings/helpers/amendment.helpers.js
trade-finance-manager-api/src/v1/graphql-mappings/helpers/formatFacilityValue.helper.api-test.js
trade-finance-manager-api/src/v1/graphql-mappings/helpers/formatFacilityValue.helper.js
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/facilities/index.js
trade-finance-manager-ui/server/controllers/facilities/index.test.js

We need to standardise the TFM API by moving away from having both gql and REST endpoints. We will move the gql endpoints to REST.
Replace the get facilities graphql endpoint with REST endpoint as part of the gql -> rest migration in TFM API.

feat(DTFS2-6182): replace get facilities graphql endpoint with REST endpoint

---

portal/server/utils/csv-utils.js

Cell addresses weren't present on excel files with some inbuilt data from Bing in the cells. While we don't need to support this we need to avoid crashes as it wasn't getting picked up by the try/catch
Only split up the cell address to get column and row if we match the regex of the cell address

Feat(FN-966): handle weird excel data that strips cell address

---

e2e-tests/.eslintrc.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-filter-on-wrong-pagination-page.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-by-exporter-name.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-on-wrong-pagination-page.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-sort.spec.js
e2e-tests/support/random-value-generator.js

@AlexBramhill and I noticed that the `dashboard-deals-filter-on-wrong-pagination-page.spec.js` test in the `portal` e2e tests would randomly fail on PRs that hadn't affected it at all, so we investigated it.
It creates 30 deals with random company names (using `chance.company()` from the `chance` package. It then filters the dashboard by searching by the first company name that was generated, assuming that this should return exactly 1 deal (the first deal).
However, `chance.company()` picks a random company name from a list of roughly 900. That gives ~3% chance that at least one of the other 29 deals have exactly the same company name as the first deal, meaning the test will fail because the dashboard filter will return (at least) 2 deals instead of 1.
I've introduced a new class, …

fix(e2e-tests): seed random company names to prevent 3% chance of collision that causes test failure

---

portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk

The back button was routed to '/utilisation-report-service' instead of '/utilisation-report-upload'
Fix the routing to '/utilisation-report-upload'

fix(FN-966): fix back button on upload page

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/front-door-portal.bicep
infrastructure/resource_group_level/modules/front-door-tfm.bicep
infrastructure/resource_group_level/modules/waf-policies.bicep

* Enabling the `prod` environment to have the WAF rules applied to Portal without the IP restriction
* Create a second set of WAF rules, only on `prod` and apply them to Portal

feat(FN-857): update waf policy application

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/front-door-tfm.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-connection-strings.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-no-connection-strings.bicep

* don't use secret to resolve circular dependency on TFM-UI URL connection string
* we now set the connection strings after the TFM-FD is deployed

feat(FN-927): wire up tfm-ui url

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/function-acbs.bicep

* deploying function-acbs in a disabled state
* adds `enabled` status to `function-acbs` and sets it per-environment

feat(FN-1203): disable function-acbs in non-prod environments

---

trade-finance-manager-api/src/v1/deals/routes.js
trade-finance-manager-api/src/v1/graphql-mappings/filters/filterActivities.api-test.js
trade-finance-manager-api/src/v1/routes.js

In #2149 we changed `PUT /deals/submit` in TFM API to require a valid TFM user token instead of requiring an API key.
This breaks the functionality of submitting deals from Portal to TFM, as portal-api calls this endpoint (and doesn't have a logged in TFM user to authenticate as).
I've reverted the change to `PUT /deals/submit` in TFM API

fix(DTFS2-6182): remove passport from put deals submit

---

e2e-tests/portal/cypress.config.js
e2e-tests/portal/cypress/e2e/journeys/admin/activate-deactivate-user/activate-deactivate-user.spec.js
e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js
e2e-tests/portal/cypress/e2e/journeys/admin/create-user/update-a-user.spec.js
e2e-tests/portal/cypress/e2e/journeys/login/change-password.spec.js
e2e-tests/portal/cypress/e2e/pages/admin/users/createUser.js
e2e-tests/portal/cypress/e2e/pages/admin/users/editUser.js
e2e-tests/portal/cypress/e2e/pages/resetPassword.js
e2e-tests/portal/cypress/support/commands.js
e2e-tests/portal/cypress/support/portal/userSetPassword.js
e2e-tests/portal/db-client.js
package-lock.json
package.json
portal-api/src/v1/users/controller.js
portal-api/src/v1/users/routes.js
portal/templates/admin/user-edit.njk

In Portal UI, the admin create user page has a `"Auto-create a valid password?"` question to which you can select `"Yes"` or `"No"` (in the latter case the admin specifies the user's password). However, if `"Yes"` is selected, the password auto-creation does not work and the user is not created.
We can in fact remove "Auto-create a valid password?" question altogether. Instead:
- The user gets created without a password and cannot login until they set one via the link that gets emailed to them
- We can remove the Auto-create a valid password? : Yes / No component entirely
This ensures that a user must set their own password, and that admins have no way of knowing this.

fix(DTFS2-6678): remove auto-create password for new user as not needed

---

trade-finance-manager-api/api-tests/api.js
trade-finance-manager-api/api-tests/v1/deals/deals-update-lead-underwriter.api-test.js
trade-finance-manager-api/api-tests/v1/tasks/tasks-update-task.api-test.js
trade-finance-manager-api/src/graphql/resolvers/mutation-update-task.js
trade-finance-manager-api/src/v1/controllers/tasks.api-test.js
trade-finance-manager-api/src/v1/controllers/tasks.controller.js
trade-finance-manager-api/src/v1/graphql-mappings/mappings/facilities/mapPremiumSchedule.api-test.js
trade-finance-manager-api/src/v1/graphql-mappings/mappings/facilities/mapTenor.js
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-api/src/v1/tasks/routes.js
trade-finance-manager-api/src/v1/validation/route-validators/route-validators.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/constants/regex.js
trade-finance-manager-ui/server/controllers/case/index.js
trade-finance-manager-ui/server/controllers/case/index.test.js
trade-finance-manager-ui/server/helpers/validateIds.js

Introduction
We want to replace TFM API's update task GraphQL query with a REST endpoint.
Resolution
In TFM API, I've created a new endpoint (PUT /deals/:dealId/tasks/:groupId/:taskId). This has existing dealId validation applied to it, as well as additional basic groupId validation applied.

feat(dtfs2-6716):replace graphql update task in tfm with rest

---

.github/workflows/bicep_workflow_feature.yml

Now we have it ready, we need to deploy infrastructure to `feature` that the ETETF project needs. This is very slightly different from the the dev infrastructure.
* trigger deploys only from `feat/stbr-infra`
* Update GHA to deploy only from `feat/stbr-infra`

feat(FN-715):deploy stbr infra

---

portal/server/routes/middleware/virusScanUpload/index.js

We couldn't disable clamav scanning on feature env as the env variable check was wrong
Fix it to check that it matches on 'true' as env variables are strings

feat(FN-997): add in correct check for clamav scanning being enabled

---

portal/server/routes/login.js
portal/templates/check-your-email.njk

As part of the new 2FA login flow, we need to add a 'Check your email' screen to Portal UI matching [this design](https://www.figma.com/file/L67W3CbcKYmFYqDUhaSG7A/User-admin?type=design&node-id=897-8999&mode=design&t=qRlYdl79ZXiZi09t-0) that will be (but not as part of this ticket) shown to the user after they click login.
Added the screen.

feat(DTFS2-6733): add 'Check your email' screen

---

e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-beneficiary.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/parties/bond-issuer.spec.js
e2e-tests/tfm/cypress/e2e/pages/partiesPage.js
e2e-tests/tfm/cypress/fixtures/constants.js
trade-finance-manager-ui/server/controllers/case/index.js

After TFM UI updates the URN for the bond issuer/beneficiary, it calls `api.updateParty(dealId, deal.parties);` where `deal` is the response from `GET deals/:dealId` from TFM API (see `postTfmFacility` in TFM-UI for this). It does this because when TFM API receives updates a party, it then checks if the deal can be created in ACBS which relies on the parties that require URNs having URNs set and (for BSS/EWCS deals) the bond issuer and beneficiary having URNs set.
However `deal.parties` is always `undefined` on the response from `GET deals/:dealId` from TFM API.
The GraphQL endpoints that we had before DTFS2-6182 meant that no change was made to the deal's parties when we call `api.updateParty(dealId, undefined);` (but the logic to create the deal in ACBS still worked), but the REST …

fix(DTFS2-6746): do not remove parties after updating bond beneficiary or issuer urns

---

portal-api/api-tests/v1/users/users.api-test.js
portal-api/src/crypto/utils.js
portal-api/src/crypto/utils.test.js
portal/server/routes/login.js

When a user logs in with a username and password, we grant them a token lasting 30 minutes to complete the login process (clicking on an email link). We've updated this to 105minutes (35mins x 3) to allow for the token to live as long as to allow for three emails to be sent (and time out) with a bit of leeway.

feat(DTFS2-6756): update token expiry time

---

portal-api/src/crypto/utils.js
portal-api/src/crypto/utils.test.js
portal-api/src/v1/users/login.controller.test.js
trade-finance-manager-api/src/utils/crypto.util.js

Currently, token expiry is non-functional. We are setting the token expiry based on Date.now() which uses milliseconds since epoch. JWTs work with seconds since epoch ([RFC 7519: JSON Web Token (JWT) (rfc-editor.org)](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.6))
This fix removes setting `ias` as it is unneeded. 
I have checked to see what happens when a token is no longer valid in `portal-api`. Portal logs the user out and their session data is deleted.

fix(DTFS2-6759): fix token expiry

---

.env.sample
portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
portal-api/src/config/sign-in-link.config.js
portal-api/src/v1/users/sign-in-link.service.js
portal-api/src/v1/users/sign-in-link.service.test.js

In the new Portal 2FA flow, the sign in link needs to link to the Portal website to log the user in. The Portal website URL varies per-environment, so we need to introduce an environment variable that configures the Portal website URL and use this for the sign in link that we send to the user.
- Added a new environment variable `PORTAL_UI_URL`
- @abhi-markan will need to add this to GitHub and ensure it has the correct value per environment
- It also needs to be added to the `feat/stbr-infra` branch, so I'll raise another PR against that branch
**NOTE:** This branch was created from Luke's branch https://github.com/UK-Export-Finance/dtfs2/pull/2200 (which has not yet been merged), so also contains those changes. The only additional changes I have made are to the files:
- .env.sample
- …

feat(DTFS2-6762): create environment variable for Portal website domain in Portal API

---

portal/server/utils/csv-utils.js
portal/server/utils/csv-utils.test.js

We had issues parsing cell values with commas due to us going to csv first and then parsing the csv to JSON
No commas are needed in the values so strip the values of any commas. Added benefit that if someone has a string representing a number with commas they are removed and it is easier to parse

feat(FN-1472): remove commas from cell values

---

e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
portal/server/utils/csv-utils.js

Trying to access one of the pages in the journey of the utilisation report upload (e.g. if you had it bookmarked) would crash the page as the utilisation report would not be in the session.
Route the user back to the start of the journey if the user does not have a utilisationReport in their session.

fix: lock down report upload journey

---

portal/server/utils/csv-utils.js
portal/server/utils/csv-utils.test.js

For some cells fetching data from another sheet or document the package wouldn't populate cell.value.result correctly, instead we need to go through the hidden fields directly to _value.result to get it. I haven't figured out why it this is the case on some of the cells but have assumed there is something going wrong with the packages mapping of data from the workbook to the cell object and then how the value getter gets the result from the object.
Try and fetch cell.value?.result, if not look for cell._value.result and if not default to cell.value as it should be a plain value not using a formula to calculate it

feat(FN-1432): handle formulas where value.result is undefined

---

portal/templates/admin/user-edit.njk
portal/templates/index.njk
portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
portal/templates/utilisation-report-service/utilisation-report-upload/confirm-and-send.njk

The position of the error summary box and back button on some of the utilisation report upload pages doesn't match the designs.
The back link is placed into the top-level `index.njk` function so that it appears directly below the header. The back link can be used in a specific njk file by setting the `backLink` object via `{% set backLink = { href: '/[path]' } %}`. The back link will not appear if your njk template file doesn't include this line. The resulting appearance of `confirm-and-send.njk` and `check-the-report.njk` are shown below.
The error summary box is moved above the `<h1>` in the relevant njk file.

feat(FN-1295): back link and error positioning

---

gef-ui/server/constants/all-banks-id.js
gef-ui/server/constants/index.js
gef-ui/server/middleware/validateBank/index.js
gef-ui/server/middleware/validateBank/index.test.js
portal/server/constants/all-banks-id.js
portal/server/constants/index.js
portal/server/controllers/dashboard/deals/deals-filters-query.test.js
portal/server/controllers/dashboard/deals/index.test.js
portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js
portal/server/controllers/dashboard/facilities/index.test.js
portal/server/helpers/isSuperUser.js
portal/server/helpers/isSuperUser.test.js
portal/server/routes/admin/users.js
portal/server/routes/middleware/validateBank/index.js
portal/server/routes/middleware/validateBank/index.test.js

When we added the `read-only` role, we thought that only the `admin` role was able to have access to all banks (when the user object has `bank.id = '*'`). However, since deploying, we have realised that the `read-only` role should be able to have access to all banks too.
The `validateBank` middleware in `portal` and `gef-ui` now allows users to access all banks if they have `bank.id === '*'` and the user has the `admin` _or_ `read-only` role 
There is a `isSuperUser` function in `portal`, `portal-api`, and `gef-ui` that checks `user.bank.id === '*'` but does not check the user roles so they do not need to change for this fix

fix(DTFS2-6789): allow read-only users to have access to all banks

---

gef-ui/server/controllers/application-details/index.js
gef-ui/server/models/application.js

`read-only` user is unable to access `GEF` deal on Portal.
* Added `READ_ONLY` to valid list of users with bank set as `*`.
* Added `console.error` when unauthorised.
* Added documentation.

fix(gef-readonly): added read-only to GEF deals users

---

dtfs-central-api/src/v1/routes/portal-routes.js

[FN-1480](https://ukef-dtfs.atlassian.net/browse/FN-1480)
There are two sets of endpoints for the fetching and creating of banks:
* bank-routes.js
* POST /bank
* GET /bank/:id
* portal-routes.js
* POST /portal/banks
* GET /portal/banks/:id
They point to the same controllers, so there is no functional difference. This appears to be some tech debt left over from when Central API / TFM was created (possibly the “bank routes" were added for TFM whilst the portal routes already existed).
Since the bank collection in MongoDB is generic, the “portal routes” version should be removed.
* Remove the routes from `portal-routes.js`, keeping the `bank-routes.js` versions.
* The portal routes endpoints do not appear to be used anywhere, so no further refactoring is required.

feat(FN-1480): remove duplicate bank routes in Central API

---

docker-compose.dev.yml
docker-compose.gha.yml
docker-compose.yml
dtfs-central-api/.eslintrc.js
dtfs-central-api/init.sh
dtfs-central-api/package-lock.json
dtfs-central-api/package.json
dtfs-central-api/src/azure-env/index.js
dtfs-central-api/src/azure-env/index.ts
dtfs-central-api/src/index.ts
dtfs-central-api/tsconfig.eslint.json
dtfs-central-api/tsconfig.json

Currently `dtfs-central-api` does not support Typescript. It would improve development efficiency and reduce the chance of bugs if it did.
- updated the `package.json`
- changed the `start` script to `npx ts-node server/index.ts`
- Added `tsconfig.json`
- This allows but does not check js files 
- Added `ts-config.eslint.json`
- Changed `server/index` and `server/azure-env/index` from js to ts to verify the change works.
- replaced `require`/`module.exports` with `import`/`export`
- I haven't been able to run this on my VM yet, but it compiles to the point of needed environment variables.
- This is branched off #2279, this PR covers the changes to `dtfs-central-api`

feat(DTFS2-6780): add typescript compatibility to dtfs-central-api

---

.github/workflows/test.yml
e2e-tests/tfm/cypress/e2e/journeys/case/deal-AIN.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/deal-MIA.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/deal-page-GEF.spec.js
e2e-tests/tfm/cypress/e2e/pages/caseDealPage.js

#2295 resolved a bug where eligibility criteria were not displayed correctly, there should be e2e tests to prevent this from reoccuring
Added tests to `deal-AIN.spec.js`, `deal-MIA.spec.js` and `deal-page-GEF.spec.js` to check that the eligibility criteria displayed matches that in the database.

feat(DTFS2-6793): add e2e test for TFM Eligibility criteria

---

package-lock.json
package.json
portal-api/.eslintrc.js

A `.d.ts` type file was recently added to the portal-api project https://github.com/UK-Export-Finance/dtfs2/blob/main-stbr/portal-api/src/scheduler/types/scheduler-job.d.ts
This change adds a typescript parser to eslint so that it can correctly parse these files. This resolves a linting error where eslint wasn't able to recognise the `type` keyword.

chore: add typescript parser to portal-api to fix linting error

---

cspell.json
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-no-longer-upload-report.spec.js
e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
portal-api/api-tests/v1/utilisation-report-service/lastest-report.api-test.js
portal-api/src/v1/controllers/utilisation-report-service/due-report-dates.controller.js
portal-api/src/v1/controllers/utilisation-report-service/due-report-dates.controller.test.js
portal-api/src/v1/controllers/utilisation-report-service/index.js
portal-api/src/v1/controllers/utilisation-report-service/latest-report.controller.js
portal-api/src/v1/routes.js
portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
portal/server/api.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.test.js
portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk

When the report for the previous report period has been submitted, we want the 'Report GEF Utilisation and Fees' page to display a specific view.
- Added a new endpoint in `portal-api` to get the latest bank report
- Refactored the `utilisation-report-upload` controller in `portal` to behave differently depending on how many reports `/v1/banks/:bankId/due-report-dates` returns

feat(FN-1089): report is not due

---

utils/mock-data-loader/gef/api.js

I noticed that the mock data loader does not clear the `gef-eligibilityCriteria` collection when it runs.
I corrected the API call that mock-data-loader uses to delete GEF eligibility criteria so that it does clear the collection when it runs

fix: fix mock-data-loader clearing gef-eligibilityCriteria

---

portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js

The old implementation of FN-1134 did not check the filename report period year correctly after it passed the month validation.
Fix the `validateFilenameContainsReportPeriod` function so that it checks the report period month and year and add a new test to check this.

feat(FN-1134): fix validate filename year

---

portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk

The next report period start date was being calculated incorrectly. For example, if the next report due is April 2023, the next report period start date was being calculated as 1 April 2023 whilst it should be 1 May 2023.
Update the utilisation report upload controller to correctly calculate the next due report period start date. Also updates component tests to reflect the expected behaviour.

feat(FN-1089): fix next report period start

---

dtfs-central-api/src/services/repositories/utilisation-reports-repo.js
dtfs-central-api/src/services/repositories/utilisation-reports-repo.test.js
dtfs-central-api/src/v1/swagger-definitions/utilisationReport.js
portal-api/test-helpers/mock-utilisation-reports.js

FN-1089 uses the `firstname` and `surname` properties from the `user` who uploaded the report. However, the `uploadedBy` user was stored in a way that did not match the other `user`s stored in portal.
Change how the utilisation reports are stored so that `firstname` and `surname` from the `user` are stored with the report. Updates other parts of the code where `uploadedBy.name` is used to match this new format.

feat(FN-1089): fix report uploadedBy schema

---

e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriting-page.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/activities/activities.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/parties/parties.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case/tasks/tasks.spec.js

#2283 didnt update the e2e tests 
##Resolution
* remove redundant checks for `aria-labels` that have been removed
* update check for `deal` heading to `underwriting`

feat(DTFS2-none): remove aria label tests and update underwriting heading test

---

trade-finance-manager-ui/templates/case/deal/deal.njk

The tfm deal page has visual headings `Facilities`, `Bank Security` and `Bank Application or Notice` which are not semantically marked up with h tags. This is problematic for blind screen reader users
Replaced the `p` tags with `h2` tags.
I cannot render this locally but have used inspect element on the dev site to check the change. There is a slight change to the styles with `margin-block-start` and `margin-block-end` going from `1em` to `.83em`.

feat(DTFS2-6461): change p to h2 tags for visual headings on TFM deal page

---

e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js

In https://github.com/UK-Export-Finance/dtfs2/pull/2315, @MarRobSoftwire flagged that one of the e2e tests had an `=== {}` condition which would always return false.
I have replaced this with an accurate way to check for an empty object

fix: fix e2e injection test for user creation

---

trade-finance-manager-ui/templates/case/facility/facility.njk

Headings on the [facility page](https://tfs-staging-tfm-fd.azurefd.net/case/654d2b5686619e13af2fdc23/facility/654d2b7b86619e13af2fdc24) do not follow the correct hierarchical heading structure. Beneath heading level 2 `Facility 0040149939` there is level 3 `Cash Facility` and level 2 `contents`. Cash facility isnt really a separate heading & contents should be under the main Facility heading.
* Group the first two headings under a `hgroup` tab and upgrade Facility to a `h1`
* The contents `h2`  is inherited from the imported[ tabs component](https://design-system.service.gov.uk/components/tabs/), so this has been left as is
|   Before   |   After   |
|-----------|----------|
|![image_720](https://github.com/UK-Export-Finance/dtfs2/assets/108682750/6b7104fb-e88f-4731-ab41-e28d52e11ba5)|![im …

fix(DTFS2-6532): replace illogical facility heading levels

---

README.md
azure-functions/acbs-function/api-test-file.jest.config.js
dtfs-central-api/README.md
dtfs-central-api/api-test-file.jest.config.js
dtfs-central-api/api-test.jest.config.js
dtfs-central-api/package.json
dtfs-central-api/test-teardown-globals.js
external-api/README.md
external-api/api-test-teardown.jest.config.js
external-api/api-test.jest.config.js
external-api/package.json
portal-api/api-test-file.jest.config.js
portal-api/package.json
portal-api/test-teardown-globals.js
trade-finance-manager-api/README.md
trade-finance-manager-api/api-test-file.jest.config.js
trade-finance-manager-api/package.json
trade-finance-manager-api/test-teardown-globals.js

@francescastocco and @JoshBinns2000 noticed that the pipeline was not failing if DTFS Central API or External API API tests were failing. We tracked this down to a test teardown that would always set the exit code to 0 regardless of the test result.
I've removed the test teardown files that would set the exit code to 0.
I've removed references to the "api-test-file" scripts as they're not needed at all, the "api-test" script does the same job

fix: ensure pipeline fails if dtfs-central and external api tests fail

---

portal/templates/utilisation-report-service/previous-reports/previous-reports.njk

Update the Portal `/previous-reports` header to match the [designs](https://miro.com/app/board/uXjVMo-AmTE=/?userEmail=mtodd@ukexportfinance.gov.uk&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board).
Designs screenshot:

fix(FN-1683): correct portal previous reports header

---

portal/server/routes/utilisation-report-service/utilisation-report-upload/index.js

Needed to update the copy to match designs when a large file was uploaded
Updated the file too large copy

fix(FN-1686): update error copy for large file

---

gef-ui/server/controllers/about-facility/index.test.js

The `controllers/about-facility > Validate About Facility > redirects user to provided facility page if all of method passes test in gef-ui/server/controllers/about-facility/index.test.js` started failing today.
The facility used by the test has `shouldCoverStartOnSubmission = true` so the cover start date is `5/12/2023` today. The cover end date for the facility is hard-coded to `5/12/2023`, and the cover end date has to be strictly after the cover start date, so the validation (and test) fails.
I've changed this test to always use a future date for the cover end date, so the test passes regardless of today's date.
I fixed a typo in one of the variables in the same test file.

fix: fix about-facility UI test failing after 5/12/2023

---

e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/pricing-and-risk-risk-managers.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/pricing-and-risk.spec.js
e2e-tests/tfm/cypress/e2e/journeys/case-underwriting/underwriting-page.spec.js
e2e-tests/tfm/cypress/e2e/journeys/users/PIM_user.spec.js
e2e-tests/tfm/cypress/e2e/pages/underwriting/pricingAndRiskPage.js
e2e-tests/tfm/cypress/e2e/pages/underwriting/underwritingPage.js
e2e-tests/ukef/cypress/e2e/journeys/portal/submit-AIN-deal-creates-default-credit-rating-in-tfm/submit-AIN-deal-creates-default-credit-rating-in-tfm.spec.js
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.component-test.js
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/exporter-table.njk
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-exporter/section-exporter.component-test.js
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.component-test.js
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/_macros/section-facilities/facility-pricing-risk-table.njk

On the underwriting page the exporter table does not have the headers semantically marked up
* Changed the exporter and facilities tables to use `govukSummaryList` components

fix(DTFS-6464): use summary lists on underwriting page

---

trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.component-test.js
trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js
trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk

The tables on the TFM deal tasks page are missing some column headers. This can make it difficult for a blind screen reader user to understand what the columns are showing.
- Added 'Task' and 'Status' headings to the deal tasks tables.
- Added tests for this change.
- Added the `scope` attribute to the table headers to denote them as columns, as according to https://design-system.service.gov.uk/components/table/ this helps users of assistive technology distinguish between row and column headers.

fix(DTFS2-6463): add 'Task' and 'Status' headings to deal tasks tables

---

.github/workflows/feature_deploy.yml

We want to start deploying the TFM work for release 5.
Switch main-stbr to start deploying the new branch (to stop this branch deploying with any future fixes) and then merge this into main-stbr-tfm-5 to start deploying that branch

chore: swap feature deployments to TFM 5 release

---

trade-finance-manager-ui/component-tests/case/underwriting/loss-given-default.component-test.js
trade-finance-manager-ui/component-tests/case/underwriting/probability-of-default.component-test.js
trade-finance-manager-ui/templates/case/amendments/amendment-facility-value.njk
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/loss-given-default.njk
trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/probability-of-default.njk

Input field in `govukInput` component can have prefix and suffix, but it is not read by screen readers.
Added:
- `<span class="govuk-visually-hidden"> in ' + currency + '</span>'` 
- `<span class="govuk-visually-hidden"> in %</span>?'`

fix(DTFS-6466): accessibility - added text for screen readers to make input field prefix/suffix known

---

trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk

Table headers missing when facility is amended. Screen readers will not know that the column headings from the first table are intended to apply to the later tables as well, so screen readers will not be able to tell screen reader users what the columns mean for any table apart from the first one.
Add table headers for each section when facility is amended.

feat(DTFS2-6863): added table headers for amendment tasks

---

e2e-tests/portal/cypress/e2e/journeys/login/login.spec.js
e2e-tests/portal/cypress/e2e/journeys/login/resend-sign-in-link.spec.js

Currently, `resend-sign-in-link.spec.js` in the Portal login journey E2E tests does not reset the user status and sign in link send count after running all of the tests. This creates an order dependency, whereby running `resend-sign-in-link.spec.js` first and then `login.spec.js` will cause the later to fail because the `BANK1_MAKER1` user is still blocked as a result of the first test suite.
- added an `after` block in `resend-sign-in-link.spec.js` to reset the `BANK1_MAKER1` after all the tests have run.

fix(DTFS2-6876): fix order dependency in Portal login journey E2E tests

---

portal-api/api-tests/v1/users/users.api-test.js
portal-api/src/v1/users/routes.js
portal-api/src/v1/users/routes.test.js

In `portal-api`,  `PUT /v1/users/:_id` does not check that the logged in user has the authorisation to update the details. Whilst the end-users shouldn't have direct access to the api this should still be added
* Check if the user has role `ADMIN` or is updating their own password
* Added api & unit tests

fix(DTFS2-6672): check user authorisation when updating details

---

dtfs-central-api/src/generateApp.js
external-api/src/generateApp.ts

dtfs-central-api and external-api healthchecks were failing, I think this was because the `/healthcheck` endpoint was called after `checkApiKey`
Reorder the healthcheck

feat(FN-1261): reorder to authorise healthcheck

---

infrastructure/resource_group_level/main.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-calculated-variables.bicep
infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api-no-calculated-variables.bicep
infrastructure/resource_group_level/modules/webapps/webapp.bicep

Refactoring the bicep I wrote when we changed connection strings to environment variables
- Set all tfm-api settings in `trade-finance-manager-api-calculated-variables`, instead of setting it twice
- Rename `tfmApiConnectionStrings` module to `tfmApiCalculatedVariables`
- Add condition to `webapp.bicep` to only set `appSettings` if not empty

fix: bicep refactor

---

e2e-tests/portal/cypress/e2e/journeys/login/resend-sign-in-link.spec.js
e2e-tests/portal/cypress/e2e/journeys/login/sign-in-link-session-edge-cases.spec.js
e2e-tests/portal/cypress/e2e/pages/index.js
e2e-tests/portal/cypress/e2e/pages/login/sign-in-link-expired.js
portal-api/api-tests/api-test-users.js
portal-api/api-tests/v1/deals/deals-status-submitted.api-test.js
portal-api/api-tests/v1/deals/deals-status.api-test.js
portal-api/api-tests/v1/gef/application.api-test.js
portal-api/api-tests/v1/users/login-with-sign-in-link.api-test.js
portal-api/api-tests/v1/users/post-sign-in-link.api-test.js
portal-api/api-tests/v1/users/users.api-test.js
portal-api/src/v1/users/login.controller.js
portal-api/src/v1/users/login.controller.test.js
portal-api/src/v1/users/repository.js
portal-api/src/v1/users/repository.test.js
portal-api/src/v1/users/sanitizeUserData.test.js
portal-api/src/v1/users/sign-in-link.controller.js
portal-api/src/v1/users/sign-in-link.controller.login-with-sign-in-link.test.js
portal-api/src/v1/users/sign-in-link.service.create-and-email-sign-in-link.test.js
portal-api/src/v1/users/sign-in-link.service.js
portal-api/src/v1/users/sign-in-link.service.login-user.test.js
portal-api/test-helpers/unit-test-mocks/mock-user.js

This change fixes an edge case where a user can access a recently issued sign in link, despite being blocked.
When a user is blocked, we wipe any past tokens from the database.
We also check the user is not blocked on login. While we realistically never get to this stage, due to the method being public, it has been included to avoid future issues
Moved some legacy hand written `user-status`s to enums

fix(dtfs2 6899): fix blocked user logging in with most recent sign in link

---

portal-api/api-tests/helpers/escapeOperators.api-test.js
portal-api/package-lock.json
portal-api/package.json
portal-api/src/v1/helpers/escapeOperators.js
portal/server/controllers/dashboard/filters/generate-keyword-query.js
portal/server/controllers/dashboard/filters/generate-keyword-query.test.js

The keyword filter in portal shouldn't allow users to attack the database
- Use `KEYWORD` when sending a keyword filter to the api
- Convert `KEYWORD` into the `$regex` operator, escaping any regex special characters
- This removes the ability to send a `REGEX` request to the api, this shouldn't be used anywhere but is potentially a breaking change

chore(DTFS2-6666): remove filter vulnerabilities

---

dtfs-central-api/.eslintrc.js
dtfs-central-api/api-test-common.jest.config.js
dtfs-central-api/package-lock.json
dtfs-central-api/package.json
dtfs-central-api/src/helpers/escapeRegExp.ts
dtfs-central-api/src/v1/controllers/tfm/deal/tfm-get-deals.controller.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js

The search box in TFM shouldn't allow users to attack the database
In `dtfs-central-api` escape regex characters to prevent potential ReDOS attacks
[Attempted other ways attack the database, with no vulnerabilities found](https://ukef-dtfs.atlassian.net/browse/DTFS2-6700)
This removes the ability to search the database with regex through the api. Whilst this shouldn't be used anywhere its potentially a breaking change

chore(DTFS2-6700): remove tfm search vulnerabilities

---

portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-facility-utilisation-error.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-facility-utilisation-error.test.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-error.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-monthly-fees-paid-error.test.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-error.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-total-fees-accrued-error.test.js

[FN-1992](https://ukef-dtfs.atlassian.net/browse/FN-1992)
Currently if a report field is a number, but has more than 2 decimal places, it still returns the generic
> <field_name> must be a number
error message. Instead the error message should be
> <field_name> must be a number with a maximum of two decimal places
Update error copy for any columns validating a currency amount
* Total fees accrued for the month
* Fees paid to UKEF for the period
* Facility utilisation

feat(FN-1992): update currency validation error message

---

portal/jest.config.js
portal/server/constants/file-upload.js
portal/server/utils/csv-utils.js
portal/server/utils/csv-utils.test.js

Empty cells at the end of a row would not be processed by the excel library and so we would not get the cell addresses or empty values for these cells when processing
Keep count of how many header columns we have and add in any empty values with cell addresses so we can show descriptive error messages later on in the process.

feat(FN-1685): fix csv parsing for rows with empty data at end of row

---

trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
trade-finance-manager-ui/server/helpers/date.js
trade-finance-manager-ui/server/services/utilisation-report-service.test.js
trade-finance-manager-ui/server/services/utilisation-report-service.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
trade-finance-manager-ui/templates/utilisation-reports/utilisation-reports.njk

Some of the parameters required to generate the `updateReportStatus` payload were stored in the request `url` as query parameters instead of being hidden in the request body. This meant that manually reloading the page after attempting to mark a report as done or not done would attempt to resubmit the form.
Moves the query parameters to the body and updates the controller to extract these values.
Updates a function which didn't need access to the `userToken`.

fix(FN-1536): move payload parameters from query to body

---

portal-api/src/v1/users/sign-in-link.service.js

Automatically log the Portal sign-in link when in development to easily allow sign-in when emails are not actually sent.

chore: log sign-in link when in development

---

azure-functions/acbs-function/package-lock.json
azure-functions/acbs-function/package.json
azure-functions/number-generator-function/package-lock.json
azure-functions/number-generator-function/package.json
dtfs-central-api/package-lock.json
dtfs-central-api/package.json
external-api/package-lock.json
external-api/package.json
gef-ui/package-lock.json
gef-ui/package.json
package-lock.json
package.json
portal-api/package-lock.json
portal-api/package.json
portal/package-lock.json
portal/package.json
trade-finance-manager-api/package-lock.json
trade-finance-manager-api/package.json
trade-finance-manager-ui/package-lock.json
trade-finance-manager-ui/package.json
utils/data-migration/package-lock.json
utils/data-migration/package.json
utils/mock-data-loader/package-lock.json
utils/mock-data-loader/package.json

All our docker files and the deployed versions of our code are using node 20 rather than node 21. We should match the package.json node versions to the deployed version of node.
Note the azure functions are actually at node 14 not 20 but these are already out of sync and need to be upgraded.
Npm should also be upgraded to the npm version that is coupled with node 20 (10+)
Update package.json files to have engines pointed at node 20 and npm 10

chore(DTFS2-6952): update node and npm versions

---

portal/server/utils/csv-utils.js

We need to handle non-ascii characters in csv files in case during the download any of the characters are not ascii characters due to the different encoding used
Replace any non-ascii characters including the 65533 unicode question mark character with spaces. This works for the current mock reports we are using with the allowed headers

feat(FN-2050): handle non-ascii characters in csv files

---

trade-finance-manager-ui/templates/_partials/primary-navigation.njk

We want the `TFM-UI` "Bank reports" primary navigation item to be on the far right.
Moves the primary navigation item.

feat(FN-2070): move bank reports primary navigation

---

dtfs-central-api/api-tests/mocks/banks.ts
dtfs-central-api/src/constants/payloads.js
dtfs-central-api/src/types/db-models/banks.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts
dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/utilisation-reports-reconciliation-summary.js
portal-api/src/constants/payloads.js
trade-finance-manager-ui/server/types/custom-express-request.ts
utils/mock-data-loader/banks/index.js

We want to add a flag to banks which signals whether or not they are viewable in `TFM` (ie. whether or not they submit utilisation reports via `portal`).
Adds the `isUtilisationReportVisibleInTfm` flag to `Banks` in `dtfs-central-api` and `mock-data-loader`. This flag is not optional as we want every banks "opt-in" status to be explicit. We also add this flag to the `portal-api` payload validation as `mock-data-loader` sends the bank payload through this api.
Corrects the `CustomExpressRequest` type helper and fixes some swagger docs issues.

feat(FN-2081): add "visible in TFM" flag to banks

---

.github/workflows/deployment.yml

Ensure deployment checkout is on the workflow run head branch.
* GHA checkout with `ref`

fix(gha): checkout with ref

---

.github/workflows/sca.yml
portal-api/src/v1/users/controller.js

Portal user block and active status emails are not being delivered on `non-production` environment.
* `username` property has been replaced with `email`.
* `sca.yml` execution on all PRs

fix(DTFS2-7003): refer to email property as opposed to username

---

.github/workflows/deploy.sh
.github/workflows/deployment.yml
.github/workflows/test.yml

Production deployments on GitHub Event hook are not being trigged.
* Updated branch name to `prod` from `production`.

fix(deployment)!: changed branch name to prod

---

utils/mock-data-loader/bss/eligibilityCriteria.js

`BSS/EWCS` EC 16 does not include fossil fuel wording.
* Updated `BSS/EWCS` `v7` EC `16`.

fix(dTFS2-7007): Ensure EC wording is correct

---

dtfs-central-api/src/v1/validation/create-facility-rules/associated-deal-id.js
dtfs-central-api/src/v1/validation/create-facility-rules/type.js

Remove inline suppression of eslint `default-param-last` rule as requested in a [separate PR](https://github.com/UK-Export-Finance/dtfs2/pull/2596#discussion_r1487381621).

refactor(FN-2226): remove suppression of eslint 'default-param-last' rule

---

e2e-tests/package.json
gef-ui/server/utils/helpers.test.js
package-lock.json
trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js
trade-finance-manager-api/package.json
trade-finance-manager-api/src/utils/date.test.js
trade-finance-manager-api/src/v1/helpers/get-guarantee-dates.api-test.js
trade-finance-manager-api/src/v1/rest-mappings/mappings/facilities/mapCoverEndDate.api-test.js
trade-finance-manager-api/src/v1/rest-mappings/mappings/gef-facilities/mapGefFacilityDates.api-test.js
trade-finance-manager-ui/server/nunjucks-configuration/filter-formatDateString.test.js

Moment js is deprecated, it should be replaced. The functional code is changed in #2758 .
* Replace moment() with vanilla Dates where possible and date-fns where necessary in
* gef-ui 
* trade-finance-manager-api
* trade-finance-manager-ui

chore(DTFS2-4533): remove moment from gef-ui, tfm-api and tfm-ui tests

---

dtfs-central-api/src/utils/date.test.ts
dtfs-central-api/src/utils/date.ts
dtfs-central-api/src/utils/report-period.test.ts
dtfs-central-api/src/utils/report-period.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts

Change `isEqualReportPeriodStart` function in `report-period` utils to more general `isEqualMonthAndYear` in `date` utils.

refactor: change 'isEqualReportPeriodStart' to 'isEqualMonthAndYear'

---

e2e-tests/portal/cypress/e2e/journeys/maker/submit-a-deal-for-review-with-issued-and-unissued-facilities-and-resubmit-after-checker-returns/dealReadyToSubmitToChecker.js
portal-api/src/constants/date-formats.ts
portal-api/src/now.js
portal-api/src/v1/controllers/deal-status/create-approval-date.js
portal-api/src/v1/controllers/deal-status/create-mia-submission-date.js
portal-api/src/v1/controllers/deal-status/create-submission-date.js
portal-api/src/v1/gef/controllers/application-submit.js
portal-api/src/v1/users/controller.js

Moment js is deprecated, it should be replaced. This PR wont convert any tests - see #2706 
Validation changes are covered by #2797, facility-dates changes are covered by #2799
* Replace moment() with vanilla Dates where possible and date-fns where necessary
* replace `now()` method with `getNowAsEpochMillisecondString()` date helper
* Cleaned up some obsolete functions handling dates
*  `updateCoverEndDate` doesn't return `NaN` when the date or year is invalid. I believe this wasn't intended but the test coverage doesn't verify this
* Need to remove `formattedTimestamp` function and package dependency on `moment` once both PRs are merged

chore(DTFS2-6994): remove moment js from portal-api

---

dtfs-central-api/src/helpers/fee-record.helper.ts
dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/previous-reports/list-previous-reports.spec.js
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirm-and-send.spec.js
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/confirmation.spec.js
e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
e2e-tests/support/tasks.js
portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js

Portal e2e tests are currently failing due to the reports that are being inserted having the wrong schema.
- Updates the generated mocks in `e2e-tests/portal` to use the `UtilisationReportEntityMockBuilder`
- Improves test coverage for some e2e tests

feat(FN-1853): fix portal e2e test mock reports

---

portal/component-tests/utilisation-report-service/previous-reports.component-test.js
portal/templates/utilisation-report-service/previous-reports/previous-reports.njk
portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk

FN-2331 - check report page title was not descriptive that an error had occurred
FN-2334 - download previous GEF report label text did not match link text
[FN-2331](https://github.com/UK-Export-Finance/dtfs2/pull/2909)
[FN-2334](https://github.com/UK-Export-Finance/dtfs2/pull/2910)

feat(FN-2331&FN-2334): Updating labels & titles to be more descriptive

---

libs/common/src/sql-db-connection/migrations/1711452223370-UpdateActivityLogsColumns.ts
libs/common/src/sql-db-entities/base-entities/auditable.base-entity.ts

The previous #2918 pull request caused the deployment pipeline to fail with migrations due to the `lastUpdatedByIsSystemUser` not having a default value.
Removes the old migration and generates a new one which includes the default value.

feat(FN-1864): add default value for lastUpdatedByIsSystemUser column

---

portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
portal/templates/utilisation-report-service/utilisation-report-upload/check-the-report.njk
portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk

The utilisation report upload button labels did not include information about the expected file type, meaning users who use a screen reader would not be provided that information when focusing on the button.
Moves the `div.govuk-hint` element inside of the `label`.
Below are screenshots from using the google chrome accessibility dev tools to show that the label for the button now include the file type information.
"Utilisation report upload"
"Check the report"

feat(FN-2335): accessibility fix for utilisation report upload buttons

---

dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports.api-test.ts
dtfs-central-api/api-tests/v1/utilisation-reports/put-utilisation-report-status.api-test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/manually-set-incomplete/manually-set-incomplete.event-handler.ts
dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller/index.test.ts
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
libs/common/src/test-helpers/mock-data/utilisation-report.entity.mock-builder.ts
portal-api/api-tests/v1/utilisation-report-service/previous-reports.api-test.js
portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.js
portal-api/src/v1/controllers/utilisation-report-service/last-uploaded.controller.js
portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.ts
trade-finance-manager-api/api-tests/v1/utilisation-reports/update-utilisation-report-service.api-test.ts
trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.test.ts
trade-finance-manager-api/src/v1/validation/route-validators/update-report-status-payload-validation/index.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/update-utilisation-report-status/index.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk

We want to remove the ability of `PDC_RECONCILE` users to mark reports in the `REPORT_NOT_RECEIVED` state as completed. This change will now mean that any report not in the `REPORT_NOT_RECEIVED` state has been uploaded.
- Updates the state machine to no longer allow reports in the `REPORT_NOT_RECEIVED` state to be marked as completed
- Updates TFM-UI to not display the checkbox for reports in the `REPORT_NOT_RECEIVED` state
- Updates unit, api and e2e* tests to reflect these changes
- Update the `UtilisationReportEntityMockBuilder` to use a generic (see [this comment](https://github.com/UK-Export-Finance/dtfs2/pull/2926#discussion_r1537473223))
- Updates `tfm-ui` so that you can mark `'PENDING_RECONCILIATION'` and `'RECONCILIATION_COMPLETED'` reports as not completed and completed …

feat(FN-1862): remove mark not received as completed

---

dtfs-central-api/api-tests/sql-db-helper.ts
e2e-tests/support/tasks.js
libs/common/src/sql-db-connection/migrations/1711652127585-AddFeeRecordCascadeDelete.ts
libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
portal-api/api-tests/sql-db-helper.ts

We want to add cascade deletes to the `FeeRecord` table.
A `FeeRecord` has a many-to-one relation with the `UtilisationReport` table, so making this change means that deleting a row in the `UtilisationReport` table will delete all linked rows in the `FeeRecord` table.
- Adds the cascade delete option to the `FeeRecord` entity
- Generates the required migration
- Updates existing implementations where `FeeRecord` rows are manually deleted before `UtilisationReport` rows are deleted

feat(FN-1853): add cascade delete to fee record table

---

dtfs-central-api/api-tests/mocks/utilisation-reports/utilisation-report-reconciliation-summary.ts
dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts
dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
dtfs-central-api/src/types/utilisation-reports.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports-reconciliation-summary.controller/helpers.ts
dtfs-central-api/test-helpers/test-data/bank-report-period-schedule.ts
dtfs-central-api/test-helpers/test-data/bank.ts
dtfs-central-api/tsconfig.eslint.json
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/mark-report-as-done.spec.js
libs/common/src/utils/report-period.test.ts
libs/common/src/utils/report-period.ts
portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.ts
portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-details.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.ts
trade-finance-manager-ui/server/services/utilisation-report-service.test.js
trade-finance-manager-ui/server/services/utilisation-report-service.ts
trade-finance-manager-ui/server/test-mocks/mock-utilisation-report-reconciliation-summary.ts
trade-finance-manager-ui/server/types/utilisation-reports.ts

Include quarterly reports on the TFM reports page
- FN-1456: Current reporting period section contains current quarterly reports and if there are any include the quarterly report period in the heading
- FN-1412: Open reports sections contain open quarterly reports, grouped by their submission month with monthly reports, and the header details the quarterly report period if there is one
- Also closes off FN-1799, using shortened months for report period headers, this was pre-existing behaviour for the monthly report periods included in headers and has been continued to be used for the quarterly report periods in headers.

feat(FN-1456): quarterly reports on TFM bank reports page

---

libs/common/src/utils/report-period.test.ts
libs/common/src/utils/report-period.ts
portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.test.js
portal-api/src/v1/controllers/utilisation-report-service/previous-reports.controller.ts
portal/component-tests/utilisation-report-service/previous-reports.component-test.js
portal/server/controllers/utilisation-report-service/previous-reports/index.test.ts
portal/server/controllers/utilisation-report-service/previous-reports/index.ts
portal/templates/utilisation-report-service/previous-reports/previous-reports.njk

Display previous quarterly reports to portal users.
- Display quarterly reports in the tabs for all years they span on the portal previous reports page
- Include the formatted period in the link text for quarterly reports and the fact it is quarterly

feat(FN-2559): quarterly previous reports

---

dtfs-central-api/api-tests/v1/tfm/facilities/tfm-facility-put.api-test.js
dtfs-central-api/src/v1/controllers/tfm/facility/tfm-update-facility.controller.js
dtfs-central-api/src/v1/routes/tfm-routes.js
trade-finance-manager-api/api-tests/api-ssrf.api-test.js
trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/acbs.controller.js
trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
trade-finance-manager-api/src/v1/controllers/amendment.controller.js
trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
trade-finance-manager-api/src/v1/controllers/facility.controller.js
trade-finance-manager-api/src/v1/controllers/tfm.controller.js
trade-finance-manager-api/src/v1/controllers/update-facilities.js
trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js

All endpoints in dtfs-central-api should add `auditDetails` when inserting/updating data. This PR covers the update facility endpoint
- Add audit details to database changes for update facility endpoint

feat(DTFS2-7083): add audit logs to update facility endpoint

---

libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts

Auditable Base Entity columns should be moved to the end of the AzureFileInfo, FeeRecord and UtilisationReport tables
- Updated migration

feat(FN-2183): reorder table columns

---

portal-api/src/v1/controllers/deal-status.controller.js
trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js

The sporadic bug can still be reproduced on `staging`.
* Increased delay to `1s`.
* Enhanced logging for deal fetch comparisson.

fix(DTFS2-7091): increased delay and enhanced logging

---

portal-api/api-tests/v1/gef/application-submit.api-test.js
portal-api/api-tests/v1/gef/application.api-test.js
portal-api/api-tests/v1/gef/clone-gef-deal.api-test.js
portal-api/api-tests/v1/gef/eligibility-criteria.api-test.js
portal-api/api-tests/v1/gef/facilities.api-test.js
portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js
portal-api/src/v1/gef/controllers/application-submit.js
portal-api/src/v1/gef/controllers/application.controller.js
portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
portal-api/src/v1/gef/controllers/eligibilityCriteria.controller.js
portal-api/src/v1/gef/controllers/facilities.controller.js
portal-api/src/v1/gef/controllers/files.controller.js
portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js
portal-api/src/v1/gef/models/application.js
portal-api/src/v1/gef/models/eligibilityCriteria.js
portal-api/src/v1/gef/models/facilities.js
portal-api/src/v1/gef/models/files.js
portal-api/src/v1/gef/models/mandatoryCriteria.js
portal-api/src/v1/users/routes.js

All endpoints in portal-api should add `auditRecords` when inserting/updating data. This PR covers the gef router.
- Add audit record to database changes for gef routes

feat(DTFS2-7120): add audit logs to gef routes of portal api

---

.github/workflows/test.yml
cspell.json
doc/sql-db.md
utils/sql-db-seeder/src/fee-record/fee-record.helper.ts
utils/sql-db-seeder/src/utilisation-report/utilisation-report.helper.ts
utils/sql-db-seeder/src/utilisation-report/utilisation-report.seed.ts

We need a way of seeding fee record data to view parts of the premium payments table.
Adds a new seeder for a fee record which:
- has matching currencies
- has differening currencies*
*This will have an affect on the `Reported fees` and `Reported payments` columns of the TFM premium payments table.
Updates documentation for the sql seeder.

feat(FN-1615): add seeder for fee records

---

libs/common/src/sql-db-connection/migrations/1715613302494-AddFeeRecordStatusColumn.ts
libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts

We need a default value for the new status column in the `FeeRecord` SQL table.
- Updates the entity to have the default value
- Replaces the old migration

feat(FN-1615): add default value for fee record status column

---

.github/workflows/deployment.yml

Add `release-2.0` to deployment to avoid rebasing `dev` branch

fix(deployment): added release-2.0 to deployment

---

libs/common/src/sql-db-connection/migrations/1715613302494-AddFeeRecordStatusColumn.ts

We need to fix the migration which adds the status column to the fee record table.
The current migration tries to set the `status` column of all existing fee records to `null`, whereas we actually want it to set it to `TO_DO`. This PR makes that change.

fix(FN-1615): add update query to fee record status migration

---

libs/common/src/helpers/currency.test.ts
libs/common/src/helpers/currency.ts

We want to use proper formatting for currency and amount strings.
- Updates the currency helper to use a formatter
- Adds unit tests for the currency helpers

feat(FN-1615): update the formatting for the currency and amount string

---

trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk

The status column of the premium payments table was not sortable.
- Make the column sortable

feat(FN-1616): add sort by status to premium payments table

---

trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk

We want to update the alignment on columns in the premium payments table which contain numeric values.
- Updates the template to use the `govuk-table__header--numeric` and `govuk-table__cell--numeric` classes
- Updates the component tests to check these classes are used where they are needed

feat(FN-2882): update premium payments table alignment

---

dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-added-to-fee-record/payment-added-to-fee-record.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/payment-added-to-fee-record/payment-added-to-fee-record.event-handler.ts
dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts

We want to implement the `'PAYMENT_ADDED_TO_FEE_RECORD'` utilisation report state machine event.
- Implements the event handler
- Updates unit tests
- Removes linked `TODO` comments

feat(FN-1697): implement payment added to fee record event

---

doc/sql-db.md
libs/common/package.json
libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts
libs/common/src/sql-db-connection/reset-database.sh
package-lock.json

The database we use in deployed environments uses ledger tables, but our local setup does not. This means that it is possible for migrations to work locally and on the test pipeline, but fail once deployed. To get around this, we want to update the initial migration to create all tables with ledger enabled. This results in the original `db:drop-all` command we have to fail as we cannot drop tables in the same way, so we also need to update this command to properly reset the database.
- Updates the initial migration without changing the filename*
- Adds a new `reset-database.sh` script to `libs/common/src/sql-db-connection`
*we don't need to run this migration as a new migration in deployed environments, so there is no need to generate a new migration for it

feat(FN-2900): update local SQL to use ledger tables

---

libs/common/src/sql-db-connection/migrations/1716990167763-AddPaymentTable.ts
libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
libs/common/src/sql-db-entities/index.ts
libs/common/src/sql-db-entities/payment/index.ts
libs/common/src/sql-db-entities/payment/payment.entity.ts
libs/common/src/sql-db-entities/payment/payment.types.ts
libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
libs/common/src/test-helpers/mock-data/index.ts
libs/common/src/test-helpers/mock-data/payment.entity.mock-builder.ts

We want to add a new SQL `Payment` table.
- Adds the new entity
- Generates the new migration (with ledger enabled)
- Adds the new `ManyToMany` relation to the fee record entity
- Adds a new entity mock builder for the `Payment`
- Adds new methods to the fee record entity mock builder to allow for defining payments

feat(FN-1739): add payment table

---

dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report-sql.repo.ts
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/utilisationReportUpload.js
e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
portal/component-tests/utilisation-report-service/utilisation-report-upload.component-test.js
portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk

When reports are inserted in the wrong order into the database the next report due to be uploaded is incorrect.
- in `findAllByBankId` method add sorting reports by report period

feat(FN-2846): add ordering to utilisation reports request

---

doc/sql-db.md
dtfs-central-api/api-tests/v1/utilisation-reports/post-payment.api-test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/add-a-payment.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/helpers.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/add-a-payment/helpers.ts
dtfs-central-api/src/services/state-machines/utilisation-report/utilisation-report.state-machine.test.ts
dtfs-central-api/src/types/utilisation-reports.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/helpers.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.ts
libs/common/src/sql-db-connection/migrations/1717746522387-PaymentTableUpdateAmountColumns.ts
libs/common/src/sql-db-connection/reset-database.sh
libs/common/src/sql-db-entities/custom-columns/monetary-column.ts
libs/common/src/sql-db-entities/payment/payment.entity.ts
libs/common/src/sql-db-entities/payment/payment.types.ts
libs/common/src/test-helpers/mock-data/payment.entity.mock-builder.ts

We want to rename some of the Payment table columns and update one of the data types to match our other monetary value columns.
- Updates the `PaymentEntity` class
- Updates references to the old column names
- Makes the `reset-database.sh` script more robust

feat(FN-1739): update table column names and data types

---

docker-compose.gha.yml

Change streams & transactions need mongodb to use a replica set. In order to test these features the GHA should run on one.
- Update the docker-compose file
It's unclear if this change affects the flakiness of the tests. To check this I've run the pipeline 6 times & found:
- 16 test suites failed flakily
- 7 of these were genuine test failures, the remainder `write EPIPE`, docker failures, MDL failures, etc.
- The `dtfs-central-api` utilisisation report tests seem to be the most flakey, accounting for 4 of these 7 and failing more often than not.
Aside from the utilisisation report, this doesnt seem to be a notable increase in flakiness over a normal PR (at a glance)

feat(DTFS2-7055): update docker-compose.gha.yml to use replica set

---

dtfs-central-api/src/generateApp.js
dtfs-central-api/src/v1/routes/bank-routes.js
dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
dtfs-central-api/src/v1/swagger-definitions/tfm.js
dtfs-central-api/src/v1/swagger.js

We want to open the route for `/api-docs` locally in `dtfs-central-api`. After opening the route, it was discovered that the swagger docs were not displaying properly.
- Opens the route
- Fixes the swagger docs `api` definition so that they docs are visible at the `/v1/api-docs` route
- Puts some extraneous routes into the `Utilisation Report` tag

fix(FN): fix swagger docs and open route

---

trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.js
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk

We want to disable sorting on the premium payments table "Payments received" and "Total payments received" column when the fee record table `paymentsReceived` column contains no values.
- Updates the controller to supply a `enablePaymentsReceivedSorting` flag
- Updates associated tests

feat(FN-2902): disable sorting when payments columns are empty

---

dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts

`get-utilisation-reports-reconciliation-summary.api-test.ts` is failing because it runs code before the SQL db connection has been initialised.
Add a timeout to prevent the code from running before the DB connection is initialised. This should only be a temporary fix but a large refactor of the `createApi` & `createApp` files would be needed otherwise

chore(DTFS2-NONE): add sleep to utilisation recon summary test

---

trade-finance-manager-api/src/types/custom-express-request.ts
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-payment.controller.test.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/post-payment.controller.ts
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-api/test-helpers/tfm-session-user.ts
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/add-payment-form-values-validator.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/add-payment-form-values-validator.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
trade-finance-manager-ui/test-helpers/test-data/add-payment-view-model.ts

We want to link up the adding a payment frontend to the backend.
This PR also resolves the [FN-1742](https://ukef-dtfs.atlassian.net/browse/FN-1742) ticket.
- Adds a new route to `TFM-API`
- Adds tests
- Updates the `TFM-UI` controller to allow for adding a new payment
- Fixes the `TFM-API` `custom-express-request.ts` file

feat(FN-1739): link add payment frontend to backend

---

trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/parse-validated-add-payment-form-values.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/parse-validated-add-payment-form-values.ts
trade-finance-manager-ui/server/types/add-payment-form-values.ts

The parsing of comma separated payment amounts in the add payment form was not working as expected.
- Add a separate function to parse the form data before it is submitted
- Add unit tests for the new function

feat(FN-1739): add parser to parse form values before sending

---

dtfs-central-api/api-tests/v1/facilities/facilities.api-test.js
dtfs-central-api/src/v1/controllers/portal/facility/create-multiple-facilities.controller.js
portal-api/api-tests/createFacilities.js
portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js

We need to add audit details to portal endpoints
This PR adds audit details to the `create multiple facility` endpoint

feat(dtfs2-6966): add audit logs to create multiple facilities endpoint

---

dtfs-central-api/api-tests/v1/utilisation-reports/get-fee-records-to-key.api-test.ts
dtfs-central-api/src/repositories/utilisation-reports-repo/utilisation-report.repo.ts

The original query would return `null` if there are no fee records matching the supplied status. This PR makes it so that the `feeRecords` array will instead be empty.
- Updates the `UtilisationReportRepo`

feat(FN-1714): update query when getting reports

---

trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/get-generate-keying-data-error-helper.ts

The check keying data error text should say "No matched fees..." instead of "No matched facilities..."
- Fixes the error text

feat(FN-1714): fix check keying data error text

---

e2e-tests/e2e-fixtures/constants.fixture.js
e2e-tests/e2e-fixtures/dbCollections.ts
e2e-tests/support/tasks.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/delete-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/mark-report-as-done.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/pdc-reconcile/delete-payment.spec.js
e2e-tests/tfm/cypress/e2e/pages/index.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportConfirmDeletePaymentPage.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportEditPaymentPage.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportsPage.js
trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk

We want to add e2e tests for the TFM delete payment journey.
- Adds the e2e test
- Adds new functions to the `tasks.js` support file
- Adds some `data-cy` selectors to templates
- Removes the `utilisation-reports/pdc-reconcile` e2e test directory

feat(FN-1720): add e2e tests for deleting payments

---

external-api/src/external-api/countries.ts
portal-api/src/external-api/__mocks__/countries.js

Ensure countries are disabled as per the list in `mocks` and enable `Burundi` for cover.
* Enabled `Burundi` country for cover.
* Aligned mock countries with `countries.ts` list.

fix(DTFS2-7248): disabled countries in mock

---

e2e-tests/e2e-fixtures/constants.fixture.js
e2e-tests/support/tasks.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportEditPaymentPage.js
trade-finance-manager-ui/templates/utilisation-reports/edit-payment.njk

We want to add some e2e tests for the TFM edit payment journey.
- Adds the e2e test
- Adds some extra assertions to the `add-payment.spec.js` test

feat(FN-1718): add edit payment e2e tests

---

e2e-tests/e2e-fixtures/constants.fixture.js
e2e-tests/support/tasks.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/delete-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/edit-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/mark-report-as-done.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/navigating-to-utilisation-reports.spec.js
e2e-tests/tfm/cypress/e2e/pages/index.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportPage.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportsPage.js
e2e-tests/tfm/cypress/e2e/pages/utilisationReportsSummaryPage.js

We want to add e2e tests for filtering the premium payments table by facility id.
- Adds the e2e test
- Adds a new cypress task to insert payments
- Separates the constant for the utilisation reports summary page and the utilisation reports page

feat(FN-1617): add e2e tests for filtering by facility id

---

dtfs-central-api/src/helpers/fee-record.helper.test.ts
dtfs-central-api/src/helpers/fee-record.helper.ts
dtfs-central-api/test-helpers/test-data/index.ts
dtfs-central-api/test-helpers/test-data/utilisation-report-raw-csv-data.ts

Fee records with zero payments should move to match status automatically when report is uploaded.
- When a fee record has 'fees paid to ukef for the period' equal to zero then the status of the created fee record should be 'MATCH'
- When a fee record has 'fees paid to ukef for the period' with a non-zero amount then the status of the created fee record should be 'TO_DO'

feat(FN-2622): automatically match fee records with zero payments

---

dtfs-central-api/src/cron-scheduler-jobs/create-utilisation-reports/index.test.ts
dtfs-central-api/src/services/changeStream/changeStreamApi.test.ts
libs/common/src/helpers/gef-deal-versioning.test.ts
libs/common/src/helpers/is-feature-flag-enabled.test.ts
portal-api/src/cron-scheduler-jobs/helpers/utilisation-report-helpers.test.ts
portal-api/src/cron-scheduler-jobs/send-report-due-emails-job/index.test.ts
portal-api/src/cron-scheduler-jobs/send-report-overdue-emails-job/index.test.ts
portal-api/src/cron-scheduler-jobs/send-report-submission-period-start-emails-job/index.test.ts
portal-api/src/v1/services/utilisation-report/email-service.test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/search-reports-table.component-test.js
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js
trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts
trade-finance-manager-ui/server/services/utilisation-report-service.test.js

When modifying the `process.env` file in tests, its not always correctly reset
Shallow clone the original process.env at the start of every test, so it's not reassigned unintentionally

feat(DTFS2-NONE): reset process.env correctly in tests

---

azure-functions/acbs-function/Dockerfile
azure-functions/acbs-function/api.js
azure-functions/acbs-function/constants/index.js
azure-functions/acbs-function/constants/request.js
azure-functions/acbs-function/package.json
external-api/tsconfig.json
gef-ui/package.json
package-lock.json
portal/package.json
trade-finance-manager-ui/package.json
utils/package.json

Durable functions `acbs` Azure Functions container was failing due to lack of `TS` transpile to `JS`.
* Webpack installation could scope creep the resolution will be time intensive, as a swift resolution constant have been introduced to `acbs-functions` as JS.
* Removed `@ukef/dtfs2-common` package dependency.
* Dockerfile: NPM cache clean has been added post installation.
* All `"@ukef/dtfs2-common` package version has been explicitly set to specific version `1.0.0`.

fix(acbs-durable-functions): resolve durable functions container startup error

---

trade-finance-manager-ui/server/routes/utilisation-reports/index.ts

I noticed I missed putting the set status endpoint behind a feature flag off check
- Validate the payment reconciliation feature flag is off when request is made to set report status

feat(FN-1811): prevent set report status when feature flag is enabled

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/filter-fee-records-by-facility-id.spec.js
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/validate-facility-id-query.ts
trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk

The error messaging was not in line with GDS recommendations and was not showing next to the input due to a bug.
- Display error text next to input
- Update wording of existing error message
- Add two new cases
- Ensure buttons wrap in the most sensible way when error message is long

feat(FN-1617): update error messages and display next to input

---

.github/workflows/feature_deploy.yml

We want to have a new feature environment in github so that we can control deployments to the feature env separately to deployments to dev and enable SQL to be deployed to without overlapping variable/secret names
Point feature_deploy at feature environment now instead of dev environment so it doesn't use the dev variables/secrets. Behind the scenes we also populated the feature env in github
Note this makes it much easier to combine the feature_deploy and deployment.yml files now, however I'm holding off doing this until branching/release strategy talks are finished as we might be refactoring parts anyway!

feat(FN-3202): use feature GitHub env for feature deploy

---

dtfs-central-api/src/v1/routes/utilisation-reports-routes.js
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/utilisation-reports/index.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/put-keying-data-mark-as-done.controller.test.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/put-keying-data-mark-as-done.controller.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/put-keying-data-mark-as-to-do.controller.test.ts
trade-finance-manager-api/src/v1/controllers/utilisation-reports/put-keying-data-mark-as-to-do.controller.ts
trade-finance-manager-api/src/v1/routes.js
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/index.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/keying-sheet-checkbox-id-helpers.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/keying-data/keying-sheet-checkbox-id-helpers.ts
trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
trade-finance-manager-ui/server/types/keying-sheet-checkbox-id.ts
trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table.njk
trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk

We need to be able to mark keying sheet rows as DONE and as TO DO
- Make respective api calls when mark as done and mark as to do buttons are clicked
- Ignore any selected checkboxes for rows already at the status we are moving to

feat(FN-1728): mark keying data as done/to do buttons

---

dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-fee-record-payment-groups.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-fee-record-payment-groups.ts

Fee records in a group which have had their keying sheet generated can have different statuses to each other.
- Display the status 'READY TO KEY' when any fee record in a group has status `READY_TO_KEY`
- Use the status of the first record in the group otherwise (since all fee records will have the same status)
- Change to test set up to allow easily testing with different combinations of statuses
Group in premium payments tab:
Corresponding keying sheet tab rows for some of the fee records in group:

feat(FN-1728): display fee record group status correctly for ready to key data

---

.gitignore
docker-compose.gha.yml
docker-compose.replica-set.yml
docker-compose.yml
libs/common/src/sql-db-connection/Dockerfile
libs/common/src/sql-db-connection/init.sh
utils/copy-env-vars/index.ts

A recent update on Microsoft MSSQL version especially `2022` have path and driver updates.
This has broken the pipeline due to absence of any health check for `dtfs-sql` container pipeline debugging has been inaccurate.
This PR aims to mitigate both the issues.
* Downgraded MSSQL docker image to explicit version `mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04`
* Refactored `init.sh` for MSSQL server boot.
* Added health check to `dtfs-sql` container.
* Renamed `dtfs-submissions-data` to `dtfs-mongo` for consistent naming convention.

fix(DTFS2-7292): downgraded MSSQL to 2022

---

.github/workflows/deployment.yml
.github/workflows/test.yml

We need to allow release branches to deploy to the staging environment
I've specifically done this as a tiny change to just support what we need for release-2.3 rather than doing an overhaul.
In an ideal world I would:
- trigger deployments from pushing to the branch and get rid of the test.yml step for deployments
- delete references to staging branch
- delete references to dev branch
- add a manual github action (workflow_dispatch) to allow main to deploy to dev (or automatic main -> dev deployment and refactor the deployment pipeline to reduce downtime, e.g. get all slots ready then swap them together rather than in serial build an image, create a slot then slot swap for each service)

feat(DTFS2-7288): allow release branches to deploy to staging env

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
dtfs-central-api/src/types/fee-records.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-keying-sheet.ts
dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/keying-sheet.js
libs/common/src/sql-db-connection/migrations/1722868553795-RemoveFeeRecordAccrualsColumn.ts
libs/common/src/sql-db-entities/fee-record/fee-record.entity.ts
libs/common/src/sql-db-entities/fee-record/fee-record.types.ts
libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
trade-finance-manager-api/src/v1/api-response-types/utilisation-report-reconciliation-details-response-body.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table.component-test.ts
trade-finance-manager-ui/server/api-response-types/utilisation-report-reconciliation-details-response-body.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table.njk
utils/sql-db-seeder/src/fee-record-payment-group/fee-record-payment-group.helpers.ts

We want to remove the keying sheet columns related to accruals.
- Removes the fee record column with a new migration
- Remove all references to the premium accrual balance adjustment

feat(FN-3289): remove the keying sheet accruals columns

---

azure-functions/acbs-function/mappings/facility/helpers/get-facility-currency-exchange-rate.js
azure-functions/acbs-function/mappings/facility/helpers/get-fee-amount.js
azure-functions/acbs-function/mappings/facility/helpers/get-interest-or-fee-rate.js
azure-functions/acbs-function/mappings/facility/helpers/get-loan-amount-difference.js
utils/data-migration/helpers/format.js

We incorrectly use `Integer` to refer to numbers which are not ints.
Update these to number
I know that `Integer` does not exist in JS -- To avoid this being a contentious PR, I've left `Integer` in where it makes sense (`months` etc), as JSDocs do not care this isn't a real type

fix(dtfs2-7311): update integer in jsdocs when incorrect

---

.github/workflows/test.yml
e2e-tests/gef/cypress/support/commands/loadData.js
package.json
utils/README.md
utils/create-keying-sheet-tfm-facilities/database-client/facility-client.ts
utils/create-keying-sheet-tfm-facilities/database-client/index.ts
utils/create-keying-sheet-tfm-facilities/database-client/mongo-db-client.ts
utils/create-keying-sheet-tfm-facilities/database-client/tfm-facility-client.ts
utils/create-keying-sheet-tfm-facilities/helpers/generate-random-tfm-facility-for-facility.ts
utils/create-keying-sheet-tfm-facilities/helpers/get-sql-facility-ids.ts
utils/create-keying-sheet-tfm-facilities/helpers/get-valid-gef-deal-id-generator.ts
utils/create-keying-sheet-tfm-facilities/helpers/index.ts
utils/create-keying-sheet-tfm-facilities/index.ts
utils/create-keying-sheet-tfm-facilities/mock-data/facility.ts
utils/create-keying-sheet-tfm-facilities/mock-data/index.ts
utils/create-keying-sheet-tfm-facilities/mock-data/tfm-facility-amendment.ts
utils/mock-data-loader/tfm/clean-all-tables-tfm.js
utils/package.json

The SQL seeder inserts entries in the `FacilityUtilisationData` table, where the `id` column of this table should correspond to a Mongo DB facility `ukefFacilityId`. This PR adds a new util script which inserts these entries after the seeder is run so that the keying sheet functionality works without error.
- Adds a new util
- Makes the `npm run load` command run all the local data-loading related scripts
- Updates the test pipeline so that only the mock data loader gets run before each test step
- Fix a bug where mock data loader doesn't actually clear the `tfm facilities` collection
- Updates the utils `README.md`

feat(FN-1725): util to create keying sheet tfm facilities

---

dtfs-central-api/src/constants/amendments.ts
dtfs-central-api/src/v1/controllers/tfm/amendments/tfm-get-amendments.controller.ts
libs/common/src/constants/amendment-status.ts
libs/common/src/constants/amendments.ts
libs/common/src/constants/index.ts
libs/common/src/types/amendment-status.ts
trade-finance-manager-api/api-tests/api-ssrf.api-test.js
trade-finance-manager-api/api-tests/v1/amendments/create-amendment-tfm-object-on-amendment-completion.api-test.js
trade-finance-manager-api/src/constants/amendments.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/amendment.controller.js
trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
trade-finance-manager-api/src/v1/helpers/amendment.helpers.test.js
trade-finance-manager-ui/server/api-response-types/amendments.ts
trade-finance-manager-ui/server/api-response-types/index.ts
trade-finance-manager-ui/server/api-ssrf.test.js
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.controller.js
trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.get.api-test.js
trade-finance-manager-ui/server/controllers/case/amendments/amendmentFacilityEndDate.post.api-test.js
trade-finance-manager-ui/templates/case/amendments/amendment-facility-end-date.njk

When adding a new facility end date to an amendment, it should show the current facility end date if either: 
- this is the first amendment, and the facility snapshot when received into tfm contains a facility end date OR
- this an additional amendment, and a previous amendment has already updated the facility end date to a value in which case it should display the FED of the most recent amendment that updated the FED. 
- Added the current facility end date section to the nunjucks file
- retrieve the latest amendment FED submitted from the API
- Reduces some repetition in test files

feat(DTFS2-7232): add current facility end date to amendments

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
dtfs-central-api/src/errors/transaction-failed.error.ts
dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
dtfs-central-api/src/helpers/execute-with-sql-transaction.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/index.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-to-an-existing-payment.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/reconcile-fee-records.spec.js
libs/common/src/sql-db-connection/migrations/1723453818266-AddFacilityUtilisationDataFixedFeeColumn.ts
libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.test.ts
libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.entity.ts
libs/common/src/sql-db-entities/facility-utilisation-data/facility-utilisation-data.types.ts
libs/common/src/test-helpers/mock-data/facility-utilisation-data.entity.mock-builder.ts
libs/common/src/test-helpers/mock-data/fee-record.entity.mock-builder.ts
libs/common/src/utils/report-period.test.ts
libs/common/src/utils/report-period.ts

We want to update the facility utilisation data table when keying data is generated for a facility.
Due to the fact that keying data generation modifies data on the actual objects we pass in, it is important that the updates are performed in the correct order ie. the principal balance adjustment and fixed fee must be calculated before the facility utilisation data is updated. To ensure this is done, a check is performed in the `calculateFixedFeeAdjustment` function which ensures that the facility utilisation data report period is not the same as the current report report period which should be sufficient as a check for whether or not the facility utilisation data has been updated prematurely.
- Adds a new helper in the event handler to update the facility utilisation data
- Updates unit …

feat(FN-3267): update facility utilisation data with keying data

---

libs/common/src/change-stream/delete-many.ts
libs/common/src/change-stream/delete-one.test.ts
libs/common/src/change-stream/delete-one.ts
libs/common/src/change-stream/test-helpers/with-delete-many.api-tests.ts
libs/common/src/change-stream/test-helpers/with-delete-one.api-tests.ts
portal-api/api-tests/deal-versioning.api-test.js
portal-api/api-tests/v1/gef/facilities/facilities.delete.api-test.js

There is a bug with delete one and delete many audit logs. This is due to us using a sharded database, which is required for change streams. With mongodb 4, we cannot have a sharded database and have transactions that update multiple tables.
Remove transactions from the deletion helpers

fix(DTFS2-7316): remove transactions from deletion audit logs

---

dtfs-central-api/src/services/changeStream/setupChangeStream.ts

Cosmosdb's change stream differs from mongodb & does not allow distinction between "insert", "update", and "replace". ([See the replies here](https://learn.microsoft.com/en-us/answers/questions/356668/how-to-get-inserted-change-stream-data-use-cosmosd))
Add "update", and "replace" to deletion change stream

fix(DTFS2-7316): add update and replace to deletion change stream

---

portal-api/src/generateApp.js

When developing locally I made a typo in a route, but instead of receiving an error response due to route not found, no response was returned causing the page to hang indefinitely.
Looking into it closer the culprit was the following in portal-api `generateApp.js`:
```
app.use((error) => {
console.error(error);
});
```
Which when the request wasn't met, was being called with the request as the error param, so the request was logged, but then since we don't send a response or call next, portal was not receiving a response to it's request and the call was hanging, which doesn't seem like desired behaviour.
At first I updated to:
```
app.use((error, req, res, next) => {
console.error(error);
next(error);
});
```
Which appears to be the more correct way to add custom error handling, but on …

feat(FN-3385): remove erroneous custom error handling

---

trade-finance-manager-ui/component-tests/assertions.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table.njk
trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk

We want to display payments inside the payment details tab. This PR covers the first part of this - another PR will include displaying the user who reconciled the fee record payment group and the date it was reconciled.
Another important note is many-to-many behaviour of fee records and payments. The ticket documents that we should display many-to-many in the same way that we display one payment to many fee records ie. each payment in the many-to-many group should be displayed in the row with all the fee records in the group.
- Adds templates and component tests for the table and table row
- Updates existing tests
- Adds a new mapping function

feat(FN-2309): display payments in payment details tab

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts

There was an issue with uploading reports with a large number of new facilities, where new refers to a facility which does not have an entry in the `FacilityUtilisationData` table.
- Adds a new api test to test for a large number of facilities
- This api test was run before and after the new changes were included to replicate the existing issue and ensure it remains working in future
- Updates the event handler
- Adds a missing docstring

feat(FN-3417): add batch saving for facility utilisation data

---

dtfs-central-api/src/helpers/get-fee-record-payment-entity-groups-from-fee-record-entities.test.ts
dtfs-central-api/src/mapping/fee-record-mapper.test.ts
dtfs-central-api/src/mapping/keying-sheet-mapping.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-principal-balance-adjustment.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/get-keying-sheet-fee-payment-shares-for-fee-records.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-records-to-key.controller/helpers.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/filter-fee-record-payment-entity-groups-by-facility-id.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/get-keying-sheet-for-report-id.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/helpers/map-fee-record-payment-entity-groups-to-fee-record-payment-groups.test.ts
dtfs-central-api/test-helpers/test-data/index.ts
dtfs-central-api/test-helpers/test-data/utilisation-report.ts

It was noted on another PR that there were 14 duplicate definitions for a test helper method.
Move the `aUtilisationReport` test helper to common place and remove all duplicates.

feat(FN-2309): introduce a DRY aUtilisationReport method

---

trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js
trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js
trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js

Sending emails to the bank was not being awaited.  This is unlikely to have caused the bug 7346, but it might have done & it should be fixed anyway.
Use `Promise.all` to await sending the emails

feat(DTFS2-7346): await send email promises

---

.github/workflows/deployment.yml

Ensure `staging` environment is used when deploying a `release-*` branch.
* Conditional environment set

feat(DTFS2-7374): conditional environment set

---

e2e-tests/gef/cypress/e2e/clone/clone-gef-deal.spec.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js

The mock facilities currently access the environment variables to determine whether to add the facility end date values to the mock. In order to separate out the e2e tests with the feature flag on and off they need to be generated as a function & pass this env var in.
In the next PR the environment variable will not be accessed & the tests will be separated into two suites - ff on & ff off.
- Convert mock facilities into functions

chore(DTFS2-7392): refactor mock facilities into functions

---

dtfs-central-api/src/constants/deals.js
e2e-tests/e2e-fixtures/constants.fixture.js
gef-ui/server/constants/index.js
portal-api/src/constants/deal.js
portal/server/constants/submission-type.js
trade-finance-manager-api/src/constants/deals.js
trade-finance-manager-ui/server/constants/deal.js
utils/data-migration/constant/deal.js

In a recent PR the deal types were pulled out into libs/common. This ensures different services are using those values instead of being hardcoded each time. The implementation in this PR means I haven't had to refactor a lot of files. 
List all changes made to the codebase.

feat(DTFS2-7294): use deal type from libs/common

---

trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
trade-finance-manager-ui/server/routes/case/cancellation.ts
trade-finance-manager-ui/server/types/view-models/deal-cancellation/bank-request-date-view-model.ts
trade-finance-manager-ui/server/types/view-models/deal-cancellation/reason-for-cancelling-view-model.ts
trade-finance-manager-ui/server/types/view-models/index.ts
trade-finance-manager-ui/templates/case/cancellation/bank-request-date.njk
trade-finance-manager-ui/test-helpers/test-data/bank-request-date-view-model.ts

The PIM user needs to be able to provide the bank request date for the deal cancellation. This ticket does not include validating the values or making updates to the database
Add bank request date template
Add a new GET endpoint to render this template

feat(DTFS2-7296): add bank request date template

---

trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-effective-from-date.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-effective-from-date.ts
trade-finance-manager-ui/server/routes/case/cancellation.ts
trade-finance-manager-ui/server/types/view-models/deal-cancellation/effective-from-date-view-model.ts

The input should be validated when the user submits an effective from date, both the usual date field validation checks, and also that it shouldn't be more than 12 months in the future or more than 12 months in the past.
Add post endpoint
Add validation helper, called by post endpoint
**Note this follows identically the implementation for the bank request date in PR https://github.com/UK-Export-Finance/dtfs2/pull/3561**

feat(DTFS2-7300): add validation for effective from date

---

e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/bank-request-date.js
e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/effective-from-date.js

This adds the E2E tests for the bank request date and effective from date pages. 
List all changes made to the codebase.

feat(DTFS2-7296): add to deal cancellation e2e tests

---

dtfs-central-api/src/helpers/fee-record-matching.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.test.ts
e2e-tests/tfm/cypress/e2e/journeys/deals/deals-search.spec.js
portal-api/src/v1/users/validation/rules/current-password-must-match.test.js
portal-api/src/v1/users/validation/rules/passwords-at-least-8-characters.test.js
portal-api/src/v1/users/validation/rules/passwords-at-least-one-lowercase.test.js
portal-api/src/v1/users/validation/rules/passwords-at-least-one-number.test.js
portal-api/src/v1/users/validation/rules/passwords-at-least-one-special-character.test.js
portal-api/src/v1/users/validation/rules/passwords-at-least-one-uppercase.test.js
portal-api/src/v1/users/validation/rules/passwords-cannot-be-reused.test.js
portal-api/src/v1/users/validation/rules/passwords-must-match.test.js
trade-finance-manager-api/api-tests/v1/amendments/update-tfm-deal-amendment-completion.api-test.js
trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-bank-request-date.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/validation/validate-effective-from-date.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-summary-helper.test.ts
trade-finance-manager-ui/server/helpers/date.test.js

- Some tests were using an `expectedResult` convention, when `expected` should be used.
- Some tests were using an `matchTest` convention, when `result` should be used.
- Replace all instances of `expectedResult` with `expected`.
- Replace all instances of `matchTest` with `result`.

chore(DTFS2-7439): align some unit test naming conventions

---

.github/workflows/test.yml
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js

Fix a failing test - currently the page following the effective from date page is not implemented, and so clicking 'continue' on the effective from date page goes to the 'Not found' page which doesn't have a 'back' button.
This PR fixes this by instead returning to the effective from date page by using the URL instead of the back button
* Set the GitHub actions feature flags to boolean instead of string.

feat(DTFS2-7300): fix effective from date page test

---

e2e-tests/gef/cypress.config.js
e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-disabled/provided-facility-back-link.spec.js
e2e-tests/gef/cypress/e2e/facility/pre-submission/facility-end-date-enabled/provided-facility-back-link.spec.js
e2e-tests/gef/cypress/e2e/facility/pre-submission/provided-facility.spec.js
e2e-tests/tfm/cypress.config.js

The FFs shouldnt be in the test config.
Remove the FF env vars from the e2e test config files.
Split up the provided facility tests, since they still used the env var
Remove the deal cancellation env var

chore(DTFS2-7427): remove FFs from e2e test config

---

dtfs-central-api/package.json
e2e-tests/package.json
external-api/package.json
mongodb/Dockerfile
package-lock.json
portal-api/package.json
trade-finance-manager-api/package.json

Ensure MongoDB version matches infrastructure version.
* MongoDB Docker base image set to `4.2.0`
* Due to existing implementation NPM package `4.2.0` cannot be therefore set all the microservices `mongodb` NPM package version to `4.17.2`.

fix(DTFS2-7317): set mongodb to version range 4.17.2 and 4.2.0 on dockerfile

---

trade-finance-manager-api/api-tests/api.ts
trade-finance-manager-api/api-tests/types/test-api.ts
trade-finance-manager-api/api-tests/v1/deal-cancellation/deal-cancellation.delete.api-test.ts
trade-finance-manager-api/src/v1/__mocks__/api.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.test.ts
trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.ts
trade-finance-manager-api/src/v1/deals/routes.js

The user can click cancel during the cancel deal journey. This should delete all cancellation data in the database
- Add deleteDealCancellation to api service, calling new endpoint in dtfs-central-api (#3634)
- Add delete cancellation endpoint and controller
- Add api and unit test coverage

feat(DTFS2-7446): add delete cancellation endpoint in tfm-api

---

e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
trade-finance-manager-ui/component-tests/case/cancellation/bank-request-date.component-test.ts
trade-finance-manager-ui/component-tests/case/cancellation/effective-from-date.component-test.ts
trade-finance-manager-ui/component-tests/case/cancellation/reason-for-cancelling.component-test.ts
trade-finance-manager-ui/templates/case/cancellation/bank-request-date.njk
trade-finance-manager-ui/templates/case/cancellation/effective-from-date.njk
trade-finance-manager-ui/templates/case/cancellation/reason-for-cancelling.njk

The existing cancellation pages have cancel links redirecting to the deal summary page. These should take the user to the new cancel cancellation page
Update the cancel link hrefs
Update the e2e tests
Update the component tests
This page doesnt exist yet (Implemented by #3640)

feat(DTFS2-7448): update cancel link hrefs

---

e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/check-details.spec.js
e2e-tests/tfm/cypress/e2e/pages/deal-cancellation/check-details.js
trade-finance-manager-ui/component-tests/case/cancellation/check-details.component-test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
trade-finance-manager-ui/server/routes/case/cancellation.ts
trade-finance-manager-ui/server/types/view-models/deal-cancellation/check-details-view-model.ts
trade-finance-manager-ui/server/types/view-models/index.ts
trade-finance-manager-ui/templates/case/cancellation/check-details.njk
trade-finance-manager-ui/test-helpers/test-data/check-answers-view-model.ts

Add the check details page to the deal cancellation flow
- Add nunjucks template
- Add controller (note the proper implementation of the POST endpoint will be handled in a separate ticket)
- Add component and unit tests
- Add e2e tests

feat(DTFS2-7297): add deal cancellation check details page

---

external-api/src/cron/index.ts
external-api/src/helpers/cron.ts

Ensure documents CRON job validated
* Void job validation, useful due to unexpected behaviour and micro-service restart.
* Added document upload retries for high volume files (this is currently a workaround as re-calling document upload API once will suffice however due to an-going issue of upload with 5+ files a re-upload is being tested).

fix(DTFS2-7444): added void cron job validation

---

external-api/api-tests/v1/eStore.api-test.ts
external-api/src/cron/eStoreDocumentsCreationJob.cron.ts
external-api/src/v1/controllers/estore/eStore.controller.ts
external-api/src/v1/routes/external-apis.route.ts

eStore API calls can throw back `500` upon duplicate errors upload and/or for any other unknown errors.
* eStore document upload will check for any `500` response code which can be thrown due to duplicate documents albeit in different directories.
* Fast fail for an existing CRON job, with status code changed to `208`.
* `cron-job-logs` status update to `Failed` upon exceptional handling and to capture appropriate error message.

fix(DTFS2-7444): edge case estore exceptional handling

---

trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/bank-request-date.controller.ts
trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/cancel-cancellation.controller.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts
trade-finance-manager-ui/server/controllers/case/cancellation/helpers/get-previous-page-url.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/reason-for-cancelling.controller.post.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.test.ts
trade-finance-manager-ui/test-helpers/test-data/a-request-session.ts
trade-finance-manager-ui/test-helpers/test-data/index.ts

When a user visits certain cancellation pages, if they dont have a draft cancellation already they should be redirected to the deal cancellation page. This should only happen if they use URL navigation, or browser history, rather than clicking buttons available on screen.
- Check the deal cancellation exists when visiting:
- bank request date
- effective from date page
- cancel cancellation page
- check details page
- The reason for cancelling page is the start of the journey so does not need a draft cancellation to exist
- Update unit tests
- Use `toEqual` not `toBe` in cancellation unit tests
- Create new `aRequestSession` mock data helper and use in cancellation unit tests

feat(DTFS2-7454): redirect from cancellation pages if no cancellation in draft

---

libs/common/src/helpers/date.test.ts

As reported in the flaky test reporting slack channel, this test has failed on a few different PRs recently. It relies heavily on consistent values of `new Date()`. 
Freeze the value of `new Date()` at the start of the test and unfreeze it at the end. 

chore(DTFS2-NONE): fix flakey test

---

trade-finance-manager-ui/server/controllers/auth/auth-sso/unauthenticated-auth.controller.post-sso-redirect.test.ts
trade-finance-manager-ui/server/routes/auth/configs/index.get-unauthenticated-auth-router.test.ts
trade-finance-manager-ui/test-helpers/with-schema.tests.ts

- Somme `toBe` instances snuck in after merging [this PR](https://github.com/UK-Export-Finance/dtfs2/pull/3654)
- Replace remaining instances of `toBe` with `toEqual`

chore(DTFS2-7462): replace toBe instances with toEqual

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/generate-keying-sheet.spec.js
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk

During a recent PDC demo, two issues were spotted with the keying sheet UI:
1. All cells in the adjustment columns aren't right aligned
2. Large numbers in the adjustment cells aren't comma separated
1. Right align all cell content in the adjustment columns
2. Use recently introduced `getFormattedMonetaryValue` helper to format monetary values with commas
Screenshot showing changes:
N/A

fix(FN-3502-3503): fix keying sheet adjustments UI

---

trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.ts
trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.ts
trade-finance-manager-api/src/v1/deals/routes.js
trade-finance-manager-api/src/v1/middleware/validate-post-submit-deal-cancellation-payload.test.ts
trade-finance-manager-api/src/v1/middleware/validate-post-submit-deal-cancellation-payload.ts
trade-finance-manager-api/src/v1/middleware/validate-put-deal-cancellation-payload.ts

The user needs to be able to submit the cancellation. This endpoint provides the stub from which the database update & email can be sent from.
- Add submit cancellation endpoint with middleware validation
- Add api and unit test coverage
This endpoint doesn't actually submit the cancellation yet, but merging this early will allow DTFS2-7298 and DTFS2-7364 to be completed in parallel

feat(DTFS2-7489): create submit cancellation endpoint tfm api

---

trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js

When submitting a deal from portal to TFM, the deal is not shown in ACBS (on staging). The logs revealed an error that can be traced to not awaiting a deal update
Await the deal update in tfm-api

fix(DTFS2-7492): await tfm deal update

---

trade-finance-manager-ui/component-tests/case/cancellation/check-details.component-test.ts
trade-finance-manager-ui/server/api.js
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.get.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.post.test.ts
trade-finance-manager-ui/server/controllers/case/cancellation/check-details.controller.ts
trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.js
trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.test.js
trade-finance-manager-ui/server/nunjucks-configuration/filter-formatUnixTimestamp.ts
trade-finance-manager-ui/server/nunjucks-configuration/index.js
trade-finance-manager-ui/server/types/view-models/deal-cancellation/check-details-view-model.ts
trade-finance-manager-ui/templates/case/cancellation/check-details.njk
trade-finance-manager-ui/test-helpers/test-data/check-answers-view-model.ts

The check your details page currently does nothing when the button is pressed. It should send a submit request to tfm-api
- Send `POST` request to `cancellation/submit` in tfm-api, sending cancellation as payload.
- Refactor check-details page to take `cancellation` object, which is returned on the post request
- Take format dates in nunjucks template, not controller using new `formatUnixTimestamp` filter
- fix `delete account` typo in template

feat(DTFS2-7528): submit cancellation in tfm-ui

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/add-payment.spec.js
trade-finance-manager-ui/component-tests/utilisation-reports/add-payment.component-test.js
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts
trade-finance-manager-ui/server/types/view-models/add-payment-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/add-payment.njk
trade-finance-manager-ui/test-helpers/test-data/view-models/add-payment-view-model.ts

At present, clicking the back/cancel buttons on the add payment screen does not persist the selected fee records. This behaviour does not align with that of the 'add to an existing payment' screen.
- Update add payment screen template to accept a back link href
- Update add payment view model to accept back link href
- Update the add payment controller to use the existing back link href helper function
- Updates to the relevant unit/component/E2E tests
N/A

feat(FN-3493): persist selected records on add payment screen

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.ts

We're not saving the correct value for the initial utilisation because we are returning the value without the cover percentage applied
- Use calculate drawn amount function to calculate initial utilisation which applies cover percentage

feat(FN-3504): apply cover percentage to initial utilisation

---

.github/workflows/deployment.yml

Deployment script is unable to reference the Dockerfile from correct context.
* Working directory changed to root.
* docker build will be executed with `-f` explicit dockerfile argument.

fix(DTFS2-7440): acbs docker file reference

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-principal-balance-adjustment.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-principal-balance-adjustment.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/update-facility-utilisation-data.ts

We are currently saving the bank's reported utilisation but then comparing it to UKEF's share of utilisation for the next report period giving incorrect adjustment numbers.
- When saving utilisation to the facility utilisation data table save ukef's share of utilisation instead
Acknowledging this could do with further refactors for future maintainability since some values are being calculated multiple times rather than passed around - a separate tech debt ticket is being raised and worked on imminently by Zain which will be against main to do exactly this.

feat(FN-3504): save ukefs share of utilisation

---

.github/workflows/deployment.yml

Deployment script is unable to reference the Dockerfile from correct context.
* Working directory changed to root.
* docker build will be executed with `-f` explicit dockerfile argument.

fix(acbs-deployment): acbs dockerfile reference fix

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/view-utilisation.spec.js
e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/utilisation-table.component-test.ts
trade-finance-manager-ui/server/nunjucks-configuration/index.js
trade-finance-manager-ui/templates/utilisation-reports/_macros/utilisation-table.njk

This PR fixes an issue where the facility ids were bold on the utilisation tab and where utilisation, value and exposure were incorrectly sorted
* Changed from th to td for facilityId
* Added data-sort-value for utilisation and casted as float
* Added e2e tests
* Added removeCommasAndFloat to nunjucks config

fix(FN-3447): bold facility id and incorrect sorting fix on utilisation tab

---

azure-functions/acbs-function/Dockerfile
azure-functions/acbs-function/package.json
package-lock.json

ACBS microservice container did not initialise properly despite no errors on the logs, it was unable to accept any request and returned `404` status code. 
* Removed `libs` library due to lack of Typescript support in current Azure functions base image.
* Removed root `package-lock.json` to ensure only `acbs-function` `package.json` is included in the container and replaced `ci` with `i` (since no package-lock.json exists due to workspaces)
* Moved few test pertinent dependencies to `devDependencies`.

fix(DTFS2-7567): acbs container initilisation

---

e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/as-non-pim-user.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/bank-request-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/cancel-cancellation.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/check-details.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/effective-from-date.spec.js
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/reason-for-cancelling.spec.js
trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts
trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.ts
trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts

The tfm-api submit cancellation endpoint needs to call the dtfs-central-api endpoint.
- Add new api method `submitDealCancellation`
- Call `api.submitDealCancellation` in `DealCancellationService.submitDealCancellation`.
- Update unit test coverage

feat(DTFS2-7573): call submit cancellation in tfm-api

---

azure-functions/acbs-function/src/functions/acbs-amend-facility.js
docker-compose.yml

Locally `external-api` is unable to communicate with `acbs` microservice, the issue is due to recent `acbs` docker service update inline with other microservices however the ACBS URL has not been updated.
* Set `AZURE_ACBS_FUNCTION_URL` to `http://acbs` when executing `acbs` microservice locally using `docker compose` command. This does not have any impact of Azure RG.
* Disabled SOF `acbs-amend-facility-covenant-record` and `acbs-amend-facility-guarantee-record`.

fix(DTFS2-7440): acbs microservice docker communication

---

trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table-row.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/_macros/payment-details-table.component-test.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table-row.njk
trade-finance-manager-ui/templates/utilisation-reports/_macros/payment-details-table.njk

The payment details tab has a complciated table with grouped rows. These grouped rows mean that standard navigation with a screenreader does not convey the same meaning as the visual display. This PR improves that by making the screenreader experience line up with the order of reading of the table with the intended visual flow.
- Hide sub rows of grouped rows from screenreaders
- Hide facility id and exporter columns from screenreaders
- Add hidden column containing the facility id and exporter in a screenreader friendly format

feat(FN-3328): screenreader ux improvements to payment details

---

trade-finance-manager-ui/component-tests/utilisation-reports/_macros/utilisation-table.component-test.ts
trade-finance-manager-ui/templates/utilisation-reports/_macros/utilisation-table.njk

Update utilisation tab headers to new wording.
Renamed headers should be: 
- Facility ID
- Exporter
- Base currency
- Facility value
- Bank utilisation
- UKEF cover
- UKEF exposure
- Fees accrued for the period
- Fees payable to UKEF for the period (reported currency)

feat(FN-3548): update utilisation tab headers

---

trade-finance-manager-api/src/v1/rest-mappings/filters/filterTasks.api-test.js
trade-finance-manager-api/src/v1/rest-mappings/filters/filterTasks.js
trade-finance-manager-ui/server/controllers/helpers/tasks.helper.js

A facility amendment generates various tasks for `PIM`, when no such tasks are available using `Filter results` on TFM can throw `502` due to the lack of exceptional handling and validation.
* Added validation across both the TFM microservices `ui` and `api` to ensure empty tasks are validated.
* Improved test coverage.

fix(DTFS2-7576): facility amendment empty tasks graceful handle

---

azure-functions/acbs-function/Dockerfile
azure-functions/acbs-function/README.md

Durable functions were not being instantiated and thus receiving `404` on `external-api` upon calling any ACBS orchestrated function endpoint.
* Set `WORKDIR` and environment variable `AzureWebJobsScriptRoot` to `/home/site/wwwroot`.
* Added documentation regarding working directory to `README.md`.

fix(DTFS2-7567): working directory for azure functions

---

dtfs-central-api/src/repositories/tfm-facilities-repo/aggregate-pipelines/all-facilities-and-facility-count.ts
e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/submit-deal-cancellation-in-past.spec.js
trade-finance-manager-ui/component-tests/facilities/_macros/facilities-table.component-test.js
trade-finance-manager-ui/templates/facilities/_macros/facilities-table.njk

When a deal is cancelled, it should display the updated facility stage on the 'All facilities' page. 
- Return the TfmFacilityStage in the `allFacilities` api call 
- Display this in the front end if it exists

feat(DTFS2-7469): display 'Risk Expired' on All Facilities page

---

e2e-tests/portal/cypress/e2e/journeys/maker-facilities/MIA-accepted-deal-status-maker-cannot-resubmit-until-confirmed-all-issued-facilities-cover-start-date/MIA-deal-with-accepted-status-issued-facilities.js

This PR fixes an issue in MIA-deal-with-accepted-status-issued-facilities.js where the incorrect date constant was used
* added new constants for todayDay and todayYear and used them for requestedCoverStartDate

fix(DTFS2-7593): fix incorrect requestedCoverStartDate dates in e2e facility

---

e2e-tests/portal/cypress/e2e/journeys/maker-loan/loan-form-values.js
trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts

We have a unit test that is failing today at the start of the month, due to checking for `dd` date instead of a `d` date. 
Separately, we have an E2E test failing for the opposite reason.
I've fixed both in this PR
Replace `dd` with `d` in the unit test, and replace 'd' with 'dd' in the e2e test

fix(DTFS2-7594): fix failing dates tests

---

libs/common/src/constants/portal/facility-status.ts
libs/common/src/constants/portal/index.ts
portal/component-tests/contract/components/bond-transactions-table.component-test.js
portal/server/constants/status.js
portal/server/helpers/dealFormsCompleted.js
portal/server/helpers/dealFormsCompleted.test.js
portal/server/helpers/isFacilityComplete.test.js

Facility Status constants need to be accessible in all services in order to update when cancelling
- add `FACILITY_STATUS` constant to libs common
- refactor portal uses of this constant to fetch from libs/common
- Theres a suspicious lack of this constant being used in portal, I did catch one place using the wrong constant but I expect there's lots more facility statuses being set as `DEAL_STATUS.INCOMPLETE`. I've not searched in depth for these & we should look to move these across iteratively when we find them

feat(DTFS2-7612): commonise facility status constant

---

dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js
dtfs-central-api/src/v1/controllers/portal/facility/delete-facility.controller.ts
dtfs-central-api/src/v1/controllers/portal/facility/get-facility.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js

The `findOneFacility` function was returning `Facility`, `null` or `{ status: 400, message: 'Invalid Facility Id' }`. This makes it hard to use with new functions. `updateFacilityStatus` will be needed to update the facility status after cancellation 
- Refactor the `findOneFacility` to throw `InvalidFacilityIdError` or `FacilityNotFoundError` to be handled in the controller. Remove `callback` parameter since this was unused
- Refactor the controllers that call this function to wrap in a try/catch block & handle the `ApiErrors` properly
- Refactor the `updateFacilityStatus` function to not have `existingFacility` passed in, and instead call `findOneFacility`. Throw `ApiError`s to be handled by the controlle

feat(DTFS2-7612): refactor get facility controller to have consistent return type

---

gef-ui/server/utils/deal-helpers.test.js
gef-ui/server/utils/display-items.js
gef-ui/server/utils/display-items.test.js
gef-ui/server/utils/helpers.js
gef-ui/server/utils/helpers.test.js

GEF deals have not historically had a deal status. The new `risk expired` status needs to be rendered in the frontend
- modify `facilityItems` function to get the facility status and, when it exists, render it instead of `Issued` or `unissued`
- Hide `Change` links when deal has been cancelled
- Use commonised `DEAL_STATUS` constant in `helpers.js` file

feat(DTFS2-7598): display risk expired facility status in GEF ui

---

dtfs-central-api/api-tests/v1/tfm/deal-cancellation/tfm-submit-deal-cancellation-post.api-test.ts
dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.scheduleDealCancellation.test.ts
dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.submitDealCancellation.test.ts
dtfs-central-api/src/repositories/tfm-deals-repo/tfm-deal-cancellation.repo.ts
dtfs-central-api/src/services/portal/facility.service.ts
dtfs-central-api/src/services/portal/facility.service.update-status.test.ts
dtfs-central-api/src/services/tfm/deal-cancellation.service.getTfmDealCancellationResponse.test.ts
dtfs-central-api/src/services/tfm/deal-cancellation.service.processScheduledCancellation.test.ts
dtfs-central-api/src/services/tfm/deal-cancellation.service.submitDealCancellation.test.ts
dtfs-central-api/src/services/tfm/deal-cancellation.service.ts
dtfs-central-api/src/v1/controllers/portal/facility/update-facility-status.controller.js
dtfs-central-api/src/v1/controllers/portal/gef-facility/update-facility.controller.js
dtfs-central-api/test-helpers/test-data/tfm-facility.ts
libs/common/src/types/portal/facility-status.ts
libs/common/src/types/portal/index.ts
libs/common/src/types/tfm-deal-cancellation.ts
trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts
trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.test.ts
trade-finance-manager-api/src/v1/services/deal-cancellation/deal-cancellation.service.ts

When a deal is cancelled in tfm, the portal facilities should show `risk expired`
- Modify the repo return type to send facilities
- Add new facilities service to update BSS and GEF facilities
- Update facilities in deal cancellation service
BSS/EWCS Facilities
- Add `FacilityStatus` type
- Modify `TfmDealCancellationResponse` type back to a previous version & update controllers/tests to handle this
This PR doesnt cover front end changes, gef-ui will need some refactoring to render the new status

feat(DTFS2-7612): update portal facility status to risk expired

---

azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
azure-functions/acbs-function/src/functions/activity-get-facility-master.js

Ensure `facilityIdentifier` is used as a standard name for facility ID.

fix(DTFS2-6616): variable consistency

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-keying-data.api-test.ts
dtfs-central-api/api-tests/v1/utilisation-reports/post-upload-utilisation-report.api-test.ts
dtfs-central-api/src/helpers/get-keying-sheet-calculation-facility-values.test.ts
dtfs-central-api/src/helpers/get-keying-sheet-calculation-facility-values.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/generate-keying-data/generate-keying-data.event-handler.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee-adjustment.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/helpers/calculate-fixed-fee.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-fixed-fee.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/calculate-initial-utilisation-and-fixed-fee.ts
dtfs-central-api/src/types/tfm/tfm-facility.ts
dtfs-central-api/test-helpers/test-data/tfm-facility.ts
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-fixed-fee-adjustment-with-amendments.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/generate-keying-sheet.spec.js

Fixed fee adjustments rely on cover end dates existing which we discovered is not the case for all facilities banks are reporting on. This was preventing upload of reports and complete use of the utilisation report service for certain banks. However, the fixed fee calculation has not been finalised and so is not being used by PDC.
In this PR we disable fixed fee completely. Removing any dependency on facility values other than 'value' and 'coverPercentage' from the utilisation reporting service. This should make the service usable for all banks, just without the fixed fee functionality. Fixed fee adjustments will be reimplemented when the calculation is finalised with support for facilities with no cover end date.
- Remove usages of facility fields other than 'coverPercentage' and 'value' …

feat(FN-3638): turn off fixed fee adjustments

---

dtfs-central-api/api-tests/v1/utilisation-reports/post-validate-utilisation-report-data.api-test.ts
dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.test.ts
dtfs-central-api/src/services/utilisation-report-data-validator/utilisation-report-cell-validators/generate-ukef-facility-id-error.ts
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-monthly-utilisation-report.spec.js
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/utilisation-report-upload/can-upload-quarterly-utilisation-report.spec.js
e2e-tests/portal/cypress/fixtures/mockUtilisationReportDetails.js
e2e-tests/ukef/cypress/fixtures/tfm-facility.js

During bank report upload, facility types should be restricted to GEF facilities as we are unable to store information such as 'value' and 'coverPercentage' on other facility types (e.g., EWCS facilities).
The valid facility types, with this information, are `CASH` and `CONTINGENT` - together these make up the `GEF_FACILITY_TYPE` const in `libs/common/src/constants/facility-type.ts`
- Modified facility ID existence check to require that the facility be a GEF facility.
- Adapted error messaging for this case in line with designer preference.
- Added API tests to check the different types of facility.
- Adapted E2E tests to match new messaging and ensure an error message is displayed for a stored EWCS facility.
N/A

feat(FN-3640): require bank report facilities be GEF facilities

---

dtfs-central-api/src/constants/batch-saving.ts
dtfs-central-api/src/constants/index.ts
dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts
dtfs-central-api/src/helpers/execute-with-sql-transaction.ts
dtfs-central-api/src/helpers/get-previous-report-period.test.ts
dtfs-central-api/src/helpers/get-previous-report-period.ts
dtfs-central-api/src/services/facility-utilisation-data/facility-utilisation-data.service.test.ts
dtfs-central-api/src/services/facility-utilisation-data/facility-utilisation-data.service.ts
dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-fixed-fee.test.ts
dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-fixed-fee.ts
dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-utilisation-and-fixed-fee.test.ts
dtfs-central-api/src/services/facility-utilisation-data/helpers/calculate-initial-utilisation-and-fixed-fee.ts
dtfs-central-api/src/services/facility-utilisation-data/helpers/index.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/index.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.test.ts
dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/report-uploaded/report-uploaded.event-handler.ts

When errors were being thrown as part of the report upload on production the logs were not displaying the originating error because we were running lots of queries in parallel which caused rolling the transaction back to fail and so the surfaced error message was a generic transaction error message.
In this PR we resolve that by adding in an additional console.error of the thrown error so we can view the original error if rolling back the transaction ever fails. As well as serialising the facility utilisation data initialisation so that if an error is thrown in a similar way again the transaction will roll back happily.
To ensure serialising the queries does not have a performance hit I timed the implementation before and after these changes for the facility utilisation data …

fix(FN-3641): improve report upload reliability

---

.github/workflows/feature_deploy.yml

Release 2.6.0 needs to be tested on feature environment. Raising a separate PR on main to prevent any overwrites from merges to main.
- Switch feature deploy to be for the release-2.6.0 branch

chore(FN): enable release-2.6.0 deployments to feature

---

trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk

The numeric and no-border class were not applying correctly in some cases where they should be present due to a missing space between the class names.
- Add a space before the no-border class name

feat(FN-3567): fix no-border style not applying to reported fees

---

dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.test.ts
dtfs-central-api/src/services/state-machines/fee-record/event-handlers/payment-deleted/payment-deleted.event-handler.ts
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/delete-payment.spec.js

Bug description: If a fee has reported payments less than the tolerance then once a payment was added, an error was being thrown when trying to delete the payment, since there was a check for matching that was not updated when tolerance's were introduced.
This PR fixes this by removing the check and always setting the status of a fee to TO_DO if it has no payments after a payment deletion.
- Remove incorrect check for error state that is actually a valid state in the system.

fix(FN-3631): enable deletion of payments against fees below tolerance

---

e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js

Unissued facilities e2e tests are failing because they arent calculating three months after the submission date correctly.
- Update threeDaysAgoPlusThreeMonths constant to calculate the date in the correct order
- Add more self-documentation to the e2e tests by assigning `deadlineForIssuing` constants

chore(DTFS2-7680): update threeDaysAgoPlusThreeMonths date constant

---

azure-functions/acbs-function/src/functions/acbs-amend-facility.js
e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-disabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/facility-end-date-enabled/unissued-facility-to-issued-cover-start-date-AIN.spec.js
e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js
portal/templates/_partials/before-you-start.njk
utils/mock-data-loader/banks/index.js

Add `ABC` to the portal and revert facility amendment guarantee and covenant record (#3918)
* Added `ABC` bank.
* Reverted commit [79c2a736c17bac27cb8e4529c96158cba28324d0](https://github.com/UK-Export-Finance/dtfs2/commit/79c2a736c17bac27cb8e4529c96158cba28324d0)
* Added https://github.com/UK-Export-Finance/dtfs2/pull/4015/commits for faulty failing tests resolution.

feat(DTFS2-7668): add bank abc to portal

---

.github/workflows/test.yml

A test was being skipped on the pipeline due to incorrect config in the test.yml file
Fix the config in the test.yml file to pick up all the tests when the deal cancellation FF is enabled

fix(DTFS2-7647): add missing test to yml file

---

e2e-tests/gef/cypress/e2e/page-header.spec.js
e2e-tests/gef/cypress/e2e/pages/page-banner.js
e2e-tests/portal/cypress/e2e/journeys/portal-header.spec.js
e2e-tests/portal/cypress/e2e/pages/header.js
e2e-tests/tfm/cypress/e2e/journeys/login/login.spec.js
e2e-tests/tfm/cypress/e2e/partials/header.js
gef-ui/templates/includes/beta-banner.njk
gef-ui/templates/partials/application-activity.njk
gef-ui/templates/partials/application-preview.njk
portal/templates/_partials/beta-banner.njk
trade-finance-manager-ui/templates/_partials/beta-banner.njk

- GOV design library has been updated.
- The phase banner (in all UI microservices) have incorrect "beta" copy. It should render "Beta" instead of "beta".
- Update nunjucks instances of "beta".
- Update E2E tests.

fix(DTFS2-7684): gov design library - update beta phase banner copy

---

azure-functions/acbs-function/src/functions/acbs-amend-facility-master-record.js
azure-functions/acbs-function/src/functions/acbs-issue-facility.js
azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js
azure-functions/acbs-function/src/functions/activity-get-facility-master.js

Facility issuance and amendments are failing due to invalid property name and argument type being supplied to DAF pertinent to extracting facility master record and facility loan identifier.
* Corrected durable activity function argument as an object.
* Removed object destructuring aliasing, since `facilityIdentifier` is the supplied property name.

fix(DTFS2-7694): argument as an object

---

.github/workflows/deployment.yml
.github/workflows/test.yml

Ensure manual deployment to `dev` can also be triggered alongside with automated CRON enabled deployment.
* Added `push` directive for `dev` branch.
* Minor documentation improvement.

fix(DTFS2-7616): manual dev deployment

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-disabled/record-correction-tab-not-visible.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/record-correction-history-no-corrections.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/report-reconciliation/bank-utilisation-report-page.spec.js
trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk

This PR hides the record correction tab behind a feature flag
* Moved items array for tabs to its own set in nunjucks
* Added if for feature flag and pushed record correction tab to that array
* Updated and added e2e tests

feat(FN-3612): hide record correction tab behind feature flag

---

e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/AIN-pending-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/MIN-pending-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-issue-facility.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/AIN-deal-pending-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/MIN-deal-pending-cancellation-updates-portal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-issue-facility.spec.js
libs/common/src/constants/tfm/index.ts
libs/common/src/constants/tfm/url.ts

The deal cancellation tests need to visit the TFM url before logging in
add `cy.vist(TFM_URL)` to all deal cancellation tests 
- remove unnecessary `url.ts` file from libs/common

chore(DTFS2-7717): visit TFM url in deal cancellation tests

---

dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-get.api-test.ts
dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-patch.api-test.ts
dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-put.api-test.ts
dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.ts
dtfs-central-api/src/repositories/tfm-facilities-repo/tfm-facilities.repo.updatePortalFacilityAmendmentByAmendmentId.test.ts
dtfs-central-api/src/services/portal/facility-amendment.service.ts
dtfs-central-api/src/services/portal/facility-amendment.updatePortalFacilityAmendment.service.test.ts
dtfs-central-api/src/services/portal/facility-amendment.upsertPortalFacilityAmendmentDraft.service.test.ts
dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.ts
dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment.controller.test.ts
dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment.controller.ts
dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-payload.test.ts
dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-payload.ts
dtfs-central-api/src/v1/routes/portal-routes.js
libs/common/src/errors/amendment-not-found.error.test.ts
libs/common/src/errors/amendment-not-found.error.ts
libs/common/src/errors/index.ts
libs/common/src/errors/invalid-audit-details.error.ts
libs/common/src/helpers/date.ts
libs/common/src/types/portal/index.ts

When the user inputs each stage of the amendments flow, the values should be updated in a PATCH request
- add repo, service and controllers to handle update request
- add unit and api tests
- Add `AmendmentNotFound` error

feat(DTFS2-7689): add PATCH portal amendment endpoint to dtfs-central-api

---

.github/dependabot.yml

This PR fixes an incorrect field in dependabot.yml
* Changed from directory to directories in dependabot.yml for npm

chore(DTFS2-7708): fixed incorrect dependabot directory name

---

trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts

One of the "find reports by year" unit test assertions has a fixed report period year value, whilst the report period used is dependent on the current year.
This led the test to fail when the current year changed from the fixed string in the assertion (2024):
```
***     "formattedReportPeriod": "January 2024",
+     "formattedReportPeriod": "January 2025",
```
Related failing runs:
https://github.com/UK-Export-Finance/dtfs2/actions/runs/12584970329/job/35110286115?pr=4089#logs
- Fixed the year used for the report period
N/A

fix(FN-3731): fix assertion dependent on current year

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts
trade-finance-manager-ui/server/types/view-models/record-correction/record-correction-request-information-view-model.ts
trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
trade-finance-manager-ui/test-helpers/test-data/view-models/record-corrections/record-correction-request-information-view-model.ts

Email addresses on the "check the information" screen of the PDC "create fee record correction request" journey are comma-separated and break on dashes.
A comment in demo highlighted that is difficult to read when there are several email addresses.
Further, the key should have the suffix `(es)` to handle the case of multiple emails.
- `(es)` suffix added to emails key
- Emails separated with a comma followed by a new line, breaking on any character when the containers max width is reached
- This is the designers preference
N/A

feat(FN-3578): improve email format for pdc correction request

---

portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.test.ts
portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/helpers.ts

We noticed that if a user entered zero as the utilisation or reported fee amount for a correction then went to the review page and then went back the field would be empty as if they had not entered a value.
- Add handling for zero as a possible value for a persisted monetary correction value.

feat(FN-3689): handle saved values of zero on correction form

---

dtfs-central-api/api-tests/helpers/custom-error-response.ts
dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction-transient-form-data.api-test.ts
dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction.api-test.ts
dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports-reconciliation-summary.api-test.ts
dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-reports.api-test.ts
dtfs-central-api/src/repositories/fee-record-correction-repo/fee-record-correction.repo.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.ts
dtfs-central-api/src/v1/routes/bank-routes.js
dtfs-central-api/src/v1/routes/middleware/payload-validation/index.ts
dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-payload.test.ts
dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-put-fee-record-correction-payload.ts
portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/get-fee-record-correction-transient-form-data.api-test.js
portal-api/api-tests/v1/utilisation-report-service/fee-record-corrections/save-fee-record-correction.api-test.js
portal-api/src/v1/api-response-types/index.ts
portal-api/src/v1/api-response-types/save-fee-record-correction-response-body.ts
portal-api/src/v1/api.js
portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction.controller.test.ts
portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/fee-record-correction.controller.ts
portal-api/src/v1/controllers/utilisation-report-service/fee-record-corrections/index.ts
portal-api/src/v1/routes.js
portal/server/api-response-types/index.ts
portal/server/api-response-types/save-fee-record-correction-response-body.ts
portal/server/api.js
portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.test.ts
portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.ts
portal/server/controllers/utilisation-report-service/record-correction/index.ts
portal/server/routes/utilisation-report-service/record-correction/index.js

In a previous PR I added the correction sent page and the GET controller for it.
In this PR we add the save correction route for when the bank submits a correction and call it when the confirm and send button is clicked on the review page. The endpoint in central-api doesn't actually save the correction as that falls to another ticket, instead it just returns the payment officer emails and the report period and then on success in portal we redirect to the correction sent page.
- Add PUT record correction route (which will be added to in FN-3675 to save the correction details the bank provides against the correction)
- Redirect to the correction sent page when api request to save correction is successful
- e2e-tests to follow in a separate PR when FN-3688 has been progressed further

feat(FN-3670): redirect to correction sent page on submission

---

libs/common/src/test-helpers/fee-record-correction-review-information.ts
portal/component-tests/utilisation-report-service/record-correction/check-the-information.component-test.js
portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.test.ts
portal/server/controllers/utilisation-report-service/record-correction/check-the-information/index.ts
portal/server/types/view-models/record-correction/utilisation-report-correction-information.ts
portal/templates/utilisation-report-service/record-correction/check-the-information.njk
portal/test-helpers/test-data/view-models/record-corrections/utilisation-report-correction-information-view-model.ts

The reported fees on the bank correction "check the information" screen needs to be formatted as a monetary value. At present, the raw number will be rendered.
Examples:
- Before: `123`, After: `123.00`
- Before: `1234.56`, After: `1,234.56`
- Updated view model "amount" type to string
- Called monetary value formatting helper in the controller
N/A

feat(FN-3669): map reported fees amount to monetary value

---

e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/provide-correction.spec.js
e2e-tests/portal/cypress/e2e/pages/index.js
e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/reviewCorrection.js

When the work for persistence was done the e2e-tests were blocked on other tickets to allow us to test the user flow. That work has now progressed enough.
- Add an e2e-test to cover the scenario where a user save and review the correction but then decides to go back and change them from the review screen

feat(FN-3689): add e2e-tests for persistence of correction form values

---

dtfs-central-api/api-tests/v1/utilisation-reports/fee-record-corrections/put-fee-record-correction.api-test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.test.ts
dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction.controller/index.ts
e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/provide-correction.spec.js
portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.test.ts
portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts

When a user abandons the correction journey without clicking cancel they might start the journey again with form data already saved. When they start a new journey we therefore need to make an api call to delete any old saved data.
Also in this PR, add deletion of correction transient form data to the endpoint that will be responsible for saving the values and completes the journey so any unused old data is not hanging around.
- Add repo delete call to the PUT fee record correction endpoint
- Add call to the transient form data delete endpoint when user is starting the provide correction journey anew
- Add e2e-tests for the changes in this PR and the initial PR for this ticket which covers deleting the form data when the user clicks cancel on the review page

feat(FN-3736): remaining delete transient form data scenarios

---

gef-ui/api-tests/amendments/eligibility.get.api-test.ts
gef-ui/component-tests/partials/amendments/eligibility.component-test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.ts
gef-ui/server/routes/facilities/amendments/index.ts
gef-ui/server/types/view-models/amendments/eligibility-view-model.ts
gef-ui/templates/_macros/amendments/eligibility-criterion.njk
gef-ui/templates/partials/amendments/eligibility.njk

This page adds the nunjucks template and controller for the Eligibility page. 
⚠️We are not yet fetching the Eligibility criteria from the database - this will be added as a seperate PR. I've set this page up so that when we have set up the endpoints to fetch it, it will be quick to add to the controller and pass into the nunjucks template. 
- Add nunjucks page and controller
- Add tests
Here is a screenshot of what the page looks like when you pass in eligibility criteria (hardcoded in the screenshot). In the PR we are not passing in any ECs for now, so it will be rendered as a blank page for now. 
What the template _will_ look like when we pass in ECs of the form e.g.:
```
criteria = [
{ id: 1, description: 'Test first criteria' },
{ id: 2, description: 'Test second criteria' },
{ id: …
```

feat(DTFS2-7498): add amendments eligibility page template

---

e2e-tests/tfm/cypress/e2e/journeys/deal-cancellation/gef/cancel-deal-with-amendment-in-progress.spec.js
libs/common/src/types/mongo-db-models/tfm-deals.ts
trade-finance-manager-ui/server/controllers/case/activity/index.js
trade-finance-manager-ui/server/controllers/case/index.js
trade-finance-manager-ui/server/controllers/case/index.test.js
trade-finance-manager-ui/server/controllers/case/parties/index.js
trade-finance-manager-ui/server/controllers/case/underwriting/index.js
trade-finance-manager-ui/server/controllers/helpers/amendments.helper.filterAmendmentsByInProgress.test.js
trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js
trade-finance-manager-ui/server/controllers/helpers/dealsAndFacilities.helper.deals.test.js
trade-finance-manager-ui/server/controllers/helpers/overrideDealsIfAmendmentsInProgress.helper.js
trade-finance-manager-ui/server/controllers/helpers/overrideDealsIfAmendmentsInProgress.helper.test.js

When the deal has an amendment in progress and is cancelled, the deal stage should be cancelled
- Refactor `filterAmendmentsByInProgress` to check if the deal stage is cancelled
I've tried to commonise the deal stage overriding logic and  as such have made some changes to the behaviour. Please check if any of these should remain as they were

feat(DTFS2-7739): display cancelled deal status when amendment in progress

---

e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/correction-sent.spec.js
e2e-tests/portal/cypress/e2e/pages/index.js
e2e-tests/portal/cypress/e2e/pages/utilisation-report-service/record-corrections/correctionSent.js
portal/component-tests/utilisation-report-service/confirmation.component-test.js
portal/templates/utilisation-report-service/_macros/email-confirmation-list.njk
portal/templates/utilisation-report-service/record-correction/correction-sent.njk

The correction sent page was added before there was a complete journey for the user to get to the page. This PR adds those e2e-tests now that the user journey is complete enough for them.
- Add e2e-tests for the correction sent page
- Update data-cy that was just 'paragraph' to a more descriptive name

feat(FN-3670): correction sent page e2e-tests

---

libs/common/src/helpers/date.test.ts
libs/common/src/helpers/date.ts
portal/api-tests/static-routes.api-test.js
portal/server/routes/static.js

`security.txt` expiry date should be set to 1 year in future to conform with [RFC-9116](https://www.rfc-editor.org/rfc/rfc9116).
* Added `addYear` helper function.
* Updated API test case assertion.
* Added `getEpochMs` helper function to get EPOCH with ms.
* Added unit test cases.

fix(DTFS2-7771): added date helper functions

---

e2e-tests/portal/cypress/e2e/journeys/payment-report-officer/record-corrections/feature-flag-enabled/provide-correction.spec.js
portal/templates/utilisation-report-service/record-correction/check-the-information.njk

The designs were updated to include a back link on the record correction review page.
- Add back link linking to previous page to record correction review page.
- Add e2e-test.

feat(FN-3689): add back link to record correction review page

---

gef-ui/api-tests/amendments/eligibility.post.api-test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/get-eligibility.ts
gef-ui/server/controllers/amendments/eligibility-criteria/post-eligibility.test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/post-eligibility.ts
gef-ui/server/controllers/amendments/eligibility-criteria/validation.test.ts
gef-ui/server/controllers/amendments/eligibility-criteria/validation.ts
gef-ui/server/controllers/amendments/helpers/eligibility.helper.parseEligibilityResponse.test.ts
gef-ui/server/controllers/amendments/helpers/eligibility.helper.parseStringAsBoolean.test.ts
gef-ui/server/controllers/amendments/helpers/eligibility.helper.ts
gef-ui/server/routes/facilities/amendments/index.ts

Handle a user presseing 'continue' on the eligibility page - either displaying validation errors or posting ot the amendment. 
**E2E tests will be added as a seperate PR**
- Parse the radio check box result from the nunjucks file
- Validate the response and display error messages if any missing criteria
- Update the amendment if a valid selection is submitted

feat(DTFS2-7498): add eligibility post controller

---

external-api/api-tests/v1/party-db.api-test.ts
external-api/src/v1/controllers/party-db.controller.ts
external-api/src/v1/routes/external-apis.route.ts
trade-finance-manager-api/api-tests/v1/deals/deals-party-db.api-test.js
trade-finance-manager-api/src/v1/api.js
trade-finance-manager-api/src/v1/controllers/deal.party-db.js
trade-finance-manager-api/src/v1/controllers/deal.party-db.test.js

In discussion with Risk teams, they wanted Risk data to be added to newly created customers in Salesforce.
The APIM side will default Risk rating at B+ and Loss given default at 50%, and the DTFS side will pass Probability of Default through to APIM to be set on the new record.
Adds probability of default (set to the exporter's value) to the data sent to the new APIM customer creation endpoint.

feat(FN-3664): add risk data to created customers

---

dtfs-central-api/src/v1/swagger-definitions/portal/portal-amendments.js
e2e-tests/e2e-fixtures/dateConstants.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js

This PR fixes the YAMLSemanticError: Map keys must be unique; "createdBy" is repeated at line 5, column 7 error
* Remove duplicated createdBy definition

fix(DTFS2-7798): remove duplicate createdBy in portal-amendments swagger definitions

---

trade-finance-manager-api/src/v1/controllers/acbs.controller.js

A facility issuance is being failed on production due to lack of facility.tfm.acbs object existence check. This happens due to failure to create the above objecte when a deal and its associated facilities have been created in ACBS and reconcilled with TFM.
* Updated property name to `facilityIdentifier`.
* Additional test cases and mocks have been pushed in this [commit](https://github.com/UK-Export-Finance/dtfs2/pull/4175/commits/9c542f26a504e6a980c994fef7c0ba3d353cb645).

fix(DTFS2-7804): updated property name to facility identifier

---

e2e-tests/gef/cypress/e2e/pages/amendments/check-your-answers.js
e2e-tests/gef/cypress/e2e/pages/amendments/submitted-for-checking.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-both-cover-end-date-and-facility-value.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-BRD-journey.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-cover-end-date-with-FED-journey.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/change-facility-value-journey.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/check-your-answers.spec.js
gef-ui/component-tests/_macros/amendment-summary-list.component-test.ts
gef-ui/component-tests/partials/amendments/check-your-answers.component-test.ts
gef-ui/templates/_macros/amendments/amendment-summary-list.njk

Updates e2e tests to cover check your answers and submitted for checking pages
- Add Check your answers and Submitted pages to amendments journey e2e tests
- Add Check your answers page e2e test
- Update component tests with changed `data-cy`

feat(DTFS2-7797): add check your answers e2e tests

---

e2e-tests/e2e-fixtures/mock-gef-facilities.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js
e2e-tests/gef/cypress/e2e/facility/review-ukef-approval/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-bank-review-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-all-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-issued-to-unissued-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-facility-end-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-change-from-preview-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facility-to-issued-cover-start-date-AIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/about-unissued-facility.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-all-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-submit-ukef-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facilities-change-to-issued-3-months-after-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-MIN.spec.js
e2e-tests/gef/cypress/e2e/facility/unissued-facilities/MIN/unissued-facility-change-from-preview-specialIssuedPermission-MIN.spec.js
e2e-tests/gef/cypress/fixtures/mocks/mock-deals.js
e2e-tests/gef/cypress/support/commands/api.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/application-details.spec.js
gef-ui/server/controllers/application-details/index.js
gef-ui/server/controllers/application-details/index.test.js

Show the make a change button only if there isn't an amendment already underway on the deal. 
- Added the UI change for this ticket (showing / hiding the amendment button based on if an amendment is underway currently or not). This change is in the one file: `gef-ui/server/controllers/application-details/index.js`. A unit test has been added for this as has an E2E test (the `application-details` E2E test file)
- Separately, due to reasons outlined on the 3 amigos channel, this small changed caused approx 10 existing GEF tests to fail as they weren't properly submitting the deal to TFM at the start of the tests causing dtfs-central-api to crash. I've fixed this in this PR (the status being updated in the `before` hooks was previously incorrect)

feat(DTFS2-7494): add ui logic to show or hide make a change button

---

e2e-tests/portal/cypress/e2e/pages/cloneDeal.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/BSS-EWCS/deal-cancellation-maker-unable-clone-deal.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/deal-cancellation/gef/deal-cancellation-maker-unable-clone-deal.spec.js
gef-ui/component-tests/includes/application-details/applicationReferenceAndActions.component-test.js
gef-ui/server/controllers/application-details/index.js
gef-ui/server/controllers/application-details/index.test.js
gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk
portal/component-tests/contract/components/clone-deal-link.component-test.js
portal/server/routes/contract/index.js
portal/templates/contract/components/clone-deal-link.njk
portal/templates/contract/contract-view.njk

This PR  is about stopping the Maker from cloning a cancelled/pending cancellation deal. 
Gef deal : add flags to hide the clone button if the deal is either cancelled or pending cancellation
BSS or EWCS deal : add flags to hide the clone button if the deal is either cancelled or pending cancellation
add e2e test coverage

fix(DTFS2-7820): cancel deal hide clone button

---

e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-keyword.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-notice-type.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filter-by/dashboard-deals-filter-by-status.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-filters.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-main-container-filter-remove.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-deals/filters/dashboard-deals-panel-filter-remove.spec.js
e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/filters/dashboard-facilities-filters.spec.js

BSS/EWCS E2E tests were creating deals by calling the API directly.
We want to prevent specific user roles (like maker, checker), from calling Portal API directly.
This PR updates all E2E tests that create individual BSS/EWCS deals, to be created via the UI, mimicking a true user journey.
Create createBssEwcsDeal cypress command.
Update E2E tests

chore(7431): replace insertOneDeal with createBssEwcs function

---

e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-check-the-information.spec.js
e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/fee-record-correction/feature-flag-enabled/create-fee-record-correction-form.spec.js
trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/check-the-information.component-test.ts
trade-finance-manager-ui/component-tests/utilisation-reports/record-corrections/create-record-correction-request.component-test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/cancel-record-correction-request/index.test.ts
trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/cancel-record-correction-request/index.ts
trade-finance-manager-ui/server/routes/utilisation-reports/index.ts
trade-finance-manager-ui/templates/utilisation-reports/record-corrections/check-the-information.njk
trade-finance-manager-ui/templates/utilisation-reports/record-corrections/create-record-correction-request.njk

This PR fixes the record correction cancel link which was a button but should be a link
* Changed create-record-correction-request and check-the-information templates to have a link instead of a button
* Changed post cancel route to a get (as pressing a link triggers a get request)
* Updated and added to e2e tests

fix(DTFS2-7917): record correction - cancel link

---

.github/workflows/deployment.yml
.github/workflows/purge.yml
.github/workflows/release.yml
e2e-tests/portal/cypress/e2e/journeys/maker/before-you-start/mandatory-criteria.spec.js
e2e-tests/portal/cypress/e2e/journeys/maker/bss-mandatory-criteria/bss-mandatory-criteria.spec.js
e2e-tests/portal/cypress/e2e/pages/beforeYouStart.js
libs/common/src/helpers/generate-mandatory-criteria.test.ts
libs/common/src/helpers/generate-mandatory-criteria.ts
libs/common/src/helpers/index.ts
libs/common/src/helpers/strip-html.test.ts
libs/common/src/helpers/strip-html.ts
libs/common/src/types/index.ts
libs/common/src/types/mandatory-criteria.ts
portal/component-tests/_macros/mandatory-criteria-box.test.js
portal/component-tests/assertions.js
portal/component-tests/contract/contract-submission-details.component-test.js
portal/templates/_macros/mandatory-criteria-box.njk
portal/templates/contract/contract-submission-details.njk
trade-finance-manager-api/src/v1/helpers/generate-mandatory-criteria-string.js

Mandatory criteria is being displayed as a HTML on check details page for `BSS/EWCS` and in an email.
* Added a second argument `text` to the macro to ascertain HTML render.
* Added component test cases.
* Added additional Cypress E2E tests cases.
* Introduced a new helper function `generateMandatoryCriteria` to render MC for an email, with an additional support to strip out HTML.
* 
* Improved test assertions.
* Added `toContain` to component test assertion.
* Minor typo fix.
* Minor lint fixes on GHA workflows.
**BSS/EWCS**
**GEF**

fix(DTFS2-7911): added html and plain text render argument to mc macro

---

portal/server/controllers/dashboard/deals/deals-filters-query.ff-test.js
portal/server/controllers/dashboard/deals/deals-filters-query.js
portal/server/controllers/dashboard/deals/deals-filters-query.test.js

This PR is about to fix when `FF_PORTAL_FACILITY_AMENDMENTS_ENABLED` is disable then  checker cannot call `getCheckersApprovalAmendmentDeal` function on application-details page.
- add isPortalFacilityAmendmentsFeatureFlagEnabled() from `libs/common` to `deals-filters-query.js`
- add feature flag on unit test

fix(DTFS2-7852): fix checker can call getCheckersApprovalAmendmentDeal when feature flag is enabled

---

portal/server/utils/csv-utils.js
portal/server/utils/csv-utils.test.js

When uploading a spreadsheet under `GEF utilisation and fees` and if any of the cell is hyperlinked, the uploaded report's cell value is presented with an `[Object Object]` value to the user. This is due to the following object being rendered by the XLSX renderer.
```js
{
hyper: 'http://',
value: 'test',
}
```
instead of a plain value `test`.
* Have added `isHyperlinkedCell` CSV utility helper for evaluation, if true then refer to the `value` property.
* Added test cases.
* Minor typo fixes.

fix(FN-3923): added hyperlink check for a cell value

---

e2e-tests/tfm/cypress/e2e/journeys/facility/facility-ain-details.spec.js
e2e-tests/tfm/cypress/e2e/journeys/facility/facility-min-details.spec.js

This PR is about to fix e2e tests which fail because the date format dd_MMMM_yyyy do not much the actual output format. Example : Date expected to be in form '2 May 2025' but we get '02 May 2025' 
- today.dd_MMMM_yyyy changed to today.d_MMMM_yyyy

fix(DTFS2): fix date e2e tests

---

package-lock.json
package.json

[CVE-2024-47764](https://www.mend.io/vulnerability-database/CVE-2024-47764) was raised against `cookie` NPM package for version `0.4.0` being used by `csurf` (depreciated package).
* Forceful override of dependency to cookie `0.7.0` using NPM overrides.

fix(DTFS2-7969): updated cookie to 0.7.0 for csurf

---

azure-functions/acbs-function/tsconfig.json
gef-ui/server/controllers/application-details/canIssueUnissuedFacilities.test.js
gef-ui/server/controllers/application-details/index.js
gef-ui/server/helpers/map-facility-application-details.ts
gef-ui/tsconfig.json
libs/common/src/helpers/has-been-submitted-to-tfm.test.ts
libs/common/src/helpers/has-been-submitted-to-tfm.ts
libs/common/src/helpers/index.ts
libs/common/src/types/mongo-db-models/deals.ts
portal/tsconfig.json

`getTfmDeal` was polluting the logs from `gef-ui` and `portal-api` for deals which have not yet been submitted to TFM.
* Introduced a new central helper function `hasBeenSubmittedToTfm`, which ascertain submission to TFM based on deal's submission count property values.
* Add new unit test cases for `hasBeenSubmittedToTfm` helper function.
* Updated test cases.
* Updated various `tsconfig.json` configurations as per warnings.
* Updated central deal type, added `submissionCount` property to both `GEF` and `BSS/EWCS` deal types.

fix(DTFS2-7986): getTfmDeal conditional check on portal

---

gef-ui/component-tests/index/index.component-test.js
gef-ui/server/controllers/application-details/index.buildBody.test.js
gef-ui/server/controllers/application-details/index.js
gef-ui/templates/index.njk
portal/component-tests/index/index.component-test.js

GEF UI container was not referring to the correct `style.css`, rather it was referring to Portal UI stylesheet.
* Added `/gef` prefix to the stylesheet link.
* Added missing `latestAmendments` to `mapSummaryList()` function, causing `previewMode` to be false where it should be `true`.
* Updated component test cases for both `gef-ui` and `portal`.
* Updated unit test case for `buildBody`.
<details>
<summary>Show/hide</summary>
</details>

feat(DTFS2-8060): gef-ui broken CSS link

---

portal-api/api-tests/v1/tfm/tfm-facility-get.api-test.ts
portal-api/src/v1/routes.js

This PR fixes an error on a deal with portal amendments which is ready for checkers approval.  When the checker opens the deal, there is an error in gef-ui and portal-api
* Added checker to '/tfm/deal/:dealId' and '/tfm/facility/:facilityId' get calls in portal-api
* Updated test

fix(DTFS2-8073): fix checker unauthorised error on portal amendment deal

---

dtfs-central-api/server/services/portal/facility-amendment.service.ts
dtfs-central-api/server/services/portal/facility-amendment.submitPortalFacilityAmendmentToUkef.service.test.ts
e2e-tests/tfm/cypress/e2e/pages/amendments/amendmentsPage.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-display-portal-amendment-on-amendment-details-page.spec.js
e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/tfm/tfm-display-portal-and-tfm-amendments-on-amendment-details-page.spec.js
libs/common/src/types/mongo-db-models/tfm-facilities.ts
trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk

This PR fixes an issue where submittedBy was not displayed on the tfm amendment details tab when a portal amendment is submitted.
* Added bankName to submission to ukef when amendment submitted
* Added row for effective date on portal amendment only
* Added submittedBy on portal amendment only
* Updated unit test
* Updated e2e tests
<details>
<summary>Show/hide</summary>
</details>

fix(DTFS2-8119): portal amendements - add submittedBy and effectiveDate to tfm amendment details

---

README.md
dtfs-central-api/server/v1/routes/swagger-routes.ts
external-api/server/helpers/swagger-definitions/acbs.ts
external-api/server/helpers/swagger-definitions/bank-holidays-division.ts
external-api/server/helpers/swagger-definitions/geospatial-addresses.ts
external-api/server/v1/routes/swagger.route.ts
gef-ui/server/generateApp.js
gef-ui/server/routes/swagger.route.ts
libs/common/src/constants/services.ts
libs/common/src/constants/swagger.ts
portal-api/server/v1/routes/swagger.route.ts
portal-ui/server/generateApp.ts
portal-ui/server/routes/swagger.route.ts
trade-finance-manager-api/server/v1/routes/swagger.route.ts
trade-finance-manager-ui/server/generateApp.js
trade-finance-manager-ui/server/routes/swagger.route.ts

This PR introduces swagger UI and JSON download endpoints to following UI microservices.
* Portal UI
* GEF UI
* TFM UI
* Introduced following URLs:
* [Portal UI](http://localhost:5000/v1/api-docs/)
* [GEF UI](http://localhost:5006/v1/api-docs/)
* [TFM UI](http://localhost:5003/v1/api-docs/)
* Dependencies updates.
* Documentation updates.
* Swagger definition indentation fixes.
<details>
<summary>Show/hide</summary>
</details>

feat(DTFS2-8115): add swagger endpoints to UI microservices

---

e2e-tests/tfm/cypress/support/utils/facility-tenor.js

This PR adds a fix for the failing tenor e2e test - `e2e-tests/tfm/cypress/e2e/journeys/case-amendments/add-bank-decision/add-bank-decision-proceed.spec.js`
* Changed tenor calculation to use date-fns difference in months

fix(DTFS2-8145): added fix for failing tenor e2e test

---

azure-functions/acbs/mappings/facility/facility-loan-amend.js
azure-functions/acbs/src/functions/acbs-amend-facility.js
external-api/server/v1/controllers/acbs.controller.ts
libs/common/src/helpers/date.test.ts
libs/common/src/helpers/date.ts
trade-finance-manager-api/server/v1/controllers/acbs.controller.js
trade-finance-manager-api/server/v1/controllers/acbs.controller.test.js
trade-finance-manager-api/server/v1/helpers/amendment.helpers.js
trade-finance-manager-api/server/v1/helpers/amendment.helpers.test.js

When a facility amendment is placed the effective date for the facility loan record is being set to the timestamp of execution. This should be the effective date supplied by the Maker (Portal) or PIM (TFM).
* Introduced `effectiveDate` to the payload in EPOCH MS.
* Introduced a new date helper `epochToEpochMs` function to convert EPOCH in seconds to EPOCH in MS.
* Added new test cases.
* Updated existing test cases.

feat(DTFS2-8042): added effective date to facility amendment
