deal-api/api-tests/banks/bank-builder.js, deal-api/api-tests/banks/banks.api-test.js, deal-api/api-tests/bond-currencies/bond-currency-builder.js, deal-api/api-tests/bond-currencies/bond-currency.api-test.js, deal-api/api-tests/countries/countries.api-test.js, deal-api/api-tests/countries/country-builder.js, deal-api/api-tests/deals/deal-builder.js, deal-api/api-tests/deals/deals.api-test.js, deal-api/api-tests/industry-sectors/industry-sector-builder.js, deal-api/api-tests/industry-sectors/industry-sector.api-test.js, deal-api/api-tests/mandatory-criteria/mandatory-criteria-builder.js, deal-api/api-tests/mandatory-criteria/mandatory-criteria.api-test.js, deal-api/api-tests/transactions/transaction-builder.js, deal-api/api-tests/transactions/transactions.api-test.js, deal-api/api-tests/wipeDB.js, deal-api/src/controllers/banks.controller.js, deal-api/src/controllers/bondCurrencies.controller.js, deal-api/src/controllers/countries.controller.js, deal-api/src/controllers/deal.controller.js, deal-api/src/controllers/industrySectors.controller.js, deal-api/src/controllers/mandatoryCriteria.controller.js, deal-api/src/controllers/transactions.controller.js, deal-api/src/createApp.js
Added Delete API and test
Changed API tests to match JSON rather than Strings
100$ codecov tests on bank data
100% codecov tests for bond currencies
100% codecov for countries
100% codecov tests for industry sectors
100% codecov tests for industry sector
100% codecov for mandatory criteria
100% codecov for transactions api
=> Added deal update API and tests

portal-api/api-tests/fixtures/gef/mandatoryCriteriaVersioned.js, portal-api/api-tests/v1/gef/mandatory-criteria-versioned/mandatory-criteria-versioned.api-test.js, portal-api/api-tests/wipeDB.js, portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js, portal-api/src/v1/gef/routes.js, portal-api/src/v1/routes.js, utils/mock-data-loader/api.js, utils/mock-data-loader/clean-all-tables.js, utils/mock-data-loader/insert-mocks.js, utils/mock-data-loader/mocks/gef/mandatoryCriteriaVersioned.js, utils/mock-data-loader/mocks/index.js, utils/mock-data-loader/mocks/mocks-no-real-banks.js
- New Mandatory Criteria (versioned) endpoints
- Unit tests
- Mocks
=> DTFS2-3467: GEF | Versioned Mandatory Criteria for Backend

portal-api/__mocks__/notifications-node-client.js, portal-api/api-test-gef.jest.config.js, portal-api/api-test-quick.jest.config.js, portal-api/api-test-setup.jest.config.js, portal-api/api-tests/fixtures/gef/application.js, portal-api/api-tests/v1/gef/application.api-test.js, portal-api/api-tests/v1/gef/mandatory-criteria-versioned.api-test.js, portal-api/api-tests/v1/gef/mandatory-criteria-versioned/application.api-test.js, portal-api/api-tests/wipeDB.js, portal-api/package.json, portal-api/src/v1/gef/controllers/application.controller.js, portal-api/src/v1/gef/controllers/mandatoryCriteriaVersioned.controller.js, portal-api/src/v1/gef/controllers/validation/applicationExists.js, portal-api/src/v1/gef/routes.js, utils/mock-data-loader/README.md, utils/mock-data-loader/api.js, utils/mock-data-loader/clean-all-tables-gef.js, utils/mock-data-loader/clean-all-tables.js, utils/mock-data-loader/gef/api.js, utils/mock-data-loader/insert-mocks-gef.js, utils/mock-data-loader/insert-mocks.js, utils/mock-data-loader/mocks/gef/application.js, utils/mock-data-loader/mocks/gef/index.js, utils/mock-data-loader/mocks/index.js, utils/mock-data-loader/re-insert-mocks.js, utils/mock-data-loader/temporary-token-handler.js
Initial structure to be built upon, this should satisfy the initial create application page.
- I have separated the GEF api tests into there own folder and ran coverage on this only to speed up writing tests
- I have commented out a couple of console logs that provided little help (I always had to scroll to see api test result)
- I have left pagination code in, which works incase this is needed in the future
=> Create Application API endpoints

gef-ui/server/utils/displayItems.js
Removed link from company name
=> DTFS2-3762 - Added issued and unissued

reference-data-proxy/api-tests/v1/companies-house.api-test.js, reference-data-proxy/api-tests/v1/ordnance-survey.api-test.js
mocked out the following:
- Companies house
- Ordnance Survey
=> mock out API calls in refernce-data-proxy

e2e-tests/gef/cypress/integration/exporters-address.spec.js, e2e-tests/gef/cypress/integration/select-exporters-corr-address.spec.js
Skipping these tests just to get the pipeline working as it seesm theyve been broken for a while. Need to learn what is the correct behaviour in these areas and reinstate accordingly
=> fix: skip failing tests temporarily

gef-ui/templates/partials/ineligible-automatic-cover.njk
Link to Jira: https://ukef-dtfs.atlassian.net/browse/DTFS2-4028
=> fix: updates copy on ineligible-automatic-cover page

gef-ui/server/controllers/about-exporter/index.js, gef-ui/server/controllers/about-exporter/index.test.js
Removes decimal point requirement from probability of default question
=> DTFS2-3969: remove decimal point limit from default probabilitiy

e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort-by-buyer.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/deals/deals-sort-by-exporter.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/dealsPage.js, trade-finance-manager-ui/templates/deals/_macros/deals-table.njk
- DTFS2-3067
- DTFS2-3068
- DTFS2-3069
=> Sort TFM deals by exporter, bank, buyer

gef-ui/server/controllers/about-exporter/index.js, gef-ui/server/controllers/about-exporter/index.test.js
https://ukef-dtfs.atlassian.net/browse/DTFS2-3969
=> DTFS2-3969: fixes following testing and ui changes

portal/server/routes/login.js, portal/templates/_partials/before-you-start.njk, portal/templates/login.njk
https://ukef-dtfs.atlassian.net/browse/DTFS2-4074
Updates to login content following review
=> DTFS2-4074: login page content updates

gef-ui/styles/styles.scss, utils/mock-data-loader/mocks/gef/eligibilityCriteria.js
Update the content for questions 13, 14, and 17.  
Update the styling of the list items to add () around the roman numeral.
=> DTFS2-4026

dtfs-central-api/src/v1/controllers/portal/deal/get-deal.controller.js, e2e-tests/portal/cypress/integration/journeys/maker/dashboard/deals/dashboard-table-data.spec.js
Temporarily removes GEF aggregation from DB query as not supported by cosmos
=> DTFS-4120: temporary disable GEF aggregation

gef-ui/templates/index.njk, portal/templates/index.njk, trade-finance-manager-ui/templates/index.njk
=> dtfs2-2959 PEN test: remove prismjs

gef-ui/constants/index.js, gef-ui/server/controllers/automatic-cover/index.js, gef-ui/server/controllers/automatic-cover/index.test.js, portal-api/api-tests/v1/gef/application.api-test.js, portal-api/src/v1/gef/enums.js, portal-api/src/v1/gef/models/application.js
- dealType
- submissionCount
- submissionType
Submission type is added to the deal when cover terms is decided.
=> DTFS2-4524 - add submission details/fields to GEF deal

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/assign-lead-underwriter.spec.js, trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js, trade-finance-manager-ui/server/helpers/array.js, trade-finance-manager-ui/server/helpers/array.test.js
- add underwriters as "assign to" options in "assign lead underwriter" form
- sort options alphabetically
=> Fix/DTFS2-3724 - TFM - assign underwriter or underwriter managers as lead underwriter

portal-api/src/v1/email/index.js, trade-finance-manager-api/src/utils/number.api-test.js, trade-finance-manager-api/src/utils/number.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/deal.convert-deal-currencies.js
Fix to prevent hanging on Mulesoft currency exchange API fail.
-- Ignore the branch name, forgot to change it before pushing. It's nothing to do with Companies House API
=> fix - better handle Mulesoft exchange rate api fail

gef-ui/server/controllers/submit-to-ukef/index.js, portal-api/api-tests/v1/gef/application.api-test.js, portal-api/api-tests/v1/gef/facilities.api-test.js, portal-api/src/v1/gef/controllers/application-submit.js, portal-api/src/v1/gef/models/application.js, portal-api/src/v1/gef/models/facilities.js
=> DTFS2-4412

.github/workflows/pipeline_gef-ui.yml, .github/workflows/pr_gef-ui.yml, e2e-tests/gef/cypress/support/commands/api.js, gef-ui/package.json
Also run GEF tests on portal-api change
=> Fixed GEF test - facility API call

gef-ui/templates/partials/about-exporter.njk
https://ukef-dtfs.atlassian.net/browse/DTFS2-4080
Updated content
=> DTFS2-4080: update content on about exporter page

e2e-tests/portal/cypress/integration/journeys/maker/dashboard/bss-deals/dashboard-table-data.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/dashboard/gef-deals/dashboard-table-data.spec.js, portal/server/controllers/dashboard/index.js, portal/templates/dashboard/deals.njk
Removes sorting from table (to be added with filtering)
Fixes date formatting
=> DTFS2-4120: remove sorting and fix dates

portal-api/.eslintrc.js, portal-api/package.json, portal-api/src/constants/deal.js, portal-api/src/constants/email-template-ids.js, portal-api/src/constants/index.js, portal-api/src/reference-data/__mocks__/api.js, portal-api/src/reference-data/__mocks__/send-email.js, portal-api/src/reference-data/api.js, portal-api/src/reference-data/send-email.js, portal-api/src/v1/gef/controllers/application.controller.js
- adds send email functionality to portal-api
- fixes eslint to not look to root for config
- adds email method to change status
=> DTFS2-3987: add email update to gef status change

.github/workflows/env_demo.yml, .github/workflows/env_dev.yml, .github/workflows/env_prod.yml, .github/workflows/env_staging.yml, .github/workflows/env_test.yml, .github/workflows/pipeline_gef-ui.yml, .github/workflows/pr_gef-ui.yml, azure-functions/docker-compose.yml, docker-compose.yml, gef-ui/docker-compose.yml, portal/docker-compose.yml, reference-data-proxy/api-tests/v1/ordnance-survey.api-test.js, reference-data-proxy/docker-compose.yml, reference-data-proxy/package.json, reference-data-proxy/src/v1/controllers/ordnance-survey.controller.js, reference-data-proxy/src/v1/routes.js, trade-finance-manager-ui/docker-compose.yml
- Updates ordnance survey api url
- Updates path for postcode lookup
=> DTFS2-4405: fix postcode lookup

gef-ui/server/index.js, portal/server/index.js, trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-bss-ewcs-facility.js
- add logs for when session secret env var is missing
- remove `SESSION_SECRET` crypto fallback as it doesn't work
- Also fixed TFM facility currency mapping so it only maps currencyCode if currency object exists.
=> Portal UI server logs for missing session secret fix small TFM mapping bug

dtfs-central-api/api-tests/v1/bank/bank-get.api-test.js, dtfs-central-api/api-tests/v1/bank/bank-post.api-test.js, dtfs-central-api/src/constants/routes.js, dtfs-central-api/src/createApp.js, dtfs-central-api/src/v1/controllers/bank/create-bank.controller.js, dtfs-central-api/src/v1/controllers/bank/get-bank.controller.js, dtfs-central-api/src/v1/controllers/portal/deal/get-deal.controller.js, dtfs-central-api/src/v1/routes/bank-routes.js, dtfs-central-api/src/v1/routes/index.js, dtfs-central-api/src/v1/routes/portal-routes.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.js, trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js
- central API get & create bank
- fetch and return bank by id when getting a GEF deal
- map bank name in UI graphql reducer
=> DTFS2-4380 - central api bank endpoints, TFM mapping bank in GEF deal

portal-api/api-tests/v1/gef/facilities.api-test.js, portal-api/src/v1/gef/controllers/validation/facilities.js
https://ukef-dtfs.atlassian.net/browse/DTFS2-4617
=> DTFS2-4617: amend name validation for if not issued

.github/workflows/env_demo.yml, .github/workflows/env_dev.yml, .github/workflows/env_prod.yml, .github/workflows/env_staging.yml, .github/workflows/env_test.yml, docker-compose.yml
Create infrastructure across all environments for number generator Azure function
=> dtfs2-3793 Number Generator function - infrastructure

e2e-tests/gef/cypress/integration/about-exporter.spec.js, gef-ui/templates/partials/about-exporter.njk
https://ukef-dtfs.atlassian.net/browse/DTFS2-4691
=> DTFS2-4691: update to correct back link

gef-ui/docker-compose.yml, trade-finance-manager-ui/docker-compose.yml
Fixes UI docker compose files to use correct setup for portal
=> fixes portal docker compose call

portal-api/src/v1/controllers/transactions/loanFixer.js
https://ukef-dtfs.atlassian.net/browse/DTFS2-4339
=> DTFS2-4339: add missing type field

reference-data-proxy/src/v1/api-estore.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefSubmissionDetails.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
Also fixed a bug where TFM was mapping non existent correspondence address, which causes graphQL query to fail.
=> DTFS2-4633 - enable estore API calls for GEF. Fix TFM mapping bug

e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js, trade-finance-manager-api/src/v1/controllers/tasks.controller.js, utils/mock-data-loader/gef/api.js, utils/mock-data-loader/gef/application.js, utils/mock-data-loader/insert-mocks-gef.js
- add userId and submissionType to mock GEF deals (allows for quicker dev work when submitting to TFM)
- TFM tasks: fix submissionType mapping for BSS/GEF
=> DTFS2-4409 - add userId and submissionType to mock GEF deals. Fix mapping bug in tasks 

trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js, trade-finance-manager-api/src/v1/mappings/map-create-estore.js
=> DTFS2-4633 - estore mapping allowing for no exporter company name

.github/workflows/pr_portal-api.yml, .github/workflows/pr_portal-ui.yml, .github/workflows/pr_trade-finance-manager-ui.yml, .github/workflows/pr_trade_finance_manager-api.yml, trade-finance-manager-ui/README.md
Removed the --record flag from Cypress
=> fix: Removed the record flag for cypress

trade-finance-manager-api/src/v1/controllers/task-emails.api-test.js, trade-finance-manager-api/src/v1/controllers/task-emails.js, trade-finance-manager-api/src/v1/controllers/tasks.api-test.js, trade-finance-manager-api/src/v1/controllers/tasks.controller.js
...To handle BSS/GEF differences
Fixes "update task" not working when a GEF deal is in play.
=> DTFS2-4409 - TFM tasks controller mapping deal

.github/workflows/README.md, .github/workflows/dns.yml, .github/workflows/env_dev.yml, .github/workflows/infrastructure.yml, .github/workflows/pipeline_azure_function_acbs.yml, .github/workflows/pipeline_azure_function_number_generator.yml, .github/workflows/pipeline_dts-central-api.yml, .github/workflows/pipeline_gef-ui.yml, .github/workflows/pipeline_portal-ui.yml, .github/workflows/pipeline_reference-data-proxy.yml, .github/workflows/pipeline_trade-finance-manager-ui.yml, .github/workflows/pipeline_trade_finance_manager-api.yml, .github/workflows/pr_azure_function_acbs.yml, .github/workflows/pr_dts-central-api.yml, .github/workflows/pr_gef-ui.yml, .github/workflows/pr_no_tests.yml, .github/workflows/pr_pipeline_reference-data-proxy.yml, .github/workflows/pr_portal-api.yml, .github/workflows/pr_portal-ui.yml, .github/workflows/pr_trade-finance-manager-ui.yml, .github/workflows/pr_trade_finance_manager-api.yml, README.md
Various configuration files and README file has been updated to reflect updated branch name.
=> DTFS-4680 : Master branch renamed to main

gef-ui/server/controllers/supporting-information/security-details/index.js, gef-ui/server/models/application.js, gef-ui/templates/includes/application-details/supporting-information.njk, gef-ui/templates/partials/security-details.njk
https://ukef-dtfs.atlassian.net/browse/DTFS2-4039
- fixes error duplication
- fixes errors not showing on inputs
- changes how security details display on application details page to show all details
=> DTFS2-4039: fix issues with security details screens

.github/workflows/pr_portal-ui.yml, e2e-tests/portal/cypress/integration/journeys/maker/dashboard/bss-facilities/dashboard-table-data.spec.js, portal/server/controllers/dashboard/facilities.js, portal/server/routes/dashboard.js, portal/templates/dashboard/deals.njk, portal/templates/dashboard/facilities.njk
Changes:
- I've removed the Created-by-you filter from BSS/GEF facilities
=> fix: Removed the filters for BSS/GEF facilities

.github/workflows/pr_portal-api.yml, docker-compose.yml, portal-api/README.md
Amends memory limit on api for now to resolve issues
=> increase memory limit for portal-api

azure-functions/number-generator-function/numbergenerator/index.js
Adds check for env vars to orchestrator for number generator
=> add check for env vars in orchestrator

trade-finance-manager-api/graphql-query-tests/get-facility.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacility.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.js, trade-finance-manager-api/src/graphql/schemas/index.js, trade-finance-manager-api/src/utils/string.api-test.js, trade-finance-manager-api/src/utils/string.js, trade-finance-manager-ui/server/graphql/queries/facility-query.js, trade-finance-manager-ui/templates/case/facility/_macros/facility_details.component-test.js, trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk, trade-finance-manager-ui/templates/case/facility/facility.njk
- Map `facility.details` and `detailsOther` to `facility.providedOn`, title case
- Add `providedOn` to graphQL query
- Render in UI
=> DTFS2-4383 - TFM - add facility "provided on basis" (GEF only)

azure-functions/acbs-function/acbs/index.js, reference-data-proxy/api-tests/v1/exposure-period.api-test.js, reference-data-proxy/package-lock.json, reference-data-proxy/package.json, reference-data-proxy/src/createApp.js, reference-data-proxy/src/v1/controllers/ordnance-survey.controller.js, reference-data-proxy/src/v1/routes.js, reference-data-proxy/src/v1/swagger-definitions/acbs-industry-sector.js, reference-data-proxy/src/v1/swagger-definitions/acbs.js, reference-data-proxy/src/v1/swagger-definitions/bank.js, reference-data-proxy/src/v1/swagger-definitions/companies-house.js, reference-data-proxy/src/v1/swagger-definitions/countries.js, reference-data-proxy/src/v1/swagger-definitions/currencies.js, reference-data-proxy/src/v1/swagger-definitions/currency-exchange-rate.js, reference-data-proxy/src/v1/swagger-definitions/estore.js, reference-data-proxy/src/v1/swagger-definitions/industry-sector.js, reference-data-proxy/src/v1/swagger-definitions/notify.js, reference-data-proxy/src/v1/swagger-definitions/ordnance-survey.js, reference-data-proxy/src/v1/swagger-definitions/party-db.js, reference-data-proxy/src/v1/swagger-definitions/portal-bss-deal.js, reference-data-proxy/src/v1/swagger-definitions/premium-schedule.js, reference-data-proxy/src/v1/swagger-routes.js, reference-data-proxy/src/v1/swagger.js
=> DTFS2-4945 - Reference Data Proxy API docs

gef-ui/server/controllers/supporting-information/manual-inclusion-questionnaire/index.js, gef-ui/server/utils/fileUtils.js, gef-ui/server/utils/fileUtils.test.js
- adds call to get application after upload to avoid race condition when uploading multiple files
=> DTFS2-4029: add additional application get to help with race condition

trade-finance-manager-api/src/constants/facilities.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-facilities/mapGefFacilityProvidedOn.js, trade-finance-manager-api/src/utils/string.api-test.js, trade-finance-manager-api/src/utils/string.js, trade-finance-manager-ui/templates/case/facility/_macros/facility_details.component-test.js, trade-finance-manager-ui/templates/case/facility/_macros/facility_details.njk
This was previously just taking e.g `RESOLVING` and changing to title case to render in the UI.
Now it maps with the text so e.g `Amazing resolving basis` will render instead.
=> DTFS2-4383 - TFM mapping GEF facility "provided on basis" ids and values

azure-functions/number-generator-function/numbergenerator/index.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js, trade-finance-manager-api/src/v1/controllers/gef.controller.js, trade-finance-manager-api/src/v1/controllers/number-generator.controller.js
- Remove number generator error response if env vars are missing. This is sometimes returned locally even if they do exist.
- update some GEF mongo calls used by number generator
- add/remove some console logs
=> Number generator tweaks

portal-api/api-tests/v1/gef/facilities.api-test.js, portal-api/src/v1/gef/calculations/facility-calculations.js, portal-api/src/v1/gef/controllers/facilities.controller.js, portal-api/src/v1/gef/models/facilities.js
Also split out facility calculation functions into a new file.
=> DTFS2-4518 - GEF facility calculating Guarantee Fee

.github/workflows/promote_to_test.yml
=> CLI upgrade 1.0.0 -> 2.30.0

.github/workflows/promote_to_test.yml
1. Updated Azure cli version, latest Azure cli upgrade is not compatible with Azure login -> https://github.com/Azure/azure-cli/issues/20154
2. Explicit declaration of azure cli version for all the services
=> GHA - Azure cli update

azure-functions/acbs-function/acbs/index.js, azure-functions/acbs-function/activity-get-acbs-country-code/function.json, azure-functions/acbs-function/activity-get-acbs-country-code/index.js, azure-functions/acbs-function/api-ukef-mdm-ea.js, azure-functions/acbs-function/mappings/party/exporter.js
1. Addition of a new durable function - Responsible for retreiving ACBS 3 character ISO country code based on exporter's country name.
2. Country code durable function only invoked for GEF deals, ACBS code already exists in BSS/ECWS deals
=> Party creation based on ACBS country code

azure-functions/acbs-function/constants/deal.js, azure-functions/acbs-function/mappings/deal/deal-investor.js, azure-functions/acbs-function/mappings/deal/helpers/get-deal-effective-date.js
1. If the deal has all its facilities unissued, then the effective date is the submission date.
2. If the deal has one or more facility issued, then the effective date will be the earliest date amongst all issued facilities.
=> Updated deal effective date calculation

azure-functions/acbs-function/acbs/index.js, azure-functions/acbs-function/activity-get-acbs-country-code/index.js, azure-functions/acbs-function/constants/deal.js
1. UK countries from company house API will be converted to GBR.
2. When GBR is pre-defined ACBS country code call is skipped.
=> Company house non UK (British isles only) country codes

.github/workflows/promote_to_demo.yml, .github/workflows/promote_to_prod.yml, .github/workflows/promote_to_staging.yml, .github/workflows/promote_to_test.yml
1. CLI version upgraded from 2.30.0 to latest as AZ CLI workaround is no longer required.
=> Azure CLI version update

azure-functions/acbs-function/mappings/deal/helpers/get-deal-effective-date.js
1. formatTimestamp only works well for EPOCH or Date format not for Date time format, function change resolves the bug.
=> Effective date format change

dtfs-central-api/package-lock.json, dtfs-central-api/package.json, dtfs-central-api/src/createApp.js, dtfs-central-api/src/drivers/db-client.js, gef-ui/package-lock.json, gef-ui/package.json, gef-ui/server/index.js, portal-api/package-lock.json, portal-api/package.json, portal-api/src/createApp.js, portal/package-lock.json, portal/package.json, portal/server/index.js, reference-data-proxy/package-lock.json, reference-data-proxy/package.json, reference-data-proxy/src/createApp.js, trade-finance-manager-api/package-lock.json, trade-finance-manager-api/package.json, trade-finance-manager-api/src/createApp.js, trade-finance-manager-ui/package-lock.json, trade-finance-manager-ui/package.json, trade-finance-manager-ui/server/index.js
Added helmet to tfm-ui , tfm-api, reference-data-proxy, portal-api, portal, gef-ui, dtfs-central-api
=> DTFS2-4998 - Added helmet to improve security

dtfs-central-api/src/createApp.js, gef-ui/public/js/js-enabled.js, gef-ui/scripts/js-enabled.js, gef-ui/server/index.js, gef-ui/templates/index.njk, gef-ui/templates/partials/application-preview.njk, gef-ui/webpack.common.config.js, portal-api/src/createApp.js, portal/public/js/js-enabled.js, portal/scripts/js-enabled.js, portal/server/index.js, portal/templates/index.njk, portal/webpack.common.config.js, reference-data-proxy/src/createApp.js, trade-finance-manager-api/src/createApp.js, trade-finance-manager-ui/public/js/js-enabled.js, trade-finance-manager-ui/scripts/js-enabled.js, trade-finance-manager-ui/server/index.js, trade-finance-manager-ui/templates/index.njk, trade-finance-manager-ui/webpack.common.config.js
- fix Refused by ukef message - this was previously showing on all submitted deals
- fix for js-enabled/disabled
=> Fix for Refused by UKEF & js-enabled/disabled

e2e-tests/gef/cypress/integration/pages/application-details.js, e2e-tests/gef/cypress/integration/submit-to-ukef-mia.spec.js
1. Creates a MIA as a maker by uploading a sample doc file and submit.
2. Login as a checker to ensure attached documents are available.
3. Submit to UKEF
=> Cypress E2E - MIA to UKEF

dtfs-central-api/src/v1/controllers/portal/gef-deal/add-underwriter-comment-gef.controller.js, gef-ui/templates/partials/application-preview.njk, trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js, trade-finance-manager-api/src/v1/controllers/deal.controller.js
- fixed a bug where the Ukef refused text was always displayed. Now it should only be visible for decision that have been declined
=> Fix: Show the rejected text for Declined applications only

gef-ui/templates/partials/submit-to-ukef-confirmation.njk
- there was a missing comma missing
=> Fix: Submit-to-ukef confirmation text

dtfs-central-api/api-tests/v1/tfm/deal/tfm-deal-put-tfm.api-test.js, dtfs-central-api/src/v1/controllers/tfm/deal/tfm-update-deal.controller.js
* Reversed order activities are added to DB so timeline shows most recent activity first
* Fixed tfm-deal-put-tfm.api-test.js to reflect this order change
=> DTFS2-4056 Reversed order activities are added to DB 

gef-ui/templates/includes/application-preview/task-comments.njk
Task section on the application details page is only available when either of the condition is true:
1. Comments are available (more than zero)
2. Decision from UKEF is avialable
=> DTFS2-4124 : Task section

gef-ui/templates/_macros/submit-confirmation-title.njk, gef-ui/templates/partials/application-preview.njk, gef-ui/templates/partials/submit-to-ukef-confirmation.njk
Fixes E2E tests / correct copy
=> Remove capitalize nunjucks filter from GEF submissionType instances

e2e-tests/gef/cypress/integration/about-exporter.spec.js, e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js, gef-ui/server/controllers/about-exporter/index.js, gef-ui/server/controllers/about-exporter/index.test.js, portal-api/api-tests/v1/gef/validation/exporter.api-test.js, portal-api/src/v1/gef/controllers/validation/exporter.js
- POST endpoint: consume existing exporter data before adding submitted data
- POST endpoint: add unit test to check that api.updateApplication is called with correct data
- Exporter status/validation: cleaning, fix issue where a (valid) false value, could cause incomplete status. Add test coverage
- Add E2E tests to check exporter status depending on the data shape
=> Fix GEF exporter status/validation issue. Add test coverage

azure-functions/acbs-function/acbs-facility/index.js, azure-functions/acbs-function/activity-create-facility-covenant/index.js, azure-functions/acbs-function/api-ukef-mdm-ea.js
* MDM EA Currency code lookup URL has been modified
* ACBS currency code - If none received then GBP/O is set as default
* Minor lint fixes
=> DTFS2-4604 : GEF Facility covenant record creation

azure-functions/acbs-function/mappings/deal/helpers/get-deal-value.js, azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js
* Use GBP converted value for the facility when a deal has multiple currencies in a facility.
=> DTFS2-4391 : GEF deal record - multiple currencies

azure-functions/acbs-function/mappings/deal/deal.js, portal-api/src/v1/gef/mappings/map-companies-house-data.api-test.js, portal-api/src/v1/gef/mappings/map-companies-house-data.js
* `United Kingdom` being set as default country when no country is returned back from companies house API call, usually the case for UK based registered office address.
* Removal redudant of constant file inclusion.
=> DTFS2-4812 : Create GEF Customer

trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js, trade-finance-manager-api/src/graphql/schemas/index.js, trade-finance-manager-ui/server/graphql/queries/deal-query.js, trade-finance-manager-ui/server/graphql/queries/deals-query.js
Somehow missed this when changing the data model.
=> TFM - move deal.details.maker to the top level (graphQL queries/schema)

.gitignore, docker-compose.dev.yml
- added docker-compose.dev.yml file to help with hot reloading
- updated the mongo image to 5.0.5 - this ensures that the version stays consistent
=> Added docker-compose.dev & updated the mongo image to mongo:5.0.5

e2e-tests/gef/cypress/fixtures/dateConstants.js, e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js, e2e-tests/gef/cypress/integration/unissued-facilities-change-all-MIN.spec.js, e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-AIN.spec.js, e2e-tests/gef/cypress/integration/unissued-facilities-change-submit-ukef-MIN.spec.js, e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-AIN.spec.js, e2e-tests/gef/cypress/integration/unissued-facility-change-from-preview-MIN.spec.js, gef-ui/server/controllers/about-facility/index.test.js, gef-ui/server/controllers/mocks/index.js, gef-ui/server/controllers/unissued-facilities/index.test.js, gef-ui/server/controllers/unissued-facilities/validation.js, gef-ui/server/controllers/unissued-facilities/validation.test.js, gef-ui/templates/partials/unissued-facilities.njk
* Changed issueDate to not be able to be in the future (validation)
* Fixed validation for submission date/issue date/cover start date being in the past by setting to midnight
* updated e2e tests to reflect bug fixes
* fixed tests and added new ones to ensure validation works
=> DTFS2-3961 - Bug fixes for unissued to issued facilities

azure-functions/acbs-function/api.js
`async` keyword has been added for all ACBS API functions
=> DTFS2-4054 : 'async' keyword for all ACBS calls

trade-finance-manager-api/graphql-query-tests/get-deal.api-test.js, trade-finance-manager-api/src/graphql/schemas/index.js, trade-finance-manager-ui/server/graphql/queries/deals-query.js
Add missing `lastUpdated` to TFM schema (`tfm.deal.tfm.lastUpdated`)
=> fix/bug - add lastUpdated to TFM deals query/schema

dtfs-central-api/src/v1/controllers/durable-functions/durable-functions-controller.js, dtfs-central-api/src/v1/controllers/portal/gef-facility/get-facilities.controller.js, dtfs-central-api/src/v1/routes/portal-routes.js, portal-api/src/v1/api.js, utils/mock-data-loader/clean-all-tables-gef.js, utils/mock-data-loader/gef/api.js
* Fixed gef-facilities not being cleared
* Added new get all gef-facilities function in central-api
* added new route and controller for removing durable functions log
* fixed mock-data-loader api to show new routes and function
* renamed central and portal api url constant
=> Mock-data-loader clear gef-facilities and durable-functions-log

azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js, azure-functions/acbs-function/mappings/facility/facility-master.js, azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
* Facility master record, productTypeName is now being set as per the deal type
* Indsutry code - invalid variable name mitigation
* Minor lint fix
=> DTFS2-ACBS : Bug patches

dtfs-central-api/src/v1/controllers/tfm/facility/tfm-get-facilities.controller.js, portal/templates/contract/about/components/about-submission-details.njk
- last week we've added `hasBeenIssued` property for BSS facilities. As a result, we can simplify the query for All facilities page
- fixed a typo
=> Simplify the All facilities query for TFM

dtfs-central-api/api-tests/v1/gef-deals/gef-deal-get.api-test.js, dtfs-central-api/api-tests/v1/gef-deals/gef-deal-post.api-test.js, dtfs-central-api/api-tests/v1/gef-deals/gef-deal-put.api-test.js, dtfs-central-api/api-tests/v1/gef-deals/gef-deal-status-put.api-test.js, dtfs-central-api/api-tests/v1/gef-facilities/gef-facility-post.api-test.js, dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deal.api-test.js, dtfs-central-api/api-tests/v1/tfm/deal/tfm-gef-deals-put-submit.api-test.js, dtfs-central-api/src/v1/controllers/durable-functions/durable-functions-controller.js, dtfs-central-api/src/v1/controllers/portal/facility/get-facilities.controller.js, dtfs-central-api/src/v1/controllers/portal/gef-facility/create-gef-facility.controller.js, dtfs-central-api/src/v1/controllers/portal/gef-facility/get-facilities.controller.js, dtfs-central-api/src/v1/routes/portal-routes.js, dtfs-submissions-data/README.md, portal-api/api-tests/v1/gef/application-submit.api-test.js, portal-api/api-tests/v1/gef/facilities.api-test.js, portal-api/src/v1/gef/controllers/application.controller.js, portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js, portal-api/src/v1/gef/controllers/facilities.controller.js, trade-finance-manager-api/src/v1/controllers/gef.controller.js, utils/mock-data-loader/.eslintrc.js, utils/mock-data-loader/centralApi.js, utils/mock-data-loader/clean-all-tables-gef.js, utils/mock-data-loader/clean-all-tables.js, utils/mock-data-loader/insert-mocks.js, utils/mock-data-loader/package-lock.json, utils/mock-data-loader/package.json, utils/mock-data-loader/refresh-reference-data.js
- removed the `gef-facilities` collection and combined all GEF facilities with BSS
=> Combined GEF & BSS facilities under one collection

dtfs-central-api/.eslintrc.js, portal-api/.eslintrc.js, reference-data-proxy/.eslintrc.js, trade-finance-manager-api/.eslintrc.js, trade-finance-manager-api/src/v1/helpers/tasks.api-test.js, trade-finance-manager-api/src/v1/tasks/tasks-edit-logic.js, utils/mock-data-loader/.eslintrc.js
=> Turn off no-console eslint rule in APIs

azure-functions/acbs-function/acbs-issue-facility/index.js, azure-functions/acbs-function/activity-create-facility-covenant/index.js, azure-functions/acbs-function/activity-get-acbs-country-code/index.js, azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js, azure-functions/acbs-function/activity-get-facility-master/index.js, azure-functions/acbs-function/mappings/facility/facility-update.js, reference-data-proxy/src/v1/controllers/acbs.controller.js, trade-finance-manager-api/api-tests/v1/acbs/acbs.api-test.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/acbs.controller.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js, trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js, trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.api-test.js, trade-finance-manager-api/src/v1/mappings/map-submitted-deal/map-cash-contingent-facility.js
ACBS facility stage update issue has been patched, this commit entails following changes:
* Addition of additional `dealType` argument used for facility type and exposure period computation.
* ACBS MDM EA calls - Safe array index access condition.
* ACBS Facility update - Addition of `exposurePeriod` and `description` post fields for an accurate facility record.
* `issuedFacilityMaster`  sub object existence verification. 
* GEF Facility mapping - `ukefFacilityId` as string
* Introduction of try-catch blocks on various calls.
* Improved documentation.
* Lint fixes.
=> DTFS2-4586 : ACBS Facility update

portal/Dockerfile, portal/sshd_config
Azure App service docker container SSH access
=> DTFS2-5301 : Portal UI SSH Access

portal/Dockerfile, portal/ssh_setup.sh
Portal UI Azure Web App Services SSH configuration
=> DTFS2-5301 : Portal UI SSH

e2e-tests/gef/cypress/fixtures/constants.js, e2e-tests/portal/cypress/integration/journeys/checker/cannot-submit-a-deal-with-newly-issued-facilities-that-have-cover-start-dates-before-today/deal.js, e2e-tests/portal/cypress/integration/partials/ukef-comments.js, e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/MIA-underwriter-managers-decision-updates-portal-deal/TFM-MIA-underwriter-managers-decision-approved-with-conditions-updates-portal-deal.spec.js, portal-api/api-tests/v1/deals/deal-clone.api-test.js, portal-api/api-tests/v1/deals/deal-comments.api-test.js, portal-api/src/v1/controllers/deal-clone.controller.js, portal-api/src/v1/controllers/deal-comments.controller.js, portal-api/src/v1/controllers/integration/type-b-helpers/update-comments.js, portal-api/src/v1/controllers/integration/type-b.controller.js, portal/templates/contract/components/ukef-comments.njk, portal/templates/contract/contract-submission-details.njk, portal/templates/contract/contract-view-comments.njk, portal/templates/contract/contract-view.njk, trade-finance-manager-api/src/constants/deals.js, trade-finance-manager-api/src/v1/controllers/deal.controller.js, utils/data-migration/maps/map-comments.js, utils/mock-data-loader/bss/deals/10.js, utils/mock-data-loader/bss/deals/11.js, utils/mock-data-loader/bss/deals/2.js, utils/mock-data-loader/bss/deals/4.js, utils/mock-data-loader/bss/deals/5.js, utils/mock-data-loader/bss/deals/6.js, utils/mock-data-loader/bss/deals/7.js, utils/mock-data-loader/bss/deals/8.js, utils/mock-data-loader/bss/deals/9.js
- replaced  `specialConditions` property with `ukefDecision`
=> Replaced `specialConditions` with `ukefDecision`

trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealDetails.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/gef-deal/mapGefDealSnapshot.js
Missed mappings after changing the data model
=> Fix/DTFS2-5238 DTFS2-5239 - fix GEF mappings in TFM

.github/workflows/pipeline_azure_function_acbs.yml, .github/workflows/pipeline_azure_function_number_generator.yml, .github/workflows/pipeline_dts-central-api.yml, .github/workflows/pipeline_gef-ui.yml, .github/workflows/pipeline_portal-api.yml, .github/workflows/pipeline_portal-ui.yml, .github/workflows/pipeline_reference-data-proxy.yml, .github/workflows/pipeline_trade-finance-manager-ui.yml, .github/workflows/pipeline_trade_finance_manager-api.yml, .github/workflows/pr_azure_function_acbs.yml, .github/workflows/pr_azure_function_number_generator.yml, .github/workflows/pr_dts-central-api.yml, .github/workflows/pr_gef-ui.yml, .github/workflows/pr_portal-api.yml, .github/workflows/pr_portal-ui.yml, .github/workflows/pr_reference_data_proxy.yml, .github/workflows/pr_trade-finance-manager-ui.yml, .github/workflows/pr_trade_finance_manager-api.yml, dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-api/src/v1/helpers/activity.api-test.js, trade-finance-manager-ui/Dockerfile
* GHA version reverted back to `v1`
* Dockerfile added hot reloading
* Typo fixes
=> Various Updates

e2e-tests/portal/cypress/integration/journeys/maker/eligibility-criteria.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/eligibility-documentation.spec.js, e2e-tests/portal/cypress/integration/pages/eligibilityCriteria.js, e2e-tests/portal/cypress/integration/pages/eligibilityDocumentation.js, portal/templates/contract/components/task-list-header.njk, portal/templates/eligibility/eligibility-supporting-documentation.njk
* Changed supporting information page title from Choose eligibility -> Add supporting information
* Added to relevant e2e tests to test for this title
* Added data-cy to task table header
=> DTFS2-2220 Changed supporting documentation page title

trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.api-test.js, trade-finance-manager-api/src/v1/emails/AIN-MIN-confirmation/gef-facilities-list.js
* removed requestedCoverStartDate from email facilities list
* Updated test
=> DTFS2-5356 Remove requested cover start date from emails

.github/workflows/pipeline_azure_function_acbs.yml, .github/workflows/pipeline_azure_function_number_generator.yml, .github/workflows/pipeline_dts-central-api.yml, .github/workflows/pipeline_gef-ui.yml, .github/workflows/pipeline_portal-api.yml, .github/workflows/pipeline_portal-ui.yml, .github/workflows/pipeline_reference-data-proxy.yml, .github/workflows/pipeline_trade-finance-manager-ui.yml, .github/workflows/pipeline_trade_finance_manager-api.yml
* Main merge initiates deployment to `dev` environment
=> DTFS2-Infrastructure :  Dev environment

e2e-tests/gef/cypress/integration/application-details-submit-to-checker.spec.js, gef-ui/server/controllers/activities-controller/index.js, gef-ui/server/controllers/activities-controller/index.test.js, gef-ui/server/controllers/mocks/index.js, gef-ui/server/models/application.js, gef-ui/templates/partials/application-activity.njk
* fixed wrong date on date submitted to UKEF on activity page
* fixed created by being undefined on application-details
* added to relevant tests
=> DTFS2-5370 GEF Bug - Fix created by and date submitted to UKEF bugs

trade-finance-manager-api/src/graphql/reducers/deals.api-test.js, trade-finance-manager-api/src/graphql/reducers/deals.js
- added supporting information for GEF deals in tfm
=> Adding supporting information to graphql query for GEF deals

e2e-tests/gef/cypress/integration/exporters-incomplete-details.spec.js, e2e-tests/gef/cypress/integration/pages/dashboard-page.js, gef-ui/server/controllers/companies-house/index.js
* added blank strings for smeType, probabilityOfDefault, isFinanceIncreasing when saving companies house number
* fixes bug where these fields were hidden when exited without saving
* Added e2e test to ensure bug does not happen
=> DTFS2-5369 GEF Bug - Show incomplete exporter fields

e2e-tests/gef/cypress/integration/review-ukef-approval-without-issuing-facilities-MIA-and-resubmit-to-ukef.spec.js, gef-ui/server/controllers/application-details/index.js, gef-ui/server/controllers/application-details/index.test.js, gef-ui/server/utils/facility-helpers.js, gef-ui/server/utils/facility-helpers.test.js, gef-ui/server/utils/helpers.js, gef-ui/server/utils/mocks/mock_applications.js, gef-ui/templates/includes/application-details/applicationReferenceAndActions.njk, gef-ui/templates/includes/application-details/automatic-cover.njk, gef-ui/templates/includes/application-details/facilities.njk
Edge case: on MIA -> MIN, if not issuing any unissued facilities, returning to maker unlocked the full application details page
* Added condition for map summary list for edge case if MIA, submission count > 0, and if changes required
* Added application details parameter for ^
* Locked certain buttons using application details parameter
* Added e2e test for edge case (MIA accepting decision without changing unissued facilities)
=> DTFS2-5385 GEF Bug - return to maker MIA bug

e2e-tests/gef/cypress/integration/application-details-submit-to-checker.spec.js, e2e-tests/gef/cypress/integration/pages/application-details.js, gef-ui/server/controllers/application-submission/index.js, gef-ui/server/controllers/application-submission/index.test.js, gef-ui/server/controllers/mocks/index.js, gef-ui/templates/includes/application-preview/task-comments.njk
* Added firstname, surname and email address to comments object
* Changed task-comments.njk to show firstname and lastname rather than username
* Added e2e test case
* Updated gef-ui test
=> DTFS2-5394 - GEF Bug - Changed portal comments to show first and lastname

gef-ui/package-lock.json, package-lock.json, portal-api/api-tests/v1/bonds/bonds-validation.api-test.js, portal-api/api-tests/v1/loan/loan-validation.api-test.js, portal-api/package-lock.json, portal-api/src/v1/validation/fields/cover-dates.js
* Added validation for cover end date being the same as cover start date for BSS 
* Added portal-api tests
=> DTFS2-5073 - BSS Bug - Cover end date validation

e2e-tests/portal/cypress/integration/journeys/checker/dashboard/dashboard.spec.js
The bug has been fixed but added a different banks' deal to an E2E test to make sure it's covered.
=> DTFS2-5372 - add test to make sure checker does not see other bank's deals in dashboard

.github/workflows/env_dev.yml, .github/workflows/promote_to_test.yml
Usage of `self-hosted` `linux` runners for for deployment to `dev` and `test` enviorments.
=> GHA - Self-hosted runners

azure-functions/acbs-function/helpers/date.js
`isString` function to resolve string timestamp.
=> DTFS2-ACBS : Date bug fix

e2e-tests/trade-finance-manager/cypress/support/portal-api/createGefFacility.js, trade-finance-manager-api/src/v1/controllers/send-tfm-email.js
* removed whole tfm object being sent to update deal from send-tfm-email.js which was causing activities to be duplicated
* removed unnecessary comment from previous PR
=> DTFS2-5416 - TFM bug - TFM activities duplication fix

.github/workflows/pr_azure_function_acbs.yml, .github/workflows/pr_azure_function_number_generator.yml, .github/workflows/pr_gef-ui.yml, .github/workflows/pr_no_tests.yml, .github/workflows/pr_portal-api.yml, .github/workflows/pr_portal-ui.yml, .github/workflows/pr_trade-finance-manager-ui.yml, .github/workflows/pr_trade_finance_manager-api.yml
`self-hosted` -> `ubuntu-latest`
=> DTFS2 - GitHub : Self-Hosted -> GH Runnners

azure-functions/acbs-function/helpers/date.js, reference-data-proxy/src/v1/controllers/party-db.controller.ts
* `isEpoch` helper function to ascertain timestamp is Epoch or not, given lack of unformity across the system on timestamp storage format.
* Error object properties verification
=> DTFS2-ACBS : Date bug

reference-data-proxy/src/v1/controllers/party-db.controller.ts
=> DTFS2 : File restored

reference-data-proxy/Dockerfile, reference-data-proxy/init.sh, reference-data-proxy/package-lock.json, reference-data-proxy/package.json
- updated the Dockerfile to node:17-alpine3.14
- used nodemon to start the server
=> Updating Reference Data Proxy

azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js, azure-functions/acbs-function/mappings/facility/helpers/get-next-quarter-date.js
* `1001` set as default industry code
* Lint fix
=> DTFS2 - ACBS Bugs

.github/workflows/dns.yml, .github/workflows/env_dev.yml, .github/workflows/env_prod.yml, .github/workflows/env_test.yml, .github/workflows/pipeline_azure_function_acbs.yml, .github/workflows/pipeline_azure_function_number_generator.yml, .github/workflows/pipeline_dts-central-api.yml, .github/workflows/pipeline_gef-ui.yml, .github/workflows/pipeline_portal-api.yml, .github/workflows/pipeline_portal-ui.yml, .github/workflows/pipeline_reference-data-proxy.yml, .github/workflows/pipeline_trade-finance-manager-ui.yml, .github/workflows/pipeline_trade_finance_manager-api.yml, .github/workflows/pr_azure_function_acbs.yml, .github/workflows/pr_azure_function_number_generator.yml, .github/workflows/pr_gef-ui.yml, .github/workflows/pr_no_tests.yml, .github/workflows/pr_portal-api.yml, .github/workflows/pr_portal-ui.yml, .github/workflows/pr_trade-finance-manager-ui.yml, .github/workflows/pr_trade_finance_manager-api.yml, .github/workflows/promote_to_demo.yml, .github/workflows/promote_to_prod.yml, .github/workflows/promote_to_staging.yml, .github/workflows/promote_to_test.yml
* `self-hosted` runners for PR, Promote and Environment.
* `self-hosted` `deployment` tagged runners to be only used for deployment across all environments.
=> DTFS2-TD : GH Runners

azure-functions/acbs-function/acbs/index.js, azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js, azure-functions/acbs-function/constants/deal.js, azure-functions/acbs-function/mappings/party/exporter.js, azure-functions/acbs-function/mappings/party/helpers/get-sme-type.js
When creating a new customer in ACBS, party's `SME`, `Industry Classification` and `UK Entity` were not being set correctly. This ticket resolves the bug by following changes:
* `citizenshipClass` if `GBR` then `1` else `2` (ROW).
* Lower case constants for like-to-like comparison.
* Frivolous constants removal.
* Frivolous comments removal.
=> DTFS2-5425 : Exporter meta data correction

portal-api/api-tests/v1/users/reset-password.api-test.js, portal-api/src/v1/users/routes.js, portal/server/api.js, portal/server/routes/login.js
Upon requesting password reset, neither password nullable nor match verification were in place. This PR aims to mitigate these issues through following updates:
* Current password, new password and confirm new password nullable check.
* New password and confirm new password match check.
* `400` status retuned upon an error message.
* Lint fixes
=> DTFS2-5428 : Password reset verification

e2e-tests/trade-finance-manager/cypress/integration/journeys/login/login.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/landingPage.js, trade-finance-manager-ui/templates/login.njk
* Changed headings for sign in fields on TFM
* Added data-cy tags
* Added tests to ensure tags are the same
* Added padding on top of sign in header
=> DTFS2-5459 - TFM Bug - Incorrect sign in page labels

e2e-tests/gef/cypress/integration/upload-files-to-azure.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/eligibility-documentation.spec.js, gef-ui/templates/_macros/fileList.njk, gef-ui/templates/_macros/fileSuccess.njk, portal-api/src/v1/controllers/deal-eligibility-documentation.controller.js, portal-api/src/v1/gef/models/files.js, portal/server/api.js, portal/templates/_macros/eligibility-documentation-file-input.njk
* added filesize to links for uploaded file
* Changed gef model to use filesize library to change size to kb
* used filesize library in portal-api to convert size to kb
* Added e2e test snippets to test this
=> DTFS2-5443- Accessibility - Added uploaded file size

azure-functions/acbs-function/constants/facility.js, azure-functions/acbs-function/mappings/facility/facility-loan.js, azure-functions/acbs-function/mappings/facility/facility-master.js, azure-functions/acbs-function/mappings/facility/helpers/get-product-type-id.js
Facility helper function was not returning code for `Contigent` facility.
* `281` code has been added for `Contigent` facility type.
* Redundant `dealType` argument has been removed.
=> DTFS2-5498 : ACBS Facility type code

e2e-tests/gef/cypress/integration/facilities.spec.js, gef-ui/server/controllers/facilities/index.js, gef-ui/server/controllers/facilities/index.test.js, gef-ui/server/controllers/provided-facility/index.js, gef-ui/server/controllers/provided-facility/index.test.js
* On facility hasBeenIssued page, on validation error, title was showing undefined for facilityType
* error message on provided-facility did not contain href for skipping to error
* Added facilityType to validation error render for facilities.njk
* Added errorRef for provided-facilitiies
=> DTFS2-5513 - GEF Accessibility & Bug - fix error skip link and undefined bug

gef-ui/server/controllers/facilities/index.js, gef-ui/server/controllers/facilities/index.test.js, gef-ui/server/services/api.js
* could not create facility as facilityType was lowercase
* readded facilityTypeString so that facilityType stays uppercase
=> DTFS2-5513 - GEF Bug - fix failure to create facility

e2e-tests/gef/cypress/integration/page-header.spec.js, e2e-tests/portal/cypress/integration/journeys/portal-header.spec.js, gef-ui/templates/includes/header.njk, portal/templates/_partials/header.njk
* portal header changed from username to full name of user
=> DTFS2-5463 - Portal & GEF - header fullname

.github/workflows/env_dev.yml, .github/workflows/env_prod.yml, .github/workflows/env_staging.yml
Upon infrastructure build new collections will be added to the Cosmos database.
`mandatoryCriteria` collection will now have it's indices build during the infrastructure build process.
=> DTFS2-5531 : Collections and indices

portal/templates/_macros/mandatory-criteria-box.njk
- fixed missing mandatory criteria for BSS/EWCS
=> DTFS2-5517: Portal - BSS/EWCS Mandatory criteria is missing

.github/workflows/env_dev.yml, .github/workflows/env_prod.yml, .github/workflows/env_staging.yml
=> DTFS2-Collection : Typo fix

e2e-tests/gef/cypress/integration/provided-facility.spec.js, gef-ui/templates/partials/provided-facility.njk
* no error was present in checkboxes component (only on top of page)
* added error to checkbox component
=> DTFS2-5513 - GEF Bug/Accessibility - Error in govukCheckbox component

e2e-tests/portal/cypress/integration/journeys/maker/about-supply-contract/about-supply-contract-page-titles.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-details.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-fee-details.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-financial-details.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-dates-repayments.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-financial-details.spec.js, e2e-tests/portal/cypress/integration/journeys/maker/loan/loan-guarantee-details.spec.js, e2e-tests/portal/cypress/integration/pages/bondDetails.js, e2e-tests/portal/cypress/integration/pages/bondFeeDetails.js, e2e-tests/portal/cypress/integration/pages/bondFinancialDetails.js, e2e-tests/portal/cypress/integration/pages/contract/about/about-buyer.js, e2e-tests/portal/cypress/integration/pages/contract/about/about-financial.js, e2e-tests/portal/cypress/integration/pages/contract/about/about-supplier.js, e2e-tests/portal/cypress/integration/pages/loanDatesRepayments.js, e2e-tests/portal/cypress/integration/pages/loanFinancialDetails.js, e2e-tests/portal/cypress/integration/pages/loanGuaranteeDetails.js, portal/templates/bond/bond-fee-details.njk, portal/templates/bond/bond-financial-details.njk, portal/templates/contract/about/about-supply-buyer.njk, portal/templates/contract/about/about-supply-financial.njk, portal/templates/loan/loan-dates-repayments.njk, portal/templates/loan/loan-financial-details.njk
* added page titles for each page for loan/bond and supplier contract
* updated and added e2e tests
=> DTFS2-2220 - Accessibility BSS - page titles

e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js, portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
* Issue date was appearing on draft cloned deal for issued facilities
* Added submittedAsIssuedDate and set to null in clone deal controller
* Updated e2e test to make sure it works
=> DTFS2-5466- Portal GEF Bug - Issue date appearing on cloned deal

portal-api/api-tests/v1/gef/application-submit.api-test.js, portal-api/src/v1/gef/controllers/application-submit.js, portal-api/src/v1/gef/controllers/facilities.controller.js
* coverStartDate was being overwritten on every submission
* added if !hasBeenIssuedAndAcknowledged to make sure not overwritten
* Added api-test
=> DTFS2-5529 - Bug - Cover start date override

azure-functions/acbs-function/acbs-facility-loan/index.js, azure-functions/acbs-function/mappings/deal/deal-guarantee.js, azure-functions/acbs-function/mappings/deal/deal-investor.js, azure-functions/acbs-function/mappings/deal/deal.js, azure-functions/acbs-function/mappings/deal/helpers/get-deal-currency.js, azure-functions/acbs-function/mappings/deal/helpers/get-deal-guarantee-value.js, azure-functions/acbs-function/mappings/deal/helpers/get-deal-value.js, azure-functions/acbs-function/mappings/deal/helpers/index.js, azure-functions/acbs-function/mappings/facility/facility-covenant.js, azure-functions/acbs-function/mappings/facility/facility-loan.js, azure-functions/acbs-function/mappings/facility/helpers/get-base-currency.js, azure-functions/acbs-function/mappings/facility/helpers/get-facility-value.js, azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency-months.js, azure-functions/acbs-function/mappings/facility/helpers/get-fee-frequency.js, azure-functions/acbs-function/mappings/facility/helpers/get-fee-type.js, azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js, azure-functions/acbs-function/mappings/facility/helpers/get-maximum-liability.js, azure-functions/acbs-function/mappings/facility/helpers/get-next-due-date.js, azure-functions/acbs-function/mappings/facility/helpers/index.js, azure-functions/acbs-function/mappings/facility/helpers/map-fee-frequency.js, azure-functions/acbs-function/mappings/facility/helpers/map-fee-type.js, trade-finance-manager-api/src/v1/controllers/deal.controller.js, trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.api-test.js
Following ACBS UAT testing various data anomalies have been reported either due to incorrect business requirement previously interpreted or due to existing bugs in the ACBS durable functions.
* Introduction of `getDealGuaranteeValue` helper function, responsible for evaluation deal guarantee record maximum liability.
* Simplification and standardisation of `getDealCurrency` , `getDealValue` and `getMaximumLiability` helper functions based on updated insight from ACBS team.
* Introduction of a new argument in `getMaximumLiability` helper function, `overallAmount` specifically used for facility covenant record.
* Standardisation of `mapFeeFrequency` helper function and increased usage.
* Introduction of `mapFeeType` helper function.
* Introduction of `getLoanMaximumLiability` for evaluating …
=> DTFS2-ACBS : Bug fixes + Updated logics

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/activities/activities.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/parties/parties.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/assign-lead-underwriter.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/pricing-and-risk.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/underwriter-managers-decision.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/activities/activitiesPage.js, e2e-tests/trade-finance-manager/cypress/integration/pages/partiesPage.js, e2e-tests/trade-finance-manager/cypress/integration/pages/tasksPage.js, e2e-tests/trade-finance-manager/cypress/integration/partials/underwritingSubNav.js, trade-finance-manager-ui/templates/case/activity/activity-comment.njk, trade-finance-manager-ui/templates/case/activity/activity.njk, trade-finance-manager-ui/templates/case/deal/deal.njk, trade-finance-manager-ui/templates/case/documents/documents.njk, trade-finance-manager-ui/templates/case/parties/parties.njk, trade-finance-manager-ui/templates/case/tasks/tasks.njk, trade-finance-manager-ui/templates/case/underwriting/layout.njk, trade-finance-manager-ui/templates/deals/deals.njk, trade-finance-manager-ui/templates/facilities/facilities.njk
* used govuk component to add "add a comment" header to the page which adds for label automatically
* added aria-labels for page headings
=> DTFS2-5586 - 5587 - TFM accessibility

e2e-tests/gef/cypress/integration/submit-to-ukef-mia.spec.js, e2e-tests/gef/cypress/integration/submit-to-ukef.spec.js, gef-ui/templates/partials/submit-to-ukef.njk
* a word was missing from submit to UKEF page
* added the word
* updated tests
=> DTFS2- 5600  - GEF Bug - word missing from submit ukef

trade-finance-manager-ui/README.md, trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk
=> DTFS2-5438 - TFM - remove facility currency from premium schedule view

e2e-tests/trade-finance-manager/cypress/fixtures/tasks-MIA.js, trade-finance-manager-api/src/constants/tasks.js
-  ‘Create a credit analysis document’ task is labelled ‘Create a credit submission document'.
-  ‘Complete the credit analysis’ tasks is labelled ‘Complete the credit submission’
-  ‘Check the credit analysis’ tasks is labelled ‘Check the credit submission’
=> DTFS2-5488: Change 'credit analysis' to 'credit submission'

e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js, e2e-tests/gef/cypress/integration/pages/upload-files.js, e2e-tests/gef/cypress/integration/upload-files-to-azure.spec.js, gef-ui/server/controllers/supporting-information/supporting-documents/docType.js, gef-ui/server/controllers/supporting-information/supporting-documents/index.test.js, gef-ui/server/models/application.js, gef-ui/server/models/application.test.js, gef-ui/templates/includes/application-details/supporting-information.njk, gef-ui/templates/includes/supporting-documents/exportLicence.njk, portal-api/api-tests/v1/gef/validation/supportingInfo.api-test.js, portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js, trade-finance-manager-api/src/v1/mappings/map-create-estore.api-test.js, trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.api-test.js, trade-finance-manager-api/src/v1/mappings/map-ukef-documents-to-estore.js
- removed the Export Licence - this is no longer needed
=> Remove Export License from GEF Supporting Documentation

gef-ui/templates/includes/footer.njk, portal/templates/_partials/footer.njk
- added the vulnerability link in the footer
=> DTFS2-5606:  Report a Vulnerability link

trade-finance-manager-ui/templates/user/change-password.njk
- the change password form was missing the csrf input
=> TFM - Password change page & unable to change password

docker-compose.dev.yml, docker-compose.gha.yml, docker-compose.yml, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/documents/documents.spec.js, reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts, trade-finance-manager-ui/templates/case/documents/documents.component-test.js, trade-finance-manager-ui/templates/case/documents/documents.njk
- updated the eStore URL in tfm to match the new requirements
=> Updated the URL for eStore site in TFM

e2e-tests/portal/cypress/integration/journeys/login/change-password.spec.js, e2e-tests/portal/cypress/integration/journeys/login/reset-password.spec.js, portal-api/src/v1/email/index.js, portal-api/src/v1/users/controller.js, portal-api/src/v1/users/routes.js, portal-api/src/v1/users/validation/rules/passwordAtLeast8Characters.js, portal/server/routes/login.js, portal/server/routes/user/profile.js, utils/mock-data-loader/portal/users.js
- ask for the current password only if the user is already logged in
- validate the new password and ensure that it's length is bigger than 8 chars
- updated the e2e-tests/
=> Updated the `Change password` page. Validate passwords that are too short

trade-finance-manager-api/src/constants/teams.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js, trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js, utils/mock-data-loader/tfm/mocks/teams.js
- PIM users should receive a copy of AIN/MIN & facilities
=> Allow PIM users to receive email notifications

azure-functions/acbs-function/package-lock.json, azure-functions/acbs-function/package.json, dtfs-central-api/package-lock.json, dtfs-central-api/package.json, gef-ui/package-lock.json, gef-ui/package.json, portal-api/package-lock.json, portal-api/package.json, portal/package-lock.json, portal/package.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-api/package.json, trade-finance-manager-ui/package-lock.json, trade-finance-manager-ui/package.json, utils/data-migration/package.json, utils/mock-data-loader/package-lock.json, utils/mock-data-loader/package.json
- version `2.29.1` has a High security issue. This has been patched in `v2.29.2`
=> Updated moment.js to 2.29.2 to fix the latest security issues

portal-api/api-tests/v1/users/users.api-test.js, portal-api/src/crypto/utils.js, portal/server/routes/login.js, portal/server/routes/middleware/validate-token.js
GDS criteria requires us to re-direct the user to the **Start** page upon entering a direct link to the application.
This has been accomplished in conjunction with `JWT` (JSON Web Token) expiration timeframe, once expired user will be redirected to the GOV UK start page `https://get-a-guarantee-for-export-finance.service.gov.uk/`.
* JWT token timeframe reduced to `12h` to keep it inline with CSRF expiration timeframe.
* Start page re-direction only when `START_PAGE_REDIRECT` environment variable is set (currently manually added to `tfs-prod-portal-ui `
* Improved documentation
=> DTFS2-5504  : GovUK Redirect

trade-finance-manager-api/.eslintrc.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.tasks.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-second-submit-facilities-unissued-to-issued.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-submitted-non-gbp-contract-value.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-AIN-submitted.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-not-submitted.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-second-submit-facilities-unissued-to-issued.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-second-submit.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIA-submitted.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIN-second-submit-facilities-unissued-to-issued.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-MIN.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-acbs.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-facilities-USD-currency.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-issued-facilities.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-companies-house.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-party-db.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal-no-ukef-id.js, trade-finance-manager-api/src/v1/__mocks__/mock-deal.js, trade-finance-manager-api/src/v1/__mocks__/mock-gef-deal.js, trade-finance-manager-api/src/v1/__mocks__/mock-portal-users.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-bss.api-test.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js, trade-finance-manager-api/src/v1/controllers/send-issued-facilities-received-email.js
- send emails to bank's general email address
- updated PIM's email address - this is not take from an API call, rather than mongodb query
=> feat: Added notification to bank's general inbox

portal/server/routes/static.js
`security.txt` static content updates:
* Location
* Policy URL
* Contact URL
* Last updated timestamp
=> fix: update the security.txt file

.github/workflows/pr_integration_tests.yml
Added `main-amendments` to Integration test.
=> DTFS2-PR-Test : Added main-amendment

trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
ACBS Interaction moved out of `MIN` branch as this condition will not always be true.
=> DTFS2-5759 : ABCS interaction

trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
In order to expedite migrated deal ACBS execution, `updatedDeal` will be subjected to below:
* Deal object added to `migratedDeals` collection.
* Issued facility DF ready JSON available under `issueFacility` array.
=> DTFS2-5759 : Migrated deal

e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-MIN-changes-tfm-stage-to-confirmed/submit-MIN-changes-tfm-stage-to-confirmed.spec.js, e2e-tests/trade-finance-manager/cypress/fixtures/constants.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js, trade-finance-manager-api/src/constants/deals.js, trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dealStage.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js
* Added functionality for MIN submissions to change tfm deal stage to confirmed
* Added submit-to-tfm test
* Updated tfm-api test
* Added constant for abandoned deal on TFM-api
=> DTFS2-5783 - TFM- MIN stage confirmed

portal-api/src/v1/gef/models/application.js
`mandatoryVersionId` check in GEF deal model.
=> fix: updated the `mandatoryCriteriaVersioned` for GEF deals

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/underwriter-managers-decision.spec.js, e2e-tests/trade-finance-manager/cypress/integration/partials/underwritingSubNav.js, trade-finance-manager-ui/templates/case/underwriting/managers-decision/managers-decision.njk
* Underwriter managers decision is blank for AIN
* added not applicable if AIN
* added to e2e test
=> fix(DTFS2-5818): AIN underwriter managers decision

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/underwriting/probability-of-default.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/underwriting/probabilityOfDefaultPage.js, trade-finance-manager-api/src/graphql/resolvers/mutation-update-probability-of-default.js, trade-finance-manager-api/src/graphql/schemas/index.js, trade-finance-manager-ui/package-lock.json, trade-finance-manager-ui/package.json, trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/pricing-and-risk/probability-of-default/index.test.js, trade-finance-manager-ui/server/controllers/deals/index.js, trade-finance-manager-ui/server/controllers/deals/index.test.js, trade-finance-manager-ui/server/controllers/helpers/index.js, trade-finance-manager-ui/server/controllers/helpers/index.test.js, trade-finance-manager-ui/templates/case/underwriting/pricing-and-risk/probability-of-default.njk
* Probability of default did not accept decimals
* Allowed to add probability of default below 0.01 and above 14.09
* changed probability of default to Float from Int
* Added validation using JOI to check for decimal places and limits
* updated tests
=> fix(DTFS2-5816): Probability of default validation

e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js, portal-api/api-tests/v1/deals/deal-clone.api-test.js, portal-api/src/v1/controllers/deal-clone.controller.js, portal-api/src/v1/controllers/deal.controller.js, portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
- updated the deal clone functionality to always return the latest version of eligibility criteria
=> fix: return the latest eligibility criteria for GEF and BSS/EWCS deals

trade-finance-manager-api/src/v1/mappings/map-eligibility-criteria-content-strings.js, trade-finance-manager-ui/server/api.js
GQL was failing to return the deal back due to void EC  and upon accessing property of an undefined object the TFM-UI crashes.
This PR aims to mitigate these issues with an eye on improved error handling.
* `Number` function to access array index.
* `networkError` check, if present appropriate error is logged using `console.error`
=> Eligibility Criteria : Capture network errors & array index number typecaste

azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
Un-issued and issued facilities exposure period.
=> DTFS2-5821 : Unissued facility exposure period

reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
- removed the `checkExistingCronJobs` function from eStore integration
=> fix: removed the `checkExistingCronJobs` function from eStore

dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-ui/Dockerfile
Dockerfile base image upgraded to `node:18.4-alpine3.16`
=> build: updated Node.JS to `node:18.4-alpine3.16`

e2e-tests/e2e-fixtures/constants.fixture.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-in-progress-deal-stage.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/index.js, e2e-tests/trade-finance-manager/cypress/integration/partials/caseSubNavigation.js, trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js, trade-finance-manager-ui/package.json, trade-finance-manager-ui/server/controllers/case/activity/index.js, trade-finance-manager-ui/server/controllers/case/activity/index.test.js, trade-finance-manager-ui/server/controllers/case/amendments/managersConditionsAndComments.controller.js, trade-finance-manager-ui/server/controllers/case/index.js, trade-finance-manager-ui/server/controllers/case/index.test.js, trade-finance-manager-ui/server/controllers/case/parties/index.js, trade-finance-manager-ui/server/controllers/case/parties/index.test.js, trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js, trade-finance-manager-ui/templates/case/amendments/amendment-managers-conditions-and-comments.njk
* On errors on UW managers decision comments page for amendments, tags would turn blue and dates were not formatted (DTFS2: 5871)
* Not all pages had Amendment in progress as deal stage (DTFS2: 5825)
* added helper to check for in progress
* used helper to set deal stage
* added e2e test to test every page
* added relevant code to format amendment details if error on UW mangers comments page
* added to e2e tests
=> fix(DTFS2-5871-5825): Amendments - deal stage and uw managers decision fixes

azure-functions/acbs-function/acbs-facility/index.js, azure-functions/acbs-function/mappings/facility/facility-fee.js, azure-functions/acbs-function/mappings/facility/facility-loan.js
* Helper function used instead of direct property comparison in order to improve code quality.
* Introduction of exceptional handling for `FLR` and `FFFR`/`PSR`, in any case of mapping failure.
=> DTFS2-5882 : ACBS - Exception handling & helper function usage

trade-finance-manager-ui/templates/case/amendments/_macros/amendment-in-progress-bar.njk
* amendments in progress bar redirected to page not found
* added amendment.dealId so it is not undefined
=> fix(DTFS2-5824): Amendments in progress bar bug

e2e-tests/trade-finance-manager/cypress/fixtures/constants.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-automatic.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js, trade-finance-manager-api/src/constants/tasks-amendment.constant.js, trade-finance-manager-api/src/constants/teams.js
* PIM was not showing as full group name on tasks (DTFS2-5887)
* Underwriting managers task was showing set as underwriter (DTFS2-5892)
* changed PIM group constant name to be full name
* changed group of task
=> fix(DTFS2-5887/5892): Amendment task fixes

trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js, trade-finance-manager-api/src/v1/controllers/amendment.controller.js, trade-finance-manager-api/src/v1/emails/amendments/automatic-approval-email-variables.js, trade-finance-manager-api/src/v1/emails/amendments/manual-amendment-decision-email-variables.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js
* BSS amendment emails were not sending
* pointed to UKEFDealId in details collection if deal type is BSS
* added api-tests
=> fix(DTFS2-5878/5879): BSS amendments email fix

reference-data-proxy/package-lock.json, reference-data-proxy/package.json, reference-data-proxy/src/cronJobs/eStoreCronJobManager.ts, reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts, reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts, reference-data-proxy/src/v1/controllers/estore/eStore.controller.ts
Changelog:
- updated the timers for CronJobs to execute 59s after the previous function finished.
(this because we need a deploy between different API calls)
=> fix: updated the eStore timers to execute after 59s

e2e-tests/portal/cypress/fixtures/constants.js, e2e-tests/portal/cypress/integration/journeys/checker/currency-conversion-date/currency-conversion-error.spec.js, gef-ui/package-lock.json, portal-api/package-lock.json, portal-api/src/v1/validation/completeDealValidation.js, portal/package-lock.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-ui/package-lock.json
* About supply contract was showing incomplete for date in the past
* added deal to another validation file
* added some more tests
=> fix(DTFS2-5709):  Loan conversion date further fix

docker-compose.dev.yml, e2e-tests/e2e-fixtures/dateConstants.js, e2e-tests/trade-finance-manager/cypress/fixtures/constants.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/8. amendment-details-manual-approval.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-proceed.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-underwriter-declined.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-withdraw.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/amendments/amendmentsPage.js, trade-finance-manager-api/src/v1/__mocks__/amendmentVariables.js, trade-finance-manager-api/src/v1/controllers/amendment.controller.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.js, trade-finance-manager-ui/server/controllers/case/amendments/amendmentAnswers.controller.js, trade-finance-manager-ui/server/controllers/case/index.js
* effective date was not showing on amendments detail page (DTFS2-5868)
* email was not being sent for first task
* added effective date based on if automatic or manual amendment so is displayed
* added helper for sending first task email
* added api-test
=> fix(DTFS2-5888-5868): Amendments bug - effective date and first task email

e2e-tests/gef/cypress/integration/clone-gef-deal.spec.js, portal-api/.eslintrc.js, portal-api/api-tests/v1/deals/deal-clone.api-test.js, portal-api/package-lock.json, portal-api/src/v1/controllers/deal-clone.controller.js, portal-api/src/v1/gef/controllers/clone-gef-deal.controller.js
- removed `supportingInformation` from cloned deals
- added `clonedDealId` to keep track of the original deal
- removed `submissionType` from cloned deals
=> fix: removed supporting docs and submission details from cloned deals

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js, e2e-tests/trade-finance-manager/cypress/integration/pages/amendments/amendmentsPage.js, trade-finance-manager-ui/server/controllers/case/index.js, trade-finance-manager-ui/templates/case/amendments/_includes/amendment-ukef-decision-submitted-summary.njk, trade-finance-manager-ui/templates/case/amendments/_macros/amendment-ukef-decision-summary.njk, trade-finance-manager-ui/templates/case/facility/_macros/amendment-details.njk
* Added component for UW Managers decision summary
* Added component to both pages
* Added tests
=> feat(DTFS2-5910): Amendments UW Managers decision component

azure-functions/acbs-function/__mocks__/durable-functions.js, azure-functions/acbs-function/acbs-facility/index.js, azure-functions/acbs-function/acbs-http/index.js, azure-functions/acbs-function/activity-create-code-value-transaction/index.js, azure-functions/acbs-function/activity-create-deal-guarantee/index.js, azure-functions/acbs-function/activity-create-deal-investor/index.js, azure-functions/acbs-function/activity-create-deal/index.js, azure-functions/acbs-function/activity-create-facility-covenant/index.js, azure-functions/acbs-function/activity-create-facility-fee/index.js, azure-functions/acbs-function/activity-create-facility-guarantee/index.js, azure-functions/acbs-function/activity-create-facility-investor/index.js, azure-functions/acbs-function/activity-create-facility-loan/index.js, azure-functions/acbs-function/activity-create-facility-master/index.js, azure-functions/acbs-function/activity-create-party/index.js, azure-functions/acbs-function/activity-get-acbs-industry-sector/index.js, azure-functions/acbs-function/activity-get-facility-master/index.js, azure-functions/acbs-function/activity-update-facility-master/index.js, azure-functions/acbs-function/mappings/facility/facility-fee.js, azure-functions/acbs-function/mappings/facility/facility-loan.js, azure-functions/acbs-function/mappings/facility/helpers/get-loan-maximum-liability.js
* Lint fixes applied across all the files in ACBS Azure DF microservice.
=> fix(lint) : ACBS Azure DF

.gitignore, portal/server/routes/contract/bond/index.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js, trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js
Once a facility has been issued and submitted to UKEF (usually as an MIA) and if the cover start date is then subsequently amended by the bank this is not taken into consideration thus invalid GCD, PS and exposure period is calculated.
This PR aims to mitigate this issue.
* Introduced `sendToUkef` constant, evaluates whether facility properties recalculation is necessary.
* AIN
* Unissued : Skip
* Issued : Calculate and `hasBeenIssuedAndAcknowledged` set to `true`
* MIA
* Unissued : Skip
* Issued : Calculate and `hasBeenIssuedAndAcknowledged` set to `true`
* MIN : N/A
* AIN
* Unissued : N/A
* Issued : Calculate as `hasBeenIssuedAndAcknowledged` does not exists.
* MIA
* Unissued : N/A
* Issued : Calculate as `hasBeenIssuedAndAcknowledged` does not exists.
* MIN
* Unissued : N/A
* Issued : …
=> fix(DTFS2-5938) - Facility premium schedule + exposure date re-calculated

trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.js
* Task emails not sending for BSS
* changed ukefDealId variable to be either from dealSnapshot or dealSnapshot.details
* added test for BSS deal
=> fix(DTFS2-5888): BSS Task email bug fix

e2e-tests/e2e-fixtures/dateConstants.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js, trade-finance-manager-ui/server/controllers/case/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/index.js
* amendment UW decision time was 24hrs and am/pm
* changed format to 'h:mm aaa' 
* added to e2e test
=> fix(DTFS2-5935): Amendment UW decision time format

trade-finance-manager-ui/server/controllers/case/amendments/leadUnderwriter.controller.js, trade-finance-manager-ui/server/controllers/case/amendments/leadUnderwriter.test.js, trade-finance-manager-ui/server/test-mocks/amendment-test-mocks.js
* updated leadUnderwriterId so it is stored as object containing  _id and first and last name
* updated tests
=> feat(DTFS2-5945): Amendment change leadUnderwriterId to leadUnderwriter object

trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js, trade-finance-manager-api/src/v1/controllers/send-deal-decision-email.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails-gef.api-test.js, trade-finance-manager-api/src/v1/controllers/send-deal-submit-emails.js
- send MIA acknowledgements and approval confirmations to PIM
=> feat(HEL-184): send MIA acknowledgements and approval confirmations to PIM

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-bank-decision-proceed.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/add-underwriter-decision.spec.js, trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapUkefExposure.api-test.js, trade-finance-manager-api/src/graphql/reducers/mappings/facilities/mapUkefExposure.js
* amendment exposure value date was pointing at submittedDate as compared to effectiveDate
* e2e test was flaky as alert() was part of comment
* Removed the alert() from comment box
* Changed exposure value date to effective date
=> fix(DTFS2-5966): Amendment exposure value date set to effective date

.github/workflows/pr_e2e_tests.yml
* Resolved cypress dashboard issue.
* Cancel test suite, when one fails.
* Added extra containers for tests.
=> fix(DTFS2-GHA) : Improved E2E GHA

.github/workflows/pr_e2e_tests.yml
* Reverted changes applied to GHA
=> DTFS2-GHA : GHA Reverted

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js, e2e-tests/portal/cypress/integration/pages/dashboardDeals.js, e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks.spec.js, portal/server/constants/dashboard.js, portal/server/constants/index.js, portal/server/constants/sort.js, portal/server/controllers/dashboard/deals/index.js, portal/server/controllers/dashboard/deals/index.test.js, portal/server/controllers/dashboard/sort/helpers.js, portal/server/routes/dashboard.js, portal/templates/dashboard/_macros/dashboard-deals-table.njk, portal/templates/dashboard/deals.njk
* Added ability to sort deals by exporter.  It was handled by component but that only sorted the page, not all deals.  Now all exporters are sorted alphabetically
* Added e2e test
=> feat(DTFS2-5215): Portal deal exporter sorting

e2e-tests/gef/cypress/integration/about-facility.spec.js, gef-ui/server/controllers/about-facility/index.js, gef-ui/server/controllers/about-facility/index.test.js
* entering special characters on GEF facilities took you to problem page
* Used joi to validate facility date inputs
* Added tests
=> fix(DTFS2-6047): GEF coverStartDate coverEndDate validation

utils/mock-data-loader/.env.azure_dev, utils/mock-data-loader/.env.azure_test, utils/mock-data-loader/.env.local
Various `.env` files were visible on VCS.
* Removed `.env` files.
=> fix: Removed frivolous env files

e2e-tests/portal/cypress/integration/journeys/dashboard/dashboard-deals/dashboard-deals-sort.spec.js, e2e-tests/submit-to-trade-finance-manager/cypress/integration/journeys/portal/submit-deal-with-issued-facilities/submit-deal-with-issued-facilities.spec.js, portal/server/controllers/dashboard/deals/index.js, portal/server/controllers/dashboard/deals/index.test.js, portal/templates/dashboard/_macros/dashboard-deals-table.njk
* Sort button had to be clicked on second etc pages to sort
* Added sortBy to the session
=> fix(DTFS2-6038): Dashboard sorting on other pages

azure-functions/acbs-function/helpers/mandatoryFields.js, azure-functions/acbs-function/package-lock.json
Mandatory field computation does not take into account field with value `0` which is an acceptable value.
* `null`, `undefined` and `empty` string check.
* Updated `package-lock.json`.
=> fix(DTFS2-ACBS): Mandatory field verfication + Updated Package lock

e2e-tests/gef/cypress/integration/unissued-facilities-change-all-AIN.spec.js, gef-ui/server/controllers/unissued-facilities/validation.js, gef-ui/server/controllers/unissued-facilities/validation.test.js, gef-ui/server/utils/coverDatesValidation.helper.js, gef-ui/server/utils/coverDatesValidation.helper.test.js
* Issuing facility page went to error page if special characters in date boxes
* Added validation on issue facility page if errors 
* Added helper
* Added tests
=> fix(DTFS2-6047): GEF validation issue facility 

e2e-tests/gef/cypress/fixtures/mocks/mock-facilities.js, e2e-tests/gef/cypress/integration/about-facility.spec.js, trade-finance-manager-api/src/v1/controllers/amend-issued-facility.js
Due to on-going business requirement finalisation pertaining to PS/FF calculation upon a facility amendment, it has been agreed with the wider team to disabled the calculation for interim.
* PS/FF calculation and facility TFM object update has been disabled.
* TODO comment has been added.
=> fix(DTFS2-4614): Facility Amendment - Premium Schedule/Fixed Fee calculation disabled

e2e-tests/portal/cypress/integration/journeys/maker/bond/bond-financial-details.spec.js, portal-api/api-tests/v1/validation/conversion-rate-date.api-test.js, portal-api/src/v1/validation/bond-rules/facility-stage-issued-rules/requested-cover-start-date.js, portal-api/src/v1/validation/fields/currency-not-the-same-as-supply-contract-rules/conversion-rate-date.js
* Cover Start Date month did not show correct error
* Conversion date did not show error if invalid dates
* Added validation for conversion date
* Added some extra tests
=> fix(DTFS2-6046): BSS dates validation

e2e-tests/e2e-fixtures/dateConstants.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-changes-multiple-single-amendments.spec.js
* E2E tests failing because of dates being close 
* Fixed tests by making dates further apart (months in advance)
=> fix: TFM failing e2e tests

azure-functions/acbs-function/acbs-amend-facility-loan-record/function.json, azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js, azure-functions/acbs-function/acbs-amend-facility-master-record/function.json, azure-functions/acbs-function/acbs-amend-facility-master-record/index.js, azure-functions/acbs-function/acbs-amend-facility/index.js, azure-functions/acbs-function/activity-update-facility-loan-amount/index.js
Facility amendment could consists of both value increment or value decrement.
Value increment works as expected, however decrement require facility records amendment to be swapped.
In a standard value increment records are amended in following sequence:
* FMR
* FLR
However, in case of decrement records are amended in reverse:
* FLR
* FMR
* Execution sequence are swapped upon operation type.
* GEF facility amendment bug resolution with regards to 10% of the amendment value and condition update for payload construction.
* Documentation update
=> feat(DTFS2-6023): Facility amendment SOFs

portal-api/src/v1/gef/controllers/portal-activities.controller.js
Added optional chaining for `userProfile`.
=> fix: Added optional chaining where userProfile will be null

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-AIN.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA-all-tasks.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/tasks/tasks-MIA.spec.js, trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.component-test.js, trade-finance-manager-ui/templates/case/tasks/_macros/tasks-table.njk, trade-finance-manager-ui/templates/case/tasks/tasks.njk
* Risk raised that any user could complete any task
* Locked tasks to user group
* Added e2e tests
'Approve or decline the deal' task is only to be completed by UW Managers which this PR resolves by locking the task to only users in the UW Managers group
=> fix(DTFS2-6108): tasks locked to user groups

e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-automatic.spec.js, e2e-tests/trade-finance-manager/cypress/integration/journeys/case/amendments/amendment-tasks-manual.spec.js, trade-finance-manager-ui/templates/case/amendments/_macros/tasks-table-amendments.njk
* Amendment tasks were not locked
* Locked amendment tasks to user group on task
File all emails about this amendment request should only be locked to PIM users
=> fix(DTFS2-6108): Amendment tasks lock

docker-compose.yml, dtfs-central-api/src/createApp.js, trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapDeals.js, trade-finance-manager-api/src/graphql/reducers/mappings/deal/mapTotals.js
DTFS central API resource starvation has been an issue with returning GQL data.
* Express json limit has been increased to `10mb`
* Empty facility object check
=> fix(DTFS2-6116): Object validation + DTFS Central API Resource upgrade

README.md, dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-ui/Dockerfile
- updated NodeJS to `v18.12-alpine3.16`
=> chore: updated Nodejs to `v18.12-alpine3.16`

gef-ui/server/controllers/unissued-facilities/validation.js, gef-ui/server/controllers/unissued-facilities/validation.test.js
* GEF issuing facility took submission date for MIA as compared to now for validating for coverStartDate
* Changed threemonthslimit to start from now for MIA
* Added unit tests
=> fix(DTFS2-6142): GEF validation coverStartDate issue facility MIA

e2e-tests/gef/cypress/e2e/review-ukef-approval-with-issued-and-unissued-facilities-MIA-and-resubmit-to-ukef.spec.js, gef-ui/server/utils/facility-helpers.js, gef-ui/server/utils/facility-helpers.test.js
* Unissued facilities table showed submission date deadline for MIA
* Refactored unissued facilities deadline 
* Changed MIA to use now as compared to submission date
* Updated test
=> fix(DTFS2-6142): Unissued Tables deadline

e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/dashboard-facilities-filter-created-by-you.spec.js, e2e-tests/portal/cypress/e2e/pages/dashboardFacilities.js, portal/server/constants/field-names.js, portal/server/controllers/dashboard/facilities/facilities-filters-query.js, portal/server/controllers/dashboard/facilities/facilities-filters-query.test.js, portal/server/controllers/dashboard/facilities/selected-filters.js, portal/server/controllers/dashboard/facilities/template-filters.js, portal/server/controllers/dashboard/facilities/template-filters.test.js
* Added created by you logic to facilities page in filters box
* Added correct matching query as calling joined deals table
* Added e2e test and unit tests
=> feat(DTFS2-5960): Portal facilities created by you

e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/7. amendment-details-automatic-approval.spec.js, e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/8. amendment-details-manual-approval.spec.js, e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/add-bank-decision-proceed.spec.js
Tenor being displayed on TFM is correct, however tenor hard-coded in E2E is a month out due to extra days.
* Changed tenor from `25 months` to `26 months`
=> fix(e2e-tenor): Fixed tenor

portal/templates/_partials/before-you-start.njk
A new bank has board and signed MGA.
* Added bank name to the portal UI login screen NJK template.
=> feat(DTFS2-6224): Added Emirates NBD Bank

trade-finance-manager-api/src/graphql/schemas/index.js, trade-finance-manager-ui/server/graphql/queries/deal-query.js, trade-finance-manager-ui/server/nunjucks-configuration/filter-dashIfEmpty.js, trade-finance-manager-ui/templates/case/_macros/case-summary-ndb.component-test.js, trade-finance-manager-ui/templates/case/_macros/case-summary-ndb.njk, trade-finance-manager-ui/templates/case/_macros/case-summary.component-test.js, trade-finance-manager-ui/templates/case/_macros/case-summary.njk, trade-finance-manager-ui/templates/case/case.component-test.js, trade-finance-manager-ui/templates/case/case.njk, trade-finance-manager-ui/templates/case/deal/deal.component-test.js, trade-finance-manager-ui/templates/case/deal/deal.njk
* Added new summary for NDB with rearranged columns and without deal stage
* Removed eligibility criteria if NDB
* Added component tests
=> feat(DTFS2-6199): NDB deal page TFM

trade-finance-manager-api/src/constants/index.js, trade-finance-manager-api/src/constants/tasks-ndb-amendment.constant.js, trade-finance-manager-api/src/v1/controllers/amendment.controller.js, trade-finance-manager-api/src/v1/helpers/amendment.helpers.api-test.js, trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.api-test.js, trade-finance-manager-api/src/v1/helpers/create-tasks-amendment.helper.js
* Added tasks for non delegated banks amendments
* Added to controller to process these tasks
* Added facility call to check if non-delegated bank flag is set
* Added api-test
=> feat(DTFS2-6237): TFM Non Delegated Banks amendment tasks

e2e-tests/e2e-fixtures/dateConstants.js, e2e-tests/gef/cypress/e2e/application-activities-AIN.spec.js, e2e-tests/gef/cypress/e2e/application-activities-MIA.spec.js, e2e-tests/gef/cypress/e2e/application-details.spec.js, e2e-tests/gef/cypress/e2e/clone-gef-deal.spec.js, e2e-tests/gef/cypress/e2e/submit-to-checker-mia.spec.js, e2e-tests/gef/cypress/e2e/submit-to-ukef.spec.js, e2e-tests/portal/cypress/e2e/journeys/reports/review-ukef-decision.spec.js, e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/activities/activities.spec.js, e2e-tests/trade-finance-manager/cypress/fixtures/mock-gef-deals.js
Replaced date constant LLL  with MMM.
Added extra constants:
* twentyFiveDaysAgo,
* twentyFiveDaysAgoUnix,
* twentyFiveDaysAgoFormatted,
* thirtyFiveDaysAgo,
* thirtyFiveDaysAgoUnix,
* thirtyFiveDaysAgoFormatted,
* todayFormattedShort
=> chore(DTFS2-6049) refactor date constants for e2e tests

reference-data-proxy/src/reference-data/countries.ts
- disabled more countries from Portal:
Belarus
Bosnia and Herzegovina
Burundi
Central African Republic
Congo
Guinea
Guinea Bissau
Iran
Iraq
Korea DPR
Mali
Nicaragua
Palestinian National Authority
Russian Federation
Syrian Arab Republic
Venezuela
Western Sahara
=> feat: disabled additional countries from Portal

azure-functions/acbs-function/acbs-amend-facility/index.js, azure-functions/acbs-function/acbs-issue-facility/index.js, azure-functions/acbs-function/acbs/index.js, azure-functions/acbs-function/package-lock.json, azure-functions/acbs-function/package.json
Amendments should only be processed for `Issued` `07` facility stage on ACBS.
A risk expired `08` facility was amended which should be avoided.
* Facility stage verification - Only `07` facilities will be amended.
* Main and facility issuance entry point exceptional handling.
* `axios` version downgraded, as version `1.2.2` has introduced breaking changes.
=> feat(DTFS2-6225): ACBS Exceptional handling

azure-functions/acbs-function/acbs-amend-facility-loan-record/index.js, azure-functions/acbs-function/acbs-amend-facility/index.js
Facility loan record should only be amended for facility type `bond`.
* Ensure facility is type `bond`.
* Removed `bond` verification from `acbs-amend-facility-loan-record` DAF.
=> feat(DTFS2-6283): Bond - Facility loan record amendment

azure-functions/acbs-function/package.json, azure-functions/number-generator-function/.eslintignore, azure-functions/number-generator-function/.eslintrc.js, azure-functions/number-generator-function/activity-get-number-from-generator/index.js, azure-functions/number-generator-function/package.json, azure-functions/number-generator-function/testing/defaultContext.js, azure-functions/number-generator-function/testing/defaultTimer.js, package-lock.json, portal-api/package-lock.json
Various npm security vulnerabilities have been flagged by `npm audit` for root and other micro-services.
* Package version bumps.
* `number-generator` microservice lint fixes.
* Root and `portal-api` npm audit fixes.
=> feat(npm-lint): Various npm audit and lint fixes

portal/server/routes/static.js
`security.txt` file expired.
* `Expires` have been updated to `2024-02-07`.
* Add `Encrypt` property.
=> chore(security.txt): Expire updated

trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/dealStage.js, trade-finance-manager-api/src/v1/controllers/deal-add-tfm-data/index.js, trade-finance-manager-api/src/v1/controllers/should-update-deal-from-MIA-to-MIN.js
A deal has been submitted with submission count `2` to TFM, despite being the first submissions.
* Property check
* Additional logging
* Code simplification
=> fix(tfm): Deal submission logging

dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-ui/Dockerfile
- updated NodeJS to v`18.14-alpine3.17`
=> chore: updated NodeJS to v`18.14-alpine3.17`

README.md
Missing cookie documentation
Following cookies attributes have been added to `README.md`
* Cookies flag
* Cookies naming convention
=> chore(cookie): Added cookie related documentation

azure-functions/acbs-function/README.md
README.md documentation update.
=> chore(docs): Updated documentation

dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-ui/Dockerfile
This reverts commit 715ad07dcafd19ad36e087e2e03324d9b35ef288.
=> Revert "chore: updated NodeJS to v`18.14-alpine3.17` (#1317)"

azure-functions/acbs-function/package-lock.json, azure-functions/acbs-function/package.json, azure-functions/number-generator-function/package-lock.json, azure-functions/number-generator-function/package.json, dtfs-central-api/package-lock.json, dtfs-central-api/package.json, gef-ui/package-lock.json, gef-ui/package.json, package-lock.json, package.json, portal-api/package-lock.json, portal-api/package.json, portal/package-lock.json, portal/package.json, reference-data-proxy/package-lock.json, reference-data-proxy/package.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-api/package.json, trade-finance-manager-ui/package-lock.json, trade-finance-manager-ui/package.json, utils/data-migration/package.json, utils/mock-data-loader/package.json
NPM updates across all micro-services
* `package.json` dependencies update.
* `node` and `npm` engine version, now points to latest versions.
=> chore(npm): NPM updates

reference-data-proxy/src/cronJobs/eStoreDealFolderCreationJob.cron.ts, reference-data-proxy/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts
- updated the eStore intervals (to match the changes in its API)
- updated the stage when TFM deals are updated
=> fix: updated the eStore intervals

azure-functions/acbs-function/package-lock.json, dtfs-central-api/package-lock.json, gef-ui/package-lock.json, package-lock.json, portal-api/package-lock.json, portal/package-lock.json, reference-data-proxy/package-lock.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-ui/package-lock.json
=> chore(npm-updates): Various dependecies updates

azure-functions/acbs-function/package-lock.json, dtfs-central-api/package-lock.json, gef-ui/package-lock.json, package-lock.json, portal-api/package-lock.json, portal/package-lock.json, reference-data-proxy/package-lock.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-api/src/v1/content-strings/index.js, trade-finance-manager-ui/package-lock.json
Following GEF ECs have been updated in line with the MGA:
* EC 2 15
* EC 1.5 15
* Hard coded content string updated as per the ticket.
* Dependencies updates.
=> fix(DTFS2-6352): TFM GEF EC 2.15 updated to reflect MGA

.husky/pre-commit, dtfs-central-api/Dockerfile, gef-ui/Dockerfile, portal-api/Dockerfile, portal/Dockerfile, reference-data-proxy/Dockerfile, trade-finance-manager-api/Dockerfile, trade-finance-manager-ui/Dockerfile
- updated NodeJS to v20.0.0-alpine3.17
=> chore: updated NodeJS to `v20.0.0-alpine3.17`

portal-api/src/reference-data/__mocks__/countries.js, reference-data-proxy/src/reference-data/countries.ts
Latest request to remove countries.
* set `disabled` flag to `true` for countries request.
=> feat(DTFS2-6439): countries disabled

docker-compose.yml, reference-data-proxy/api-tests/v1/currency-exchange-rate.api-test.ts, reference-data-proxy/src/utils/swagger-definitions/currency-exchange-rate.ts, reference-data-proxy/src/v1/controllers/currency-exchange-rate.controller.ts, reference-data-proxy/src/v1/routes/external-apis.route.ts, trade-finance-manager-api/src/v1/__mocks__/api.js, trade-finance-manager-api/src/v1/controllers/convert-facility-currency.js, trade-finance-manager-api/src/v1/controllers/deal.convert-deal-currencies.js, trade-finance-manager-ui/templates/case/facility/_macros/premium_schedule.njk
Currency exchange for non GBP source currencies.
* Refactored currency inversion for non-GBP i.e. `USD -> GBP`
* Enhanced api tests.
* Improved documentation.
Renamed PS title from source currency to GBP since they are calculated in GBP.
=> fix(currency-exchange-rate): Currency exchange rate calculation

azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js
Exposure period calculation has not be correct especially for `BSS/EWCS` deals.
* Return `exposurePeriodInMonths` if already calculated by TFM.
=> fix(acbs): exposure period calculation

e2e-tests/portal/cypress/e2e/journeys/admin/create-user/create-a-user.spec.js, e2e-tests/portal/cypress/fixtures/users.js, portal-api/api-tests/v1/users/users.api-test.js
Various vulnerabilities test coverage has been missing.
* Added cypress test for NoSQL injection input
* Added api-test for users.api-test for login with NoSQL injection
=> fix(DTFS2-6147): vulnerabilities test coverage 

.github/workflows/development_deploy.yml, .github/workflows/staging_deploy.yml
=> fix(typo): GHA job name

trade-finance-manager-api/src/v1/controllers/amendment.controller.js
I found a bug when loading the homepage in TFM where getting all amendments in progress was failing.
Change req.query -> req.params as the status is in path not query
=> fix(DTFS2): Fix get all amendments endpoint

external-api/src/v1/controllers/acbs.controller.ts
=> fix(external-api): url typo fixes

gef-ui/templates/includes/footer.njk, gef-ui/templates/partials/accessibility-statement.njk, portal/templates/_partials/footer.njk, portal/templates/accessibility-statement.njk, trade-finance-manager-ui/templates/_partials/footer.njk, trade-finance-manager-ui/templates/accessibility-statement.njk
Footer telephone number to be removed.
* Removed from footer and accessibility statement NJK templates:
* `gef-ui`
* `portal`
* `trade-finance-manager-ui`
=> feat(UI): removed footer telephone number

.github/workflows/development_infrastructure.yml, .github/workflows/production_infrastructure.yml, .github/workflows/staging_infrastructure.yml
Missing JWT key
* Added `JWT_VALIDATING_KEY` to `tfm-api`.
=> fix(iac): added jwt validating key

trade-finance-manager-api/src/v1/api.js, trade-finance-manager-ui/server/controllers/deals/index.js, trade-finance-manager-ui/server/controllers/facilities/index.js
An `Unauthorised` error message does satisfy `.length > 0` condition given `String` type in nature.
* Added `Array.isArray()` validation to compound condition for both `deals` and `facilities`.
* Added **temporary** console info for `dev` debug only.
* Replaced `%O` with `%S`
=> fix(tfm): array validation

azure-functions/acbs-function/package-lock.json, azure-functions/number-generator-function/package-lock.json, dtfs-central-api/package-lock.json, external-api/package-lock.json, gef-ui/package-lock.json, portal-api/package-lock.json, portal/package-lock.json, trade-finance-manager-api/package-lock.json, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-ui/package-lock.json, trade-finance-manager-ui/server/controllers/case/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/index.js, trade-finance-manager-ui/server/controllers/helpers/amendments.helper.js, utils/mock-data-loader/api.js, utils/mock-data-loader/centralApi.js, utils/mock-data-loader/gef/api.js, utils/mock-data-loader/tfm/api.js
Improve code quality
* Code simplification
* Code consistency
* Dependencies updates
=> refactor(code): code simplification

e2e-tests/trade-finance-manager/cypress/e2e/journeys/case/amendments/add-underwriter-decision.spec.js, trade-finance-manager-ui/server/index.js, trade-finance-manager-ui/server/routes/case/index.js, trade-finance-manager-ui/server/routes/case/index.test.js
HTML code in inputs was added to database and displayed on page
* Added santize-xss to index.js so used across UI
* Added to e2e tests
=> fix(tfm-exception-text): TFM UI - Sanitise-xss in index.js

trade-finance-manager-api/src/v1/validation/feedback-rules/email-address.js
* TFM API feedback email regex was inefficient
* Changed to use JOI for email validation
=> fix(tfm-api-email): JOI validation for feedback email

portal-api/src/v1/gef/controllers/validation/application.js
There were 3 security issues to tackle, two to do with returning user input back to the user and one with SSRF
Fix remaining issues by not returning user input and validating inputs used in urls.
=> DRAFT: security: Fix critical security issues

external-api/src/cronJobs/eStoreCronJobManager.ts, external-api/src/cronJobs/eStoreDealFolderCreationJob.cron.ts, external-api/src/cronJobs/eStoreFacilityFolderCreationJob.cron.ts, external-api/src/cronJobs/eStoreSiteCreationJob.cron.ts, external-api/src/cronJobs/eStoreTermStoreAndBuyerFolder.cron.ts, external-api/src/v1/controllers/acbs.controller.ts, external-api/src/v1/controllers/companies-house.controller.ts, external-api/src/v1/controllers/currency-exchange-rate.controller.ts, external-api/src/v1/controllers/email.controller.ts, external-api/src/v1/controllers/estore/eStore.controller.ts, external-api/src/v1/controllers/exposure-period.controller.ts, external-api/src/v1/controllers/industry-sectors.controller.ts, external-api/src/v1/controllers/ordnance-survey.controller.ts, external-api/src/v1/controllers/party-db.controller.ts, external-api/src/v1/controllers/party-urn.controller.ts, external-api/src/v1/controllers/premium-schedule.controller.ts
* External API did not have correct format for console.errors and console.info
* Used %s and %O for console.errors and console.info in external-api
=> fix(External-API-console): Correct format for console.info and errors

infrastructure/arm_templates/function-number-generator/errors.json, infrastructure/arm_templates/function-number-generator/parameters.json, infrastructure/arm_templates/function-number-generator/template.json, infrastructure/resource_group_level/main.bicep, infrastructure/resource_group_level/modules/function-number-generator.bicep, infrastructure/subscription_level/main.bicep
This card covers 
* Implementing the function-number-generator Azure Function infrastructure in Bicep
* The function-number-generator Azure Function infrastructure is implemented in Bicep
* Environment variables have been checked and categorised
=> Feat(FN-420): function-number-generator in Bicep

infrastructure/resource_group_level/main.bicep, infrastructure/resource_group_level/modules/function-acbs.bicep, infrastructure/resource_group_level/modules/function-number-generator.bicep, infrastructure/resource_group_level/modules/webapps/dtfs-central-api.bicep, infrastructure/resource_group_level/modules/webapps/external-api.bicep, infrastructure/resource_group_level/modules/webapps/gef-ui.bicep, infrastructure/resource_group_level/modules/webapps/portal-api.bicep, infrastructure/resource_group_level/modules/webapps/portal-ui.bicep, infrastructure/resource_group_level/modules/webapps/trade-finance-manager-api.bicep, infrastructure/resource_group_level/modules/webapps/trade-finance-manager-ui.bicep
* updating variable changes from updates to main
* environment variables from secrets updated
* environment variables from vars updated
=> feat(FN-923): update infrastructure with main - vars

portal/templates/_partials/before-you-start.njk
Added `Virgin Money UK` to the portal.
=> feat(DTFS2-6566): added virgin money bank to the portal

.github/workflows/publish.yml
Release/publish action is failing because of json error
Added comma
=> fix: fixing json format error in github action publish.yml

azure-functions/acbs-function/acbs-amend-facility/index.js, azure-functions/acbs-function/acbs-facility/index.js, azure-functions/acbs-function/acbs-issue-facility/index.js, azure-functions/acbs-function/acbs/index.js, azure-functions/acbs-function/constants/deal.js, external-api/src/constants/number-generator.constant.ts, external-api/src/v1/controllers/estore/eStore.controller.ts
Ensure UKEF ID `PENDING` or `100000` are not send to ACBS or eStore for processing.
* Added deal and facility ID validation in ACBS DOFs.
* Moved `100000` to constant in `eStore`.
=> fix(ukefid): UKEF ID validation

.github/workflows/feature_deploy.yml
* deploying the app code which is currently separate from deploying the infrastructure.
* app code is deployed in the same way as for the dev environment
=> feat(FN-1133): deploy app code

.github/workflows/feature_deploy.yml
* deploying application code via a matrix strategy to limit parallelism and avoid throttling errors
* application code is now deployed via a matrix strategy with limited parallelism.
=> feat(FN-1113): matrix deploy

.github/workflows/feature_deploy.yml
* avoiding a restart of webapps after a slot swap
* restart command removed
* updated actions/checkout version
=> feat(FN-1172): do not restart webapps after a slot swap

.github/workflows/feature_deploy.yml
* deploying application code to feature environment
* adding GHA workflow to deploy app code to feature on push to `main-stbr`
NOTE: This is merely cherry picking the relevant commits from the Bicep branch `feat/DTFS2-6422`.
=> feat(FN-1173): deploy app code from main stbr

infrastructure/resource_group_level/main.bicep, infrastructure/resource_group_level/modules/cosmosdb.bicep, infrastructure/resource_group_level/modules/function-acbs.bicep, infrastructure/resource_group_level/modules/function-number-generator.bicep, infrastructure/resource_group_level/modules/privatelink-azurewebsites-net.bicep, infrastructure/resource_group_level/modules/privatelink-mongo-cosmos-azure-com.bicep, infrastructure/resource_group_level/modules/redis.bicep, infrastructure/resource_group_level/modules/storage.bicep, infrastructure/resource_group_level/modules/webapps/webapp.bicep
* removing unnecessary and redundant code
* Various comments, removed, as well as superfluous Bicep, and some confirmed unnecessary infrastructure
=> chore(FN-684): Remove unnecessary code

infrastructure/resource_group_level/main.bicep, infrastructure/resource_group_level/modules/clamav.bicep, infrastructure/resource_group_level/modules/vnet.bicep, infrastructure/resource_group_level/modules/webapps/portal-api.bicep, infrastructure/resource_group_level/modules/webapps/portal-ui.bicep
We need to amend the Bicep described infrastructure to work with the ETETF Beta work
* adding ClamAV infrastructure.
* ClamAV ACI is created in a private vnet.
=> feat(FN-1145): add clamav infra

README.md
We've recently had a new team member set up the codebase. There were some steps in the README that weren't clear enough and led to errors during setup.
I have added more clarity to the README in the areas that weren't clear enough.
=> docs: improve setup instructions in the README

external-api/api-test.jest.config.js
Update `api-test.jest.config.ts` file for external api
=> fix(DTFS2): update external api api jest config

README.md, portal-api/README.md, portal/README.md
The changes we've made to Portal login process justify the documentation of the new process
Added readme docs
=> feat(DTFS2-6758): update readme with login implementation

portal-api/src/v1/controllers/utilisation-report-service/utilisation-report-upload.controller.js
Bug was introduced which meant that `reportSubmittedBy ` could not be populated in the email template for the confirmation of report upload email to banks
Passed in the `parsedUser` to the sendEmail function
=> feat(FN-995): fix report submitted by param

.github/workflows/bicep_az_deployment_group.yml, .github/workflows/bicep_deploy.yml, .github/workflows/bicep_workflow_feature.yml, infrastructure/resource_group_level/main.bicep
The new environment variable `PORTAL_UI_URL` is added by #2265 & needs to be added to the bicep files
* Added `PORTAL_UI_URL` to `.github/workflows/bicep_az_deployment_group.yml`, `.github/workflows/bicep_workflow_feature.yml` and `infrastructure/resource_group_level/main.bicep`
=> feat(DTFS2-6762): add environment variable portal-ui-url

portal/jest.config.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.test.js, portal/server/helpers/getOneIndexedMonth.js, portal/server/helpers/getOneIndexedMonth.test.js, portal/server/helpers/index.js
Report month is stored in the session, it was indexed at 0 but we want to use index 1 to make it easier to read
When we set the month increase the value by 1
=> feat(FN-970): fix month indexing in session

portal/package-lock.json
package lock in portal was out of date.
updated package lock
=> chore(DTFS2-NONE): update package-lock for portal

dtfs-central-api/src/v1/controllers/bank/get-bank.controller.js, dtfs-central-api/src/v1/routes/bank-routes.js, portal-api/api-tests/api.js, portal-api/api-tests/v1/utilisation-report-service/utilisation-report-upload.api-test.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-validator.test.js, portal/templates/utilisation-report-service/utilisation-report-upload/utilisation-report-upload.njk, trade-finance-manager-api/src/v1/api.js
We need to update the title of the upload report page
Update the title of the upload report page
=> feat(FN-1507): update title on upload report page

dtfs-central-api/src/drivers/db-client.js, dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-reports.controller.js, dtfs-central-api/src/v1/controllers/utilisation-report-service/upload-utilisation-report.controller.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js
We weren't using transactions when saving data so if one call saved data could be in a bad state
Use mongodb transactions and add some misc. fixes/logging
=> Fix: use mongodb transactions

.github/workflows/test.yml, dtfs-central-api/src/drivers/db-client.js, e2e-tests/support/db-client.js, external-api/src/database/mongo-client.ts, portal-api/src/drivers/db-client.js, portal-api/test-helpers/api-test-helpers/database/database-client.js, trade-finance-manager-api/src/drivers/db-client.js, utils/data-migration/export-tables.js, utils/data-migration/helpers/database.js, utils/mock-data-loader/api.js, utils/mock-data-loader/database/database-client.js
We have changed mock data loader to interact directly with mongodb. This has caused issues in the pipeline as we are not allowing enough time for mongodb to spin up
I've bumped up the existing wait timer
Removed depreciated options in mongodb connection
=> fix(DTFS2-NONE): fix pipeline

.github/workflows/feature_deploy.yml, azure-functions/acbs-function/package-lock.json, azure-functions/number-generator-function/package-lock.json, package-lock.json, package.json, portal/server/api.js, portal/server/routes/middleware/validateRole/index.js, portal/templates/admin/user-edit.njk
Fix any issues from the most recent main -> main-stbr merge
=> fix: add back eslint parser typescript defs

portal/server/controllers/utilisation-report-service/utilisation-report-upload/index.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-status.js
The next due report period due date was being computed as the tenth day of the reporting period month which isn't correct.
Updates the controller and relevant helper functions to compute the correct report period due date.
=> fix: get correct report period due date

infrastructure/resource_group_level/modules/cosmosdb.bicep, infrastructure/resource_group_level/modules/storage.bicep
- In E2ETF we have created some new collections and a file share which need to be reflected in the Bicep code
=> feat(FN-1501): add new collections and fileshare to bicep infra

dtfs-central-api/api-test.jest.config.js, dtfs-central-api/api-tests/v1/utilisation-reports/get-utilisation-report.api-test.js, dtfs-central-api/src/utils/string.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/put-utilisation-report-status.controller.ts, e2e-tests/tfm/cypress/e2e/pages/facilityPage.js, external-api/api-tests/v1/bank-holidays.api-test.ts
Some tests are failing following the merge of `main` into `main-stbr-tfm-5`.
Fixes the relevant tests.
=> chore(merge): fix tests on main-stbr-tfm-5

.github/workflows/publish.yml
Add `style` to publish to allow `style/**/*` branches to be included in `CHANGELOG.MD`.
* Added `style` to `publish.yml`.
=> feat(DTFS2-6897): added style to  publish.yml

.github/workflows/publish.yml
Syntax error
* Added missing command
=> fix(publish): added missing comma

.github/workflows/publish.yml, .github/workflows/release.json, README.md
Upgrade auto release version syntax to `v4`
* Syntax upgrade for `v4`
* Created `release.json` manifest file.
* Added badges to `README.md`
=> fix(gha): `release-please` v4 upgrade

.github/workflows/feature_deploy.yml
- During feature deployment dunction-app deployments fail so the whole action is failing
=> feat(fn 692): disable function apps in feature deployments

.github/workflows/feature_deploy.yml
During feature deployment function-app deployments fail so the whole action is failing
=> feat(FN-692): disable function apps in feature deployments

trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-for-bank.component-test.js, trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-reports.component-test.js, trade-finance-manager-ui/server/constants/index.js, trade-finance-manager-ui/server/constants/primary-navigation-items.ts, trade-finance-manager-ui/server/constants/primary-navigation-keys.ts, trade-finance-manager-ui/server/controllers/deals/index.js, trade-finance-manager-ui/server/controllers/deals/index.test.js, trade-finance-manager-ui/server/controllers/facilities/index.js, trade-finance-manager-ui/server/controllers/facilities/index.test.js, trade-finance-manager-ui/server/controllers/utilisation-reports/index.test.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts
Adds a new constant to TFM UI which contains the names of the primary navigation items and updates all occurrences of `activePrimaryNavigation` to use the new constant.
=> feat(FN-1613): introduce primary navigation constant

dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.test.ts, dtfs-central-api/src/services/repositories/utilisation-reports-repo/utilisation-reports-repo.ts
[FN-1051](https://ukef-dtfs.atlassian.net/browse/FN-1051)
Correct the DB query to get open reports (details in file)
=> fix(FN-1051): correct open reports DB query

.github/workflows/deployment.yml
Ensure the deployment variable is `workflow_run` workflow reference branch
* Updated reference variable to `event.workflow_run.head_branch`.
=> fix(deployment): updated environment variable reference name

.github/workflows/deployment.yml
Rectify functions swap slot container source image path
* Updated functions slot source image path
=> fix(deployment): functions slot container source image

.github/workflows/deployment.yml
Update main-stbr-tfm-5 with most recent main changes
=> chore: update stbr tfm 5 with recent changes

.github/workflows/bicep_workflow_feature.yml, infrastructure/resource_group_level/modules/webapps/webapp.bicep
Enable healthcheck on web apps
Add healthCheckPath to siteConfig on `Microsoft.Web/sites` resource
=> feat(FN-1261): enable healthcheck on webapps

.github/workflows/feature_deploy.yml
We want to deploy to the feature environment when changes are made to the refactor feature branch.
=> feat(FN-1549): set feature branch to deploy to feature env

.github/workflows/deployment.yml, .github/workflows/feature_deploy.yml
[FN-1856](https://ukef-dtfs.atlassian.net/browse/FN-1856)
Adds running of SQL migrations to the deployment pipelines.
=> feat(FN-1856): run sql migrations in deployment pipelines

.github/workflows/deployment.yml, .github/workflows/feature_deploy.yml
Following the introduction of [npm workspaces](https://github.com/UK-Export-Finance/dtfs2/pull/2596) the context that we run microservice Dockerfiles has been updated to be the root of the project. This is done because Dockerfiles now pull in shared code from the `libs` directory, with everything being installed using root `package.json` npm workspace scripts.
Update the GitHub Actions `deployment.yml` and `feature_deploy.yml` scripts to update the run context, as mentioned above.
=> feat(FN-2239): update deployment scripts to set workspace context

dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.test.ts, dtfs-central-api/src/scheduler/jobs/create-utilisation-reports/index.ts
For the job to upload reports, an error was being thrown in `dtfs-central-api` due to reporting schedules not existing for certain banks.
Any bank which has `isVisibleInTfmUtilisationReports` set to `true` should have a defined reporting schedule, so this PR adds filtering to the banks to make sure that only those banks are checked.
=> feat(FN-1947): only upload reports for banks which are visible in TFM

.github/workflows/feature_deploy.yml, dtfs-central-api/src/drivers/db-client.ts, dtfs-central-api/src/services/changeStream/setupChangeStream.ts
On the azure cosmosdb it's not running a version of mongo that can watch the whole database
Update the code to iterate over collections in the database and watch them individually
=> feat(DTFS2-6965): iterate over collections in database to set up changestream

utils/mock-data-loader/api.js
Include a summary of the changes and related feature(s) or issue(s).
List all changes made to the codebase.
=> fix(DTFS2-NONE): fix error handling in mock data loader

.github/workflows/lint.yml, .github/workflows/sca.yml, .github/workflows/test.yml, azure-functions/acbs-function/helpers/date.format-date.test.js, azure-functions/acbs-function/helpers/date.js
Azure functions were failing to create deals. This was due to an issue with dates, and how we parse them.
When we create a deal in azure functions we pass `submissionDate`, which is an `epoch`, through `formatDate` returning an `iso date time as string`. Later in the deal creation process in azure functions, we call the same `formatDate` function on this newly created `iso date time as string`. This caused an `invalidDate` to be created, and lead to the deal failing to create.
We would expect this `iso date time as string` to return a `formatted date` when parsed through `formatDate`
We added handling to allow `formatDate` to parse `iso date time as sting`s
We've added test cases to ensure this is fixed, as well as running the data from the bug report locally to ensure it returns expected …
=> fix(dtfs2-7063): facility id record are missing in acbs

.github/workflows/deployment.yml, .github/workflows/test.yml
We need to release to dev from release-1.5 to help QA
=> chore(DTFS2): set up release branch deployments

portal/server/routes/contract/eligibility/submittedDocumentationMatchesOriginalData.js, portal/server/routes/contract/eligibility/submittedDocumentationMatchesOriginalData.test.js
=> chore(merge): merge `DTFS2-70621 to `release-1.5`

portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.js, portal/server/controllers/utilisation-report-service/utilisation-report-upload/utilisation-report-cell-validators/generate-payment-exchange-rate-error.test.js
Error copy was incorrectly referencing base and accrual currency
- Update error text & tests
=> feat(FN-2561): update error text

trade-finance-manager-ui/templates/accessibility-statement.njk
Update TFM Accessibility Statement
Update the statement to reflect those changes after TFM went live
=> fix(DTFS2-7099): update TFM accessibility statement

README.md, gef-ui/templates/index.njk, portal/templates/index.njk, service-unavailable/index.html, trade-finance-manager-ui/templates/index.njk
Favicon was not auto refreshing due to typical favicon caching issues
Adding a query parameter should work to fix this
Unable to test locally
=> Feat/dtfs2 7093/update crown favicon

README.md, portal/server/generateApp.ts, trade-finance-manager-ui/server/generateApp.js
fix issue with gov-uk static folder not being resolved
=> feat(dtfs2 7096): update static folder

e2e-tests/tfm/cypress.config.js, trade-finance-manager-ui/component-tests/utilisation-reports/_macros/report-reconciliation-table.component-test.js, trade-finance-manager-ui/templates/utilisation-reports/_macros/report-reconciliation-table.njk
Checkbox has been moved to a new `Select` column at the end of the row as per design 
- Move checkbox to end of row
- Update component test
=> feat(FN-2562): TFM mark as complete checkbox design

package-lock.json, portal-api/src/v1/controllers/deal-status.controller.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js, trade-finance-manager-ui/package.json, trade-finance-manager-ui/server/controllers/case/underwriting/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/index.test.js, trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.js, trade-finance-manager-ui/server/controllers/case/underwriting/lead-underwriter/index.test.js
Ensure TFM-UI invalid user session does not crash the container
* Deal and user session validation, if void user will be re-directed to problem with service page.
* Added few logs for troubleshooting.
* Improved test coverage.
* Lint fixes.
=> fix(DTFS2-7091): Handle invalid TFM-UI user session

.github/workflows/test.yml, e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js, e2e-tests/portal/cypress/e2e/pages/login/index.js, portal/templates/_partials/before-you-start.njk
Add `Shawbrook` bank to the portal.
* Added to login page NJK partial template.
* Improved component coverage via E2E Cypress test.
=> feat(DTFS2-7124): Add `Shawbrook` bank to portal

package.json
Replace erroneous reference to `dev` with `start`
=> feat(FN-2623): fix start detach script error

.github/workflows/deployment.yml
Ensure database deployment is conditional.
* Introduced `GitHub Actions` compound expression. variable name has been kept consistent inline with other applications.
* Standardised steps name and syntax
=> fix(deployment-script): conditional database deployment script

.github/workflows/feature_deploy.yml
Update feature deploy workflow trigger
=> chore: update-feature-deploy-workflow-trigger

.github/workflows/deployment.yml
Change release-1.5 to `release-2.0`.
=> fix(deployment-script): changed release-1.5 to release-2.9

.github/workflows/deployment.yml, .github/workflows/test.yml
Update `release-1.5` to `release-2.0`
=> fix(deployment): updated release-1.5 to release-2.0

.github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/sca.yml, .github/workflows/test.yml
Update release-1.5 to release-2.0
=> fix(deployment): change release-1.5 to release-2.0

.github/workflows/README.md, azure-functions/README.md, azure-functions/acbs-function/README.md, dtfs-central-api/README.md, e2e-tests/README.md, external-api/README.md, gef-ui/README.md, reverse-proxy/README.md, trade-finance-manager-api/README.md, trade-finance-manager-ui/README.md, utils/README.md, utils/data-migration/README.md
=> fix(release-2.0): formatt `README.md`

.github/workflows/README.md, .github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/sca.yml, .github/workflows/test.yml, azure-functions/README.md, azure-functions/acbs-function/README.md, dtfs-central-api/README.md, e2e-tests/README.md, external-api/README.md, gef-ui/README.md, reverse-proxy/README.md, trade-finance-manager-api/README.md, trade-finance-manager-ui/README.md, utils/README.md, utils/data-migration/README.md
Merge release-2.0 into release-2.1
=> chore(FN): merge release-2.0 into release-2.1

doc/sql-db.md, libs/common/package.json, libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts, libs/common/src/sql-db-connection/reset-database.sh, package-lock.json
We want to merge `release-2.1` into `release-2.2`.
=> feat(FN-2900): update local SQL to use ledger tables (#3159)

doc/sql-db.md, libs/common/package.json, libs/common/src/sql-db-connection/migrations/1712063692770-AddUtilisationReportTables.ts, libs/common/src/sql-db-connection/reset-database.sh, package-lock.json
We want to merge `release-2.2` into `main`.
=> chore: merge 'release-2.2' into 'main'

.gitignore, gef-ui/README.md
Added `local.settings.json` to `.gitignore`.
=> fix(deployment): added local.settings.json to .gitignore

.github/workflows/feature_deploy.yml
Remove parallel deployments to 1 and use clean up script from deployment.yml for cleaning up slots
=> chore(FN): improve feature deploy

portal/server/routes/static.js
Ensure `security.txt` Expires values is up-to-date.
* Updated to `2024-12-31` in ISO-8601-1 format and less than an year as per the [guide](https://www.rfc-editor.org/rfc/rfc9116#section-2.5.5).
=> fix(security.txt): updated the Expires value

doc/npm-workspaces.md, libs/common/README.md
Add some explanation for libs/common multiple exports
=> chore(FN): add readme to libs common explaining its exports

azure-functions/acbs-function/Dockerfile
The currently node Docker image seems to be causing issues with container startup.
Updated to `node` v20 slim image distro as per https://github.com/Azure/azure-functions-docker
=> fix(acbs-docker-image): upgraded to node v20

dtfs-central-api/src/v1/controllers/portal/deal/add-deal-comment.controller.js, dtfs-central-api/src/v1/routes/portal-routes.js, portal-api/api-tests/api-ssrf.api-test.js, portal-api/api-tests/v1/deals/deal-comments.api-test.js, portal-api/api-tests/v1/deals/deals-status.api-test.js, portal-api/src/v1/api.js, portal-api/src/v1/controllers/deal-comments.controller.js, portal-api/src/v1/controllers/deal-status.controller.js, trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/deal-underwriter-managers-decision.controller.js
We need to add audit details to portal endpoints
This PR adds audit details to the `create deal comment` endpoint
=> feat(dtfs2-6966): add audit logs to create deal comment endpoint

dtfs-central-api/src/v1/routes/portal-routes.js, dtfs-central-api/src/v1/swagger-definitions/audit-details.js, dtfs-central-api/src/v1/swagger-definitions/utilisation-reports/selected-fee-records-details.js
There are some yaml semantic errors which need fixing.
- Fixes the errors
=> fix(FN-1750): fix some yaml semantic errors

dtfs-central-api/api-tests/v1/facilities/facility-put.api-test.js, dtfs-central-api/src/v1/controllers/portal/facility/update-facility.controller.js, dtfs-central-api/src/v1/routes/portal-routes.js, e2e-tests/portal/cypress/support/central-api/api.js, e2e-tests/tfm/cypress/support/central-api/api.js, portal-api/api-tests/v1/deals/deals-status-facilities.api-test.js, portal-api/src/v1/api.js, portal-api/src/v1/controllers/deal-status/update-facility-cover-start-dates.js, portal-api/src/v1/controllers/facilities.controller.js, portal-api/src/v1/controllers/loans.controller.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/update-facilities.js, trade-finance-manager-api/src/v1/controllers/update-issued-facilities.js, trade-finance-manager-api/src/v1/helpers/dealHasAllUkefIds.js, utils/mock-data-loader/centralApi.js
We need to add audit details to portal endpoints
This PR adds audit details to the `update facility` endpoint
=> feat(dtfs2-6966): add audit logs to update facility endpoint

dtfs-central-api/api-tests/v1/deals/update-deal-status.api-test.js, dtfs-central-api/api-tests/v1/gef-deals/gef-deal-status-put.api-test.js, dtfs-central-api/src/v1/controllers/portal/deal/update-deal-status.controller.js, dtfs-central-api/src/v1/controllers/portal/deal/update-deal.controller.js, dtfs-central-api/src/v1/controllers/portal/gef-deal/put-gef-deal.status.controller.js, trade-finance-manager-api/api-tests/api-ssrf.api-test.js, trade-finance-manager-api/api-tests/api-test-users.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-update-underwriter-managers-decision.api-test.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/deal-underwriter-managers-decision.controller.js, trade-finance-manager-api/src/v1/controllers/deal.submit.controller.js, trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.js, trade-finance-manager-api/src/v1/controllers/update-portal-deal-status.test.js
We need to add audit details to portal endpoints
This PR captures a missed update deal status endpoint
=> feat(dtfs2-6966): add audit logs to update deal status endpoint

.github/workflows/lint.yml, package-lock.json, package.json
Ensure all `*.yml` files are validated in the pipeline.
* Added `yaml-lint` with GLOB path syntax as a NPM script `validate:yml` and to staged files using `lint-staged` script.
=> feat(DTFS2-7230): added yaml validation

e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js, portal/templates/_partials/before-you-start.njk
Add a newly signed bank `Societe Generale`
* Added to E2E and NJK bank template.
=> feat(DTFS2-7196): add `Societe Generale` bank

docker-compose.yml, dtfs-central-api/api-tests/v1/gef-deals/gef-deal-put.api-test.js, dtfs-central-api/src/v1/controllers/portal/gef-deal/add-min-activities.controller.js, dtfs-central-api/src/v1/controllers/portal/gef-deal/update-deal.controller.js, package.json, portal-api/api-tests/v1/gef/facilities.api-test.js, portal-api/src/v1/gef/controllers/facilities.controller.js, trade-finance-manager-api/api-tests/api-ssrf.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.second-submission.api-test.js, trade-finance-manager-api/src/v1/api.js, trade-finance-manager-api/src/v1/controllers/update-portal-deal-from-MIA-to-MIN.js
There are some misc gef endpoints that we believed were unused in dtfs
This adds audit logs to the endpoints currently in use
=> feat(dtfs2-6966): update missing gef endpoint

trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js, trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
Add empty state message to the premium payments table
=> feat(FN-1617): display message on premium payments tab when no matched facilities found 

trade-finance-manager-ui/component-tests/_macros/select-all-table-cell-checkbox.component-test.js, trade-finance-manager-ui/component-tests/utilisation-reports/_macros/premium-payments-table.component-test.js, trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.test.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/helpers/reconciliation-for-report-helper.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.test.ts, trade-finance-manager-ui/server/types/view-models/utilisation-report-reconciliation-for-report-view-model.ts, trade-finance-manager-ui/templates/_macros/select-all-table-cell-checkbox.njk, trade-finance-manager-ui/templates/_macros/table-cell-checkbox.njk, trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table-row.njk, trade-finance-manager-ui/templates/utilisation-reports/_macros/premium-payments-table.njk
- Added aria-labels to the premium payments table checkboxes
=> feat(FN-3052): add screenreader labels to premium payments table checkboxes

trade-finance-manager-api/api-tests/v1/deals/deals-submit.api-test.js, trade-finance-manager-api/api-tests/v1/deals/deals-submit.facilities.api-test.js, trade-finance-manager-api/src/cron-scheduler-jobs/check-azure-acbs-function.js, trade-finance-manager-api/src/v1/helpers/all-parties-have-urn.js
ACBS prerequisite check has failed due to missing bond related properties.
* Added optional chaining.
* Added mock resolved value to `createACBS`  and `issueAcbsFacilities` functions.
* Fixed CRON expression (every 10 minutes)
=> fix(DTFS2-7284): optional chaining on bond parties

.github/workflows/feature_deploy.yml, .github/workflows/notify.yml
We need to use the notify step to track changes against release-2.3
=> feat(DTFS2-NONE): setup notifications for release 2.3

trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-fee-records-to-key.controller.ts, trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-selected-fee-records-details.controller.ts, trade-finance-manager-api/src/v1/controllers/utilisation-reports/get-utilisation-reports-by-bank-and-year.controller.ts, trade-finance-manager-api/src/v1/controllers/utilisation-reports/update-utilisation-report-status.controller.ts
Ensure methods are called with a consistent pattern and where applicable follow same conventions.
* `axios.isAxiosError` changed to `isAxiosError`
* Used `HttpStatusCodes` where applicable.
=> fix(DTFS2-7305): code consistency

docker-compose.gha.yml, docker-compose.replica-set.yml, docker-compose.yml
Include FF_TFM_FACILITY_END_DATE_ENABLED in tfm-api in docker compose files 
List all changes made to the codebase.
=> feat(DTFS2-7169): update env vars in docker compose

dtfs-central-api/src/v1/routes/middleware/payload-validation/create-validation-middleware-for-schema.ts, dtfs-central-api/src/v1/validation/route-validators/express-validator-result-handler.js, dtfs-central-api/src/v1/validation/route-validators/route-validators.js, trade-finance-manager-api/src/v1/api.js
we have a bug creating facility amendments that only occurs on remote
add logging to middleware to identify the issue
=> fix(dtfs2-7313): add logging to identify remote only issue

e2e-tests/support/tasks.js, e2e-tests/tfm/cypress/e2e/journeys/utilisation-reports/generate-keying-sheet.spec.js, e2e-tests/tfm/cypress/e2e/pages/utilisation-reports/utilisationReportPage.js, trade-finance-manager-ui/component-tests/utilisation-reports/_macros/keying-sheet-table-row.component-test.ts, trade-finance-manager-ui/templates/utilisation-reports/_macros/keying-sheet-table-row.njk
We want to add some e2e tests for generating keying data.
- Adds an e2e test
=> feat(FN-1725): add e2e test for keying sheets

.github/workflows/deployment.yml
Enable `db:migrate` script execution upon deployment.
=> fix(DTFS2-6713): enable db migrate

README.md, doc/sql-db.md, utils/README.md
Some documentation had fallen out of date, lending to some confusion.
- Correct the order of README steps
- Update utils README to have more information on the different commands making up npm run load
- Update sql db documentation
=> feat(FN-3402): update documentation related to data seeding

azure-functions/acbs-function/package.json, dtfs-central-api/package.json, external-api/package.json, gef-ui/package.json, libs/common/package.json, package-lock.json, package.json, portal-api/package.json, portal/package.json, trade-finance-manager-api/package.json, trade-finance-manager-ui/package.json, utils/package.json
- Dependabot flagged some dependency updates.
- Update dependencies.
=> chore(deps): bump dependencies

.github/workflows/feature_deploy.yml
We have a demo where we want to disable automatic deployments for them but not inhibit others pushing code to main, this will be reverted post demo.
=> chore(FN): temporarily disable main deployments to feature env

.github/workflows/feature_deploy.yml
Reverts UK-Export-Finance/dtfs2#3477 and re-enables deployments to the feature environment.
=> chore(FN): re-enable main deployments to feature env

.github/workflows/notify.yml
Re-enable push notifications for branch release-2.3.
=> feat(DTFS2-7368): re-enable teams notifications for release-2.3

.github/workflows/deployment.yml
Ensure release based branches can be deployed.
=> fix(deployment): release deployment

.github/workflows/deployment.yml, libs/common/package.json, package-lock.json
SQL migration deployment script is failing due to inconsistent deployment YAML configuration and missing dependency. 
* Moved `needs` before `needs.setup.outputs.environment` reference.
* Added `husky` to `libs/common` package.json as `npm ci` will execute `npm run prepare`.
=> fix(DTFS2-7288): deployment pipeline 

portal-api/api-tests/v1/gef/external-api.api-test.js
Company house not found.
* Updated return to `422`.
=> fix(company-house): company house not found

trade-finance-manager-ui/component-tests/case/cancellation/effective-from-date.component-test.ts, trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.test.ts, trade-finance-manager-ui/server/controllers/case/cancellation/effective-from-date.controller.ts, trade-finance-manager-ui/server/routes/case/cancellation.ts, trade-finance-manager-ui/server/types/view-models/deal-cancellation/effective-from-date-view-model.ts, trade-finance-manager-ui/server/types/view-models/index.ts, trade-finance-manager-ui/templates/case/cancellation/effective-from-date.njk, trade-finance-manager-ui/test-helpers/test-data/effective-from-date-view-model.ts
The PIM user needs to be able to provide the effective from date for the deal cancellation. This ticket does not include validating the values or making updates to the database
Add bank request date template
Add a new GET endpoint to render this template
=> feat(DTFS2-7300): add effective from date template

trade-finance-manager-ui/component-tests/utilisation-reports/utilisation-report-reconciliation-for-report.component-test.ts, trade-finance-manager-ui/templates/utilisation-reports/utilisation-report-reconciliation-for-report.njk
This PR makes content changes to the utilisation report reconciliation for report page
* Content changes on nunjucks template
* Updated test
=> feat(FN-3449-3450): content changes to reconciliation for report page

external-api/src/cron/index.ts, external-api/src/helpers/cron.ts
Ensure documents CRON job validated
* Void job validation, useful due to unexpected behaviour and micro-service restart.
* Added document upload retries for high volume files (this is currently a workaround as re-calling document upload API once will suffice however due to an-going issue of upload with 5+ files a re-upload is being tested).
=> fix(DTFS2-7444): eStore void job validation

azure-functions/acbs-function/src/functions/acbs-amend-facility-covenant-record.js, azure-functions/acbs-function/src/functions/acbs-amend-facility-guarantee-record.js, azure-functions/acbs-function/src/functions/acbs-amend-facility.js, azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js, azure-functions/acbs-function/src/functions/activity-update-facility-guarantee.js
Facility covenant and guarantee amendments failed due to an `undefined` facility identifier, this PR aims to resolve this by correcting the variable name which supplied to the endpoint URI.
* Amended to correct variable name.
* Minor documentation updates.
=> fix(DTFS2-6616): facility covenant and guarantee record variable correction

portal-api/src/external-api/__mocks__/countries.js, trade-finance-manager-ui/templates/_partials/footer.njk
Various changes which were merged to `prod` under `release-2.0` branch were never merged back to `main`
* Added `disabled: true` to mock countries.
* Added GovUK class to footer link on TFM.
=> fix(DTFS2-7463): merge prod changes to main

.github/workflows/feature_deploy.yml
Point feature deployments at release-2.4.0.
=> chore(FN): swap feature deployments to deploy from release-2.4.0

gef-ui/server/controllers/activities-controller/index.js, gef-ui/server/controllers/application-details/index.js
fix issue due to introduction of default timezone
=> chore(dtfs2-6892): fix issue with pages not using default timezone

docker-compose.yml, trade-finance-manager-ui/server/routes/auth/configs/unauthenticated-auth-sso.ts, trade-finance-manager-ui/server/routes/login/configs/login-sso.ts
update routers to correctly bind `this`
update docker to include env vars
=> feat(dtfs2-6892): fix docker config and update routers to avoid issue with unbound methods

.github/workflows/deployment.yml, .github/workflows/development_infrastructure.yml, .github/workflows/dns.yml, .github/workflows/dns_tfm.yml, .github/workflows/feature_deploy.yml, .github/workflows/infrastructure.yml, .github/workflows/production_infrastructure.yml, .github/workflows/staging_infrastructure.yml, azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js, host.json
When facility amendment is applied on facility type `Loan`, with only `amount` attribute execution should be terminated.
* Facility loan record mapping validation.
* Updated `azure/cli` to `v2.1.0`.
=> fix(DTFS2-7590): facility loan amount amendment

.github/workflows/feature_deploy.yml
Deploy main to feature temporarily while dev is fixed and SSO isn't ready
=> chore(FN): deploy main to feature before SSO is deployed

azure-functions/acbs-function/src/functions/acbs-amend-facility.js
Reintroduce facility amendment covenant and guarantee SOF
* Uncommented relevant code.
=> fix(DTFS2-6616): re-introduce facility amendment covenant and guarantee

cspell.json, e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js, portal/templates/_partials/before-you-start.njk, utils/mock-data-loader/banks/index.js
Add new banks to portal.
* Added `ICICI` and `ABC` bank.
* Added `ICICI` to cspell.json.
* Added both the banks to bank mock data loader.
=> feat(DTFS2-7668): added ICICI and ABC bank

e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-disabled/dashboard-facilities-filter-by-facility-stage.spec.js, e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-disabled/dashboard-facilities-filters.spec.js, e2e-tests/portal/cypress/e2e/journeys/dashboard/dashboard-facilities/deal-cancellation-enabled/dashboard-facilities-filter-by-facility-stage.spec.js, e2e-tests/portal/cypress/e2e/journeys/dashboard/fixtures/index.js, e2e-tests/portal/cypress/e2e/pages/dashboardFacilities.js
The risk expired filter needs e2e tests
Add e2e coverage for the risk expired filter
=> feat(DTFS2-7644): add e2e test for risk expired filter

gef-ui/api-tests/amendments/what-needs-to-change.api-test.ts, gef-ui/api-tests/common-tests/role-validation-api-tests.js, gef-ui/component-tests/includes/application-preview/facilities.component-test.js, gef-ui/component-tests/partials/amendments/what-needs-to-change.component-test.js, gef-ui/server/constants/emails.ts, gef-ui/server/controllers/amendments/what-needs-to-change/what-needs-to-change.get.test.ts, gef-ui/server/controllers/amendments/what-needs-to-change/what-needs-to-change.ts, gef-ui/server/routes/facilities/amendments/index.ts, gef-ui/server/routes/index.js, gef-ui/server/types/deal.ts, gef-ui/server/types/view-models/amendments/what-needs-to-change-view-model.ts, gef-ui/templates/_macros/change-something-else-details.njk, gef-ui/templates/includes/application-preview/facilities.njk, gef-ui/templates/partials/amendments/what-needs-to-change.njk
Add the front end for the 'What needs to change?' amendments page. 
This does not currently fetch or post any backend data related to the amendments as the endpoints for these are still WIP so will be added as a distinct PR. 
End to end tests will also be added separately. 
- Add new route for the page
- Add nunjucks template
- link up to the 'Make a change' button
Screen recording of implementation:
https://github.com/user-attachments/assets/529a121f-6ecf-42c9-bdca-5f6093826733
=> feat(DTFS2-7523): add what needs to change page template

dtfs-central-api/src/helpers/execute-with-sql-transaction.test.ts, dtfs-central-api/src/v1/controllers/portal/facility/get-amendment.controller.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/delete-payment.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-request-review.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/get-fee-record-correction-transient-form-data.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/post-fee-record-correction.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/fee-record-correction/put-fee-record-correction-transient-form-data.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/get-utilisation-report-reconciliation-details-by-id.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-add-fees-to-an-existing-payment-group.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-payment.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-remove-fees-from-payment-group.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-report-data-validation.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-upload-utilisation-report.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-done.controller/index.test.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/put-keying-data-mark-as-to-do.controller/index.test.ts, libs/common/src/test-helpers/test-api-error.ts, trade-finance-manager-api/api-tests/v1/deal-cancellation/submit-deal-cancellation.post.api-test.ts, trade-finance-manager-api/src/v1/controllers/deal-cancellation/delete-deal-cancellation.controller.test.ts, trade-finance-manager-api/src/v1/controllers/deal-cancellation/get-deal-cancellation.controller.test.ts, trade-finance-manager-api/src/v1/controllers/deal-cancellation/submit-deal-cancellation.controller.test.ts, trade-finance-manager-api/src/v1/controllers/deal-cancellation/update-deal-cancellation.controller.test.ts
Our test api error currently is missing a few fields needed for sso tests
Add these missing fields, update constructor to take object
=> feat(DTFS2-6892): update test api error constructor

.github/actions/functions/action.yml, .github/actions/mssql/action.yml, .github/actions/webapp/action.yml, .github/workflows/deployment.yml, .github/workflows/release.yml, .github/workflows/test.yml
Pass node.js version to GH composite module.
* Added `node` inputs to composute GH action.
* Added `ref` to git chekcouts.
* Removed duplicate push directive.
* Minor documentation improvement.
=> fix(DTFS2-7616): effecient deployment

.github/workflows/release.yml
Remove `ref` attribute for release deployment GHA.
=> fix(DTFS2-7616): removed ref attribute

.github/workflows/README.md, azure-functions/acbs-function/src/functions/activity-get-facility-loan-id.js, azure-functions/acbs-function/src/functions/activity-get-facility-master.js, portal/README.md
Merge `release-2.5.1` to `main`.
=> Chore/merge release 2.5.0 to main

.github/actions/mssql/action.yml, .github/actions/rerun/action.yml, .github/actions/webapp/action.yml, .github/workflows/release.yml, .github/workflows/test.yml
Deployment scripts
* Updated deployment scripts and GHA composite modules as per `main`.
=> fix(deployment): updated deployment script as per main

.github/dependabot.yml, .github/workflows/deployment.yml, .github/workflows/development_infrastructure.yml, .github/workflows/production_infrastructure.yml, .github/workflows/release.yml, .github/workflows/staging_infrastructure.yml
Ensure automatic notifications are dispatched to selected channel when a deployment has finished successfully.
* Added `notify` step, this step will invoke a cURL POST request to a selected channel configured for an incoming webhook.
* Removed `notify.yml`.
* Updated TZ to `TIMEZONE` organisation variable.
=> fix(DTFS2-7616): added ms notifications web hook

dtfs-central-api/package.json, package-lock.json, package.json, portal-api/package.json
=> chore(deps): dependencies updates

azure-functions/acbs-function/src/functions/acbs-amend-facility.js
Enable facility amendment SOF for covenant and guarantee records.
* Uncommended SOF calls.
=> fix(DTFS2-7581): enable facility covenant and guarantee amendments in acbs

trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
Updated test mocks to reflect change of year.
* Updated to `2025`.
=> fix(DTFS2-10543): updated test mocks

portal/server/controllers/utilisation-report-service/previous-reports/index.ts, portal/server/controllers/utilisation-report-service/record-correction/provide-utilisation-report-correction/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/add-payment/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/add-to-an-existing-payment/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/check-keying-data/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/confirm-delete-payment/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/edit-payment/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/check-the-information/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/create-record-correction-request/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/record-corrections/request-sent/index.ts, trade-finance-manager-ui/server/controllers/utilisation-reports/utilisation-report-reconciliation-for-report/index.ts
This PR removes all instances of res being passed to a downstream function
* Removed res being passed to another function to render a template
* Added correct string substitution where it was missing for console.errors
=> chore(FN-3742): remove all instances of res being passed to a function

gef-ui/api-tests/amendments/bank-review-date.get.api-test.ts, gef-ui/component-tests/partials/amendments/bank-review-date.component-test.ts, gef-ui/component-tests/partials/amendments/cover-end-date.component-test.ts, gef-ui/component-tests/partials/amendments/do-you-have-a-facility-end-date.component-test.ts, gef-ui/component-tests/partials/amendments/facility-end-date.component-test.ts, gef-ui/component-tests/partials/amendments/facility-value.component-test.ts, gef-ui/server/controllers/amendments/bank-review-date/get-bank-review-date.test.ts, gef-ui/server/controllers/amendments/bank-review-date/get-bank-review-date.ts, gef-ui/server/controllers/amendments/facility-end-date/get-facility-end-date.ts, gef-ui/server/controllers/amendments/helpers/dates.helper.convertDateToDayMonthYearInput.test.ts, gef-ui/server/controllers/amendments/helpers/dates.helper.ts, gef-ui/server/routes/facilities/amendments/index.ts, gef-ui/server/types/view-models/amendments/bank-review-date-view-model.ts, gef-ui/templates/_macros/what-is-a-bank-review-date.njk, gef-ui/templates/partials/amendments/bank-review-date.njk, gef-ui/templates/partials/amendments/do-you-have-a-facility-end-date.njk, gef-ui/templates/partials/bank-review-date.njk
User should be able to add a bank review date to the amendment.
- Add new GET controller to render Bank Review Date page (POST will be a separate PR)
- Add unit, api and component tests
=> feat(DTFS2-7621): add bank review date page

e2e-tests/gef/cypress/e2e/pages/amendments/what-do-you-need-to-change.js, e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-value-journey.happy-path.spec.js, e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/change-facility-value-journey.unhappy-path.spec.js
Facility value e2e test uses old `data-cy` which were updated
Update `data-cy`
=> test(DTFS2-7675): fix amendments e2e test

libs/common/src/helpers/date.test.ts, libs/common/src/helpers/date.ts, portal/api-tests/static-routes.api-test.js, portal/server/routes/static.js
`.well-know/security.txt` has been expired.
* Updated `Expires` directive.
* Added additonal api test cases for file content and expiry date validity.
=> fix(DTFS2-7771): update security.txt

dtfs-central-api/api-tests/v1/portal-facility-amendments/amendment-status-patch.api-test.ts, dtfs-central-api/src/services/portal/facility-amendment.service.ts, dtfs-central-api/src/services/portal/facility-amendment.submitPortalFacilityAmendmentToChecker.service.test.ts, dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.test.ts, dtfs-central-api/src/v1/controllers/portal/facility/patch-amendment-status.controller.ts, dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.test.ts, dtfs-central-api/src/v1/routes/middleware/payload-validation/validate-patch-portal-facility-amendment-status-payload.ts, dtfs-central-api/src/v1/routes/portal-routes.js, gef-ui/api-tests/amendments/check-your-answers.post.api-test.ts, gef-ui/server/controllers/amendments/check-your-answers/post-check-your-answers.test.ts, gef-ui/server/controllers/amendments/check-your-answers/post-check-your-answers.ts, gef-ui/server/controllers/amendments/helpers/navigation.helper.getNextPage.test.ts, gef-ui/server/controllers/amendments/helpers/navigation.helper.getPreviousPage.test.ts, gef-ui/server/controllers/amendments/helpers/navigation.helper.ts, gef-ui/server/routes/facilities/amendments/index.ts, gef-ui/server/services/api.js, gef-ui/test-helpers/mock-amendment.ts, portal-api/src/v1/api.js
The maker needs to be able to submit the amendment to the checker
- Add post check your answers endpoint
- Add api and unit tests
- Remove dealId from dtfs-central-api update amendment status endpoint
=> feat(DTFS2-7796): post check your answers page

dtfs-central-api/src/helpers/get-fee-record-payment-entity-groups.ts, dtfs-central-api/src/services/state-machines/utilisation-report/event-handlers/helpers/get-keying-sheet-fee-payment-shares-for-fee-records.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-records-to-key.controller/helpers.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/get-fee-records-to-key.controller/index.ts, dtfs-central-api/src/v1/controllers/utilisation-report-service/post-keying-data.controller/index.ts
During a dev handover zain asked if we could add some more documentation to this area of code to assist with future maintenance.
- Add docstrings and comments to keying sheet related logic
=> chore(FN-3850): add additional documentation to keying sheet logic

e2e-tests/gef/cypress/e2e/facility/unissued-facilities/AIN/unissued-facilities-change-submit-ukef-AIN.spec.js, package.json, trade-finance-manager-ui/server/controllers/utilisation-reports/find-reports-by-year/index.test.ts
Merge changes from `release-2.5.2` to `main`.
=> chore(merge): merge release-2.5.2 to main

.github/workflows/feature.yml
Ensure `release-2.7` can be deployed to `feature`.
=> chore(deployment): feature deployment

azure-functions/acbs-function/api.js, azure-functions/acbs-function/helpers/http.js, azure-functions/acbs-function/mappings/deal/helpers/get-industry-classification.js, azure-functions/acbs-function/mappings/facility/facility-covenant-amend.js, azure-functions/acbs-function/mappings/facility/facility-covenant-amend.test.js, azure-functions/acbs-function/mappings/facility/facility-guarantee-amend.js, azure-functions/acbs-function/mappings/facility/facility-guarantee-amend.test.js, azure-functions/acbs-function/mappings/facility/facility-loan-amend.js, azure-functions/acbs-function/mappings/facility/helpers/get-exposure-period.js, azure-functions/acbs-function/src/functions/acbs-amend-facility-loan-record.js, azure-functions/acbs-function/src/functions/activity-create-facility-covenant.js, azure-functions/acbs-function/src/functions/activity-create-facility-guarantee.js, azure-functions/acbs-function/src/functions/activity-update-facility-covenant.js, azure-functions/acbs-function/src/functions/activity-update-facility-guarantee.js, azure-functions/acbs-function/src/functions/activity-update-facility-loan-amount.js, azure-functions/acbs-function/src/functions/activity-update-facility-loan.js, azure-functions/acbs-function/src/functions/activity-update-facility-master.js
The facility covenant and guarantee records were not being amended correctly.
* Incorrect property reference has bee corrected.
* Improved test coverage for covenant and guaranteee mapping functions.
* Minor documentation fixes.
* Introduced `HttpStatusCode` to `acbs-function`.
* Minor lint fixes.
=> fix(DTFS2-7826): fix facility covenant and guarantee amendment

.github/workflows/feature.yml, .github/workflows/purge.yml, cspell.json
Ensure `feature` enviornment is also incorporated into automated deployment pipelines.
* Added nightly `main` deployment to `feature` at `00:30`.
* Added feature ACR to `purge.yml`.
* Added an exception to cspell.
=> fix(DTFS2-7846): feature deployment and ACR purge

.github/workflows/deployment.yml, .github/workflows/feature.yml, .github/workflows/purge.yml
=> chore(deployment): updated deployment cron schedule

e2e-tests/portal/cypress/support/commands.js, e2e-tests/portal/cypress/support/portal/addBondDetails.js, e2e-tests/portal/cypress/support/portal/completeAboutBuyerSection.js, e2e-tests/portal/cypress/support/portal/completeAboutFinancialSection.js, e2e-tests/portal/cypress/support/portal/completeAboutSupplierSection.js, e2e-tests/portal/cypress/support/portal/completeBondFeeDetails.js, e2e-tests/portal/cypress/support/portal/completeBondFinancialDetails.js, e2e-tests/portal/cypress/support/portal/completeEligibilityCriteria.js, e2e-tests/portal/cypress/support/portal/completeIssuedBondDetails.js, e2e-tests/portal/cypress/support/portal/completeUnissuedBondDetails.js, e2e-tests/portal/cypress/support/portal/createBssEwcsDeal.js, e2e-tests/portal/cypress/support/portal/fillBankDetails.js, e2e-tests/portal/cypress/support/portal/proceedToReviewAndApproval.js, e2e-tests/portal/cypress/support/portal/startNewSubmission.js
BSS/EWCS E2E tests were creating deals by calling the API directly.
=> chore(DTFS2-7431): clean bss ewcs deal function

libs/common/src/helpers/facility-calculations/index.test.ts, libs/common/src/helpers/facility-calculations/index.ts, trade-finance-manager-api/src/v1/helpers/calculate-gef-facility-fee-record.api-test.js
Revert `guaranteeFee` to `interestPercentage` in fixed fee formula calculation.
=> fix(DTFS2-8016): revert fixed fee formula to interest percentage

e2e-tests/gef/cypress/e2e/pages/application-amendments.js, e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/journeys/return-amendment-to-maker-disabled-for-checker.spec.js, e2e-tests/ukef/cypress/e2e/journeys/portal/amendments/pages/portal/amendment-details-approved-amendment.spec.js
This PR add e2e tests for 7884 and 7924 tickets
Add e2e tests
<details>
<summary>Show/hide</summary>
```json
```
</details>
<details>
<summary>Show/hide</summary>
Add screenshots here.
</details>
=> feat(DTFS2-7884-7924): e2e tests

e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/content.spec.js, e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js, portal-ui/templates/_partials/before-you-start.njk
Add `Banco Santander` to the list.
* Added to nunjucks template.
* Added to Cypress tests.
=> feat(DTFS2-8134): add Banco Santander to banks list

e2e-tests/portal/cypress/e2e/journeys/feature-flag-enabled/content.spec.js, e2e-tests/portal/cypress/e2e/journeys/homepage/content.spec.js, portal-ui/templates/_partials/before-you-start.njk
Merge `release-2.10.0` to `main`.
=> chore(merge): merge release-2.10.0 to main
